// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buff.proto

#ifndef PROTOBUF_buff_2eproto__INCLUDED
#define PROTOBUF_buff_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace faith {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_buff_2eproto();
void protobuf_AssignDesc_buff_2eproto();
void protobuf_ShutdownFile_buff_2eproto();

class buff_proto;
class buff_proto_buff_save_load;
class buff_proto_buff_operation;
class buff_proto_buff_operation_end;
class buff_proto_buff_damage;
class buff_proto_buff_info;
class buff_proto_buff_info_all;

enum e_buff_operation_type {
  e_buff_operation_type_add = 1,
  e_buff_operation_type_del = 2,
  e_buff_operation_type_info = 3
};
bool e_buff_operation_type_IsValid(int value);
const e_buff_operation_type e_buff_operation_type_MIN = e_buff_operation_type_add;
const e_buff_operation_type e_buff_operation_type_MAX = e_buff_operation_type_info;
const int e_buff_operation_type_ARRAYSIZE = e_buff_operation_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_buff_operation_type_descriptor();
inline const ::std::string& e_buff_operation_type_Name(e_buff_operation_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_buff_operation_type_descriptor(), value);
}
inline bool e_buff_operation_type_Parse(
    const ::std::string& name, e_buff_operation_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_buff_operation_type>(
    e_buff_operation_type_descriptor(), name, value);
}
enum e_buff_damage_type {
  e_buff_damage_type_normal = 1,
  e_buff_damage_type_critical = 2,
  e_buff_damage_type_dodge = 3
};
bool e_buff_damage_type_IsValid(int value);
const e_buff_damage_type e_buff_damage_type_MIN = e_buff_damage_type_normal;
const e_buff_damage_type e_buff_damage_type_MAX = e_buff_damage_type_dodge;
const int e_buff_damage_type_ARRAYSIZE = e_buff_damage_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_buff_damage_type_descriptor();
inline const ::std::string& e_buff_damage_type_Name(e_buff_damage_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_buff_damage_type_descriptor(), value);
}
inline bool e_buff_damage_type_Parse(
    const ::std::string& name, e_buff_damage_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_buff_damage_type>(
    e_buff_damage_type_descriptor(), name, value);
}
// ===================================================================

class buff_proto_buff_save_load : public ::google::protobuf::Message {
 public:
  buff_proto_buff_save_load();
  virtual ~buff_proto_buff_save_load();

  buff_proto_buff_save_load(const buff_proto_buff_save_load& from);

  inline buff_proto_buff_save_load& operator=(const buff_proto_buff_save_load& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto_buff_save_load& default_instance();

  void Swap(buff_proto_buff_save_load* other);

  // implements Message ----------------------------------------------

  buff_proto_buff_save_load* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto_buff_save_load& from);
  void MergeFrom(const buff_proto_buff_save_load& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .faith.buff_proto.buff_info data_ary = 1;
  inline int data_ary_size() const;
  inline void clear_data_ary();
  static const int kDataAryFieldNumber = 1;
  inline const ::faith::buff_proto_buff_info& data_ary(int index) const;
  inline ::faith::buff_proto_buff_info* mutable_data_ary(int index);
  inline ::faith::buff_proto_buff_info* add_data_ary();
  inline const ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >&
      data_ary() const;
  inline ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >*
      mutable_data_ary();

  // @@protoc_insertion_point(class_scope:faith.buff_proto.buff_save_load)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info > data_ary_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto_buff_save_load* default_instance_;
};
// -------------------------------------------------------------------

class buff_proto_buff_operation : public ::google::protobuf::Message {
 public:
  buff_proto_buff_operation();
  virtual ~buff_proto_buff_operation();

  buff_proto_buff_operation(const buff_proto_buff_operation& from);

  inline buff_proto_buff_operation& operator=(const buff_proto_buff_operation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto_buff_operation& default_instance();

  void Swap(buff_proto_buff_operation* other);

  // implements Message ----------------------------------------------

  buff_proto_buff_operation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto_buff_operation& from);
  void MergeFrom(const buff_proto_buff_operation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 operation_type = 1;
  inline bool has_operation_type() const;
  inline void clear_operation_type();
  static const int kOperationTypeFieldNumber = 1;
  inline ::google::protobuf::int32 operation_type() const;
  inline void set_operation_type(::google::protobuf::int32 value);

  // optional int64 buff_guid = 5;
  inline bool has_buff_guid() const;
  inline void clear_buff_guid();
  static const int kBuffGuidFieldNumber = 5;
  inline ::google::protobuf::int64 buff_guid() const;
  inline void set_buff_guid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:faith.buff_proto.buff_operation)
 private:
  inline void set_has_operation_type();
  inline void clear_has_operation_type();
  inline void set_has_buff_guid();
  inline void clear_has_buff_guid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 buff_guid_;
  ::google::protobuf::int32 operation_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto_buff_operation* default_instance_;
};
// -------------------------------------------------------------------

class buff_proto_buff_operation_end : public ::google::protobuf::Message {
 public:
  buff_proto_buff_operation_end();
  virtual ~buff_proto_buff_operation_end();

  buff_proto_buff_operation_end(const buff_proto_buff_operation_end& from);

  inline buff_proto_buff_operation_end& operator=(const buff_proto_buff_operation_end& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto_buff_operation_end& default_instance();

  void Swap(buff_proto_buff_operation_end* other);

  // implements Message ----------------------------------------------

  buff_proto_buff_operation_end* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto_buff_operation_end& from);
  void MergeFrom(const buff_proto_buff_operation_end& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 operation_type = 1;
  inline bool has_operation_type() const;
  inline void clear_operation_type();
  static const int kOperationTypeFieldNumber = 1;
  inline ::google::protobuf::int32 operation_type() const;
  inline void set_operation_type(::google::protobuf::int32 value);

  // optional int32 template_id = 2;
  inline bool has_template_id() const;
  inline void clear_template_id();
  static const int kTemplateIdFieldNumber = 2;
  inline ::google::protobuf::int32 template_id() const;
  inline void set_template_id(::google::protobuf::int32 value);

  // optional int32 pile_count = 3;
  inline bool has_pile_count() const;
  inline void clear_pile_count();
  static const int kPileCountFieldNumber = 3;
  inline ::google::protobuf::int32 pile_count() const;
  inline void set_pile_count(::google::protobuf::int32 value);

  // optional int32 time = 4;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 4;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);

  // optional int64 sender_guid = 5;
  inline bool has_sender_guid() const;
  inline void clear_sender_guid();
  static const int kSenderGuidFieldNumber = 5;
  inline ::google::protobuf::int64 sender_guid() const;
  inline void set_sender_guid(::google::protobuf::int64 value);

  // optional int64 target_guid = 6;
  inline bool has_target_guid() const;
  inline void clear_target_guid();
  static const int kTargetGuidFieldNumber = 6;
  inline ::google::protobuf::int64 target_guid() const;
  inline void set_target_guid(::google::protobuf::int64 value);

  // optional int64 buff_guid = 7;
  inline bool has_buff_guid() const;
  inline void clear_buff_guid();
  static const int kBuffGuidFieldNumber = 7;
  inline ::google::protobuf::int64 buff_guid() const;
  inline void set_buff_guid(::google::protobuf::int64 value);

  // optional int32 skill_template_id = 8 [default = 0];
  inline bool has_skill_template_id() const;
  inline void clear_skill_template_id();
  static const int kSkillTemplateIdFieldNumber = 8;
  inline ::google::protobuf::int32 skill_template_id() const;
  inline void set_skill_template_id(::google::protobuf::int32 value);

  // optional int32 effect_index = 9 [default = -1];
  inline bool has_effect_index() const;
  inline void clear_effect_index();
  static const int kEffectIndexFieldNumber = 9;
  inline ::google::protobuf::int32 effect_index() const;
  inline void set_effect_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:faith.buff_proto.buff_operation_end)
 private:
  inline void set_has_operation_type();
  inline void clear_has_operation_type();
  inline void set_has_template_id();
  inline void clear_has_template_id();
  inline void set_has_pile_count();
  inline void clear_has_pile_count();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_sender_guid();
  inline void clear_has_sender_guid();
  inline void set_has_target_guid();
  inline void clear_has_target_guid();
  inline void set_has_buff_guid();
  inline void clear_has_buff_guid();
  inline void set_has_skill_template_id();
  inline void clear_has_skill_template_id();
  inline void set_has_effect_index();
  inline void clear_has_effect_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 operation_type_;
  ::google::protobuf::int32 template_id_;
  ::google::protobuf::int32 pile_count_;
  ::google::protobuf::int32 time_;
  ::google::protobuf::int64 sender_guid_;
  ::google::protobuf::int64 target_guid_;
  ::google::protobuf::int64 buff_guid_;
  ::google::protobuf::int32 skill_template_id_;
  ::google::protobuf::int32 effect_index_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto_buff_operation_end* default_instance_;
};
// -------------------------------------------------------------------

class buff_proto_buff_damage : public ::google::protobuf::Message {
 public:
  buff_proto_buff_damage();
  virtual ~buff_proto_buff_damage();

  buff_proto_buff_damage(const buff_proto_buff_damage& from);

  inline buff_proto_buff_damage& operator=(const buff_proto_buff_damage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto_buff_damage& default_instance();

  void Swap(buff_proto_buff_damage* other);

  // implements Message ----------------------------------------------

  buff_proto_buff_damage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto_buff_damage& from);
  void MergeFrom(const buff_proto_buff_damage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 damage_type = 1;
  inline bool has_damage_type() const;
  inline void clear_damage_type();
  static const int kDamageTypeFieldNumber = 1;
  inline ::google::protobuf::int32 damage_type() const;
  inline void set_damage_type(::google::protobuf::int32 value);

  // optional int64 sender = 2;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 2;
  inline ::google::protobuf::int64 sender() const;
  inline void set_sender(::google::protobuf::int64 value);

  // optional int64 target = 3;
  inline bool has_target() const;
  inline void clear_target();
  static const int kTargetFieldNumber = 3;
  inline ::google::protobuf::int64 target() const;
  inline void set_target(::google::protobuf::int64 value);

  // optional int64 damage_count = 4;
  inline bool has_damage_count() const;
  inline void clear_damage_count();
  static const int kDamageCountFieldNumber = 4;
  inline ::google::protobuf::int64 damage_count() const;
  inline void set_damage_count(::google::protobuf::int64 value);

  // optional int64 elem_damage_count = 5;
  inline bool has_elem_damage_count() const;
  inline void clear_elem_damage_count();
  static const int kElemDamageCountFieldNumber = 5;
  inline ::google::protobuf::int64 elem_damage_count() const;
  inline void set_elem_damage_count(::google::protobuf::int64 value);

  // optional bool is_double = 6 [default = false];
  inline bool has_is_double() const;
  inline void clear_is_double();
  static const int kIsDoubleFieldNumber = 6;
  inline bool is_double() const;
  inline void set_is_double(bool value);

  // optional bool is_dead = 7 [default = false];
  inline bool has_is_dead() const;
  inline void clear_is_dead();
  static const int kIsDeadFieldNumber = 7;
  inline bool is_dead() const;
  inline void set_is_dead(bool value);

  // optional int32 skill_template_id = 8 [default = 0];
  inline bool has_skill_template_id() const;
  inline void clear_skill_template_id();
  static const int kSkillTemplateIdFieldNumber = 8;
  inline ::google::protobuf::int32 skill_template_id() const;
  inline void set_skill_template_id(::google::protobuf::int32 value);

  // optional int64 end_hp = 9 [default = 0];
  inline bool has_end_hp() const;
  inline void clear_end_hp();
  static const int kEndHpFieldNumber = 9;
  inline ::google::protobuf::int64 end_hp() const;
  inline void set_end_hp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:faith.buff_proto.buff_damage)
 private:
  inline void set_has_damage_type();
  inline void clear_has_damage_type();
  inline void set_has_sender();
  inline void clear_has_sender();
  inline void set_has_target();
  inline void clear_has_target();
  inline void set_has_damage_count();
  inline void clear_has_damage_count();
  inline void set_has_elem_damage_count();
  inline void clear_has_elem_damage_count();
  inline void set_has_is_double();
  inline void clear_has_is_double();
  inline void set_has_is_dead();
  inline void clear_has_is_dead();
  inline void set_has_skill_template_id();
  inline void clear_has_skill_template_id();
  inline void set_has_end_hp();
  inline void clear_has_end_hp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 sender_;
  ::google::protobuf::int64 target_;
  ::google::protobuf::int64 damage_count_;
  ::google::protobuf::int32 damage_type_;
  bool is_double_;
  bool is_dead_;
  ::google::protobuf::int64 elem_damage_count_;
  ::google::protobuf::int64 end_hp_;
  ::google::protobuf::int32 skill_template_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto_buff_damage* default_instance_;
};
// -------------------------------------------------------------------

class buff_proto_buff_info : public ::google::protobuf::Message {
 public:
  buff_proto_buff_info();
  virtual ~buff_proto_buff_info();

  buff_proto_buff_info(const buff_proto_buff_info& from);

  inline buff_proto_buff_info& operator=(const buff_proto_buff_info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto_buff_info& default_instance();

  void Swap(buff_proto_buff_info* other);

  // implements Message ----------------------------------------------

  buff_proto_buff_info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto_buff_info& from);
  void MergeFrom(const buff_proto_buff_info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 buff_guid = 1;
  inline bool has_buff_guid() const;
  inline void clear_buff_guid();
  static const int kBuffGuidFieldNumber = 1;
  inline ::google::protobuf::int64 buff_guid() const;
  inline void set_buff_guid(::google::protobuf::int64 value);

  // optional int64 sender_guid = 2;
  inline bool has_sender_guid() const;
  inline void clear_sender_guid();
  static const int kSenderGuidFieldNumber = 2;
  inline ::google::protobuf::int64 sender_guid() const;
  inline void set_sender_guid(::google::protobuf::int64 value);

  // repeated int32 data_ary = 3;
  inline int data_ary_size() const;
  inline void clear_data_ary();
  static const int kDataAryFieldNumber = 3;
  inline ::google::protobuf::int32 data_ary(int index) const;
  inline void set_data_ary(int index, ::google::protobuf::int32 value);
  inline void add_data_ary(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      data_ary() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_data_ary();

  // @@protoc_insertion_point(class_scope:faith.buff_proto.buff_info)
 private:
  inline void set_has_buff_guid();
  inline void clear_has_buff_guid();
  inline void set_has_sender_guid();
  inline void clear_has_sender_guid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 buff_guid_;
  ::google::protobuf::int64 sender_guid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > data_ary_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto_buff_info* default_instance_;
};
// -------------------------------------------------------------------

class buff_proto_buff_info_all : public ::google::protobuf::Message {
 public:
  buff_proto_buff_info_all();
  virtual ~buff_proto_buff_info_all();

  buff_proto_buff_info_all(const buff_proto_buff_info_all& from);

  inline buff_proto_buff_info_all& operator=(const buff_proto_buff_info_all& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto_buff_info_all& default_instance();

  void Swap(buff_proto_buff_info_all* other);

  // implements Message ----------------------------------------------

  buff_proto_buff_info_all* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto_buff_info_all& from);
  void MergeFrom(const buff_proto_buff_info_all& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 target = 1;
  inline bool has_target() const;
  inline void clear_target();
  static const int kTargetFieldNumber = 1;
  inline ::google::protobuf::int64 target() const;
  inline void set_target(::google::protobuf::int64 value);

  // repeated .faith.buff_proto.buff_info buff_info = 2;
  inline int buff_info_size() const;
  inline void clear_buff_info();
  static const int kBuffInfoFieldNumber = 2;
  inline const ::faith::buff_proto_buff_info& buff_info(int index) const;
  inline ::faith::buff_proto_buff_info* mutable_buff_info(int index);
  inline ::faith::buff_proto_buff_info* add_buff_info();
  inline const ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >&
      buff_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >*
      mutable_buff_info();

  // @@protoc_insertion_point(class_scope:faith.buff_proto.buff_info_all)
 private:
  inline void set_has_target();
  inline void clear_has_target();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 target_;
  ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info > buff_info_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto_buff_info_all* default_instance_;
};
// -------------------------------------------------------------------

class buff_proto : public ::google::protobuf::Message {
 public:
  buff_proto();
  virtual ~buff_proto();

  buff_proto(const buff_proto& from);

  inline buff_proto& operator=(const buff_proto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const buff_proto& default_instance();

  void Swap(buff_proto* other);

  // implements Message ----------------------------------------------

  buff_proto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const buff_proto& from);
  void MergeFrom(const buff_proto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef buff_proto_buff_save_load buff_save_load;
  typedef buff_proto_buff_operation buff_operation;
  typedef buff_proto_buff_operation_end buff_operation_end;
  typedef buff_proto_buff_damage buff_damage;
  typedef buff_proto_buff_info buff_info;
  typedef buff_proto_buff_info_all buff_info_all;

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:faith.buff_proto)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_buff_2eproto();
  friend void protobuf_AssignDesc_buff_2eproto();
  friend void protobuf_ShutdownFile_buff_2eproto();

  void InitAsDefaultInstance();
  static buff_proto* default_instance_;
};
// ===================================================================


// ===================================================================

// buff_proto_buff_save_load

// repeated .faith.buff_proto.buff_info data_ary = 1;
inline int buff_proto_buff_save_load::data_ary_size() const {
  return data_ary_.size();
}
inline void buff_proto_buff_save_load::clear_data_ary() {
  data_ary_.Clear();
}
inline const ::faith::buff_proto_buff_info& buff_proto_buff_save_load::data_ary(int index) const {
  return data_ary_.Get(index);
}
inline ::faith::buff_proto_buff_info* buff_proto_buff_save_load::mutable_data_ary(int index) {
  return data_ary_.Mutable(index);
}
inline ::faith::buff_proto_buff_info* buff_proto_buff_save_load::add_data_ary() {
  return data_ary_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >&
buff_proto_buff_save_load::data_ary() const {
  return data_ary_;
}
inline ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >*
buff_proto_buff_save_load::mutable_data_ary() {
  return &data_ary_;
}

// -------------------------------------------------------------------

// buff_proto_buff_operation

// optional int32 operation_type = 1;
inline bool buff_proto_buff_operation::has_operation_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void buff_proto_buff_operation::set_has_operation_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void buff_proto_buff_operation::clear_has_operation_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void buff_proto_buff_operation::clear_operation_type() {
  operation_type_ = 0;
  clear_has_operation_type();
}
inline ::google::protobuf::int32 buff_proto_buff_operation::operation_type() const {
  return operation_type_;
}
inline void buff_proto_buff_operation::set_operation_type(::google::protobuf::int32 value) {
  set_has_operation_type();
  operation_type_ = value;
}

// optional int64 buff_guid = 5;
inline bool buff_proto_buff_operation::has_buff_guid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void buff_proto_buff_operation::set_has_buff_guid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void buff_proto_buff_operation::clear_has_buff_guid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void buff_proto_buff_operation::clear_buff_guid() {
  buff_guid_ = GOOGLE_LONGLONG(0);
  clear_has_buff_guid();
}
inline ::google::protobuf::int64 buff_proto_buff_operation::buff_guid() const {
  return buff_guid_;
}
inline void buff_proto_buff_operation::set_buff_guid(::google::protobuf::int64 value) {
  set_has_buff_guid();
  buff_guid_ = value;
}

// -------------------------------------------------------------------

// buff_proto_buff_operation_end

// optional int32 operation_type = 1;
inline bool buff_proto_buff_operation_end::has_operation_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_operation_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void buff_proto_buff_operation_end::clear_has_operation_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void buff_proto_buff_operation_end::clear_operation_type() {
  operation_type_ = 0;
  clear_has_operation_type();
}
inline ::google::protobuf::int32 buff_proto_buff_operation_end::operation_type() const {
  return operation_type_;
}
inline void buff_proto_buff_operation_end::set_operation_type(::google::protobuf::int32 value) {
  set_has_operation_type();
  operation_type_ = value;
}

// optional int32 template_id = 2;
inline bool buff_proto_buff_operation_end::has_template_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_template_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void buff_proto_buff_operation_end::clear_has_template_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void buff_proto_buff_operation_end::clear_template_id() {
  template_id_ = 0;
  clear_has_template_id();
}
inline ::google::protobuf::int32 buff_proto_buff_operation_end::template_id() const {
  return template_id_;
}
inline void buff_proto_buff_operation_end::set_template_id(::google::protobuf::int32 value) {
  set_has_template_id();
  template_id_ = value;
}

// optional int32 pile_count = 3;
inline bool buff_proto_buff_operation_end::has_pile_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_pile_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void buff_proto_buff_operation_end::clear_has_pile_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void buff_proto_buff_operation_end::clear_pile_count() {
  pile_count_ = 0;
  clear_has_pile_count();
}
inline ::google::protobuf::int32 buff_proto_buff_operation_end::pile_count() const {
  return pile_count_;
}
inline void buff_proto_buff_operation_end::set_pile_count(::google::protobuf::int32 value) {
  set_has_pile_count();
  pile_count_ = value;
}

// optional int32 time = 4;
inline bool buff_proto_buff_operation_end::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void buff_proto_buff_operation_end::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void buff_proto_buff_operation_end::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 buff_proto_buff_operation_end::time() const {
  return time_;
}
inline void buff_proto_buff_operation_end::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// optional int64 sender_guid = 5;
inline bool buff_proto_buff_operation_end::has_sender_guid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_sender_guid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void buff_proto_buff_operation_end::clear_has_sender_guid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void buff_proto_buff_operation_end::clear_sender_guid() {
  sender_guid_ = GOOGLE_LONGLONG(0);
  clear_has_sender_guid();
}
inline ::google::protobuf::int64 buff_proto_buff_operation_end::sender_guid() const {
  return sender_guid_;
}
inline void buff_proto_buff_operation_end::set_sender_guid(::google::protobuf::int64 value) {
  set_has_sender_guid();
  sender_guid_ = value;
}

// optional int64 target_guid = 6;
inline bool buff_proto_buff_operation_end::has_target_guid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_target_guid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void buff_proto_buff_operation_end::clear_has_target_guid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void buff_proto_buff_operation_end::clear_target_guid() {
  target_guid_ = GOOGLE_LONGLONG(0);
  clear_has_target_guid();
}
inline ::google::protobuf::int64 buff_proto_buff_operation_end::target_guid() const {
  return target_guid_;
}
inline void buff_proto_buff_operation_end::set_target_guid(::google::protobuf::int64 value) {
  set_has_target_guid();
  target_guid_ = value;
}

// optional int64 buff_guid = 7;
inline bool buff_proto_buff_operation_end::has_buff_guid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_buff_guid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void buff_proto_buff_operation_end::clear_has_buff_guid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void buff_proto_buff_operation_end::clear_buff_guid() {
  buff_guid_ = GOOGLE_LONGLONG(0);
  clear_has_buff_guid();
}
inline ::google::protobuf::int64 buff_proto_buff_operation_end::buff_guid() const {
  return buff_guid_;
}
inline void buff_proto_buff_operation_end::set_buff_guid(::google::protobuf::int64 value) {
  set_has_buff_guid();
  buff_guid_ = value;
}

// optional int32 skill_template_id = 8 [default = 0];
inline bool buff_proto_buff_operation_end::has_skill_template_id() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_skill_template_id() {
  _has_bits_[0] |= 0x00000080u;
}
inline void buff_proto_buff_operation_end::clear_has_skill_template_id() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void buff_proto_buff_operation_end::clear_skill_template_id() {
  skill_template_id_ = 0;
  clear_has_skill_template_id();
}
inline ::google::protobuf::int32 buff_proto_buff_operation_end::skill_template_id() const {
  return skill_template_id_;
}
inline void buff_proto_buff_operation_end::set_skill_template_id(::google::protobuf::int32 value) {
  set_has_skill_template_id();
  skill_template_id_ = value;
}

// optional int32 effect_index = 9 [default = -1];
inline bool buff_proto_buff_operation_end::has_effect_index() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void buff_proto_buff_operation_end::set_has_effect_index() {
  _has_bits_[0] |= 0x00000100u;
}
inline void buff_proto_buff_operation_end::clear_has_effect_index() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void buff_proto_buff_operation_end::clear_effect_index() {
  effect_index_ = -1;
  clear_has_effect_index();
}
inline ::google::protobuf::int32 buff_proto_buff_operation_end::effect_index() const {
  return effect_index_;
}
inline void buff_proto_buff_operation_end::set_effect_index(::google::protobuf::int32 value) {
  set_has_effect_index();
  effect_index_ = value;
}

// -------------------------------------------------------------------

// buff_proto_buff_damage

// optional int32 damage_type = 1;
inline bool buff_proto_buff_damage::has_damage_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void buff_proto_buff_damage::set_has_damage_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void buff_proto_buff_damage::clear_has_damage_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void buff_proto_buff_damage::clear_damage_type() {
  damage_type_ = 0;
  clear_has_damage_type();
}
inline ::google::protobuf::int32 buff_proto_buff_damage::damage_type() const {
  return damage_type_;
}
inline void buff_proto_buff_damage::set_damage_type(::google::protobuf::int32 value) {
  set_has_damage_type();
  damage_type_ = value;
}

// optional int64 sender = 2;
inline bool buff_proto_buff_damage::has_sender() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void buff_proto_buff_damage::set_has_sender() {
  _has_bits_[0] |= 0x00000002u;
}
inline void buff_proto_buff_damage::clear_has_sender() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void buff_proto_buff_damage::clear_sender() {
  sender_ = GOOGLE_LONGLONG(0);
  clear_has_sender();
}
inline ::google::protobuf::int64 buff_proto_buff_damage::sender() const {
  return sender_;
}
inline void buff_proto_buff_damage::set_sender(::google::protobuf::int64 value) {
  set_has_sender();
  sender_ = value;
}

// optional int64 target = 3;
inline bool buff_proto_buff_damage::has_target() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void buff_proto_buff_damage::set_has_target() {
  _has_bits_[0] |= 0x00000004u;
}
inline void buff_proto_buff_damage::clear_has_target() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void buff_proto_buff_damage::clear_target() {
  target_ = GOOGLE_LONGLONG(0);
  clear_has_target();
}
inline ::google::protobuf::int64 buff_proto_buff_damage::target() const {
  return target_;
}
inline void buff_proto_buff_damage::set_target(::google::protobuf::int64 value) {
  set_has_target();
  target_ = value;
}

// optional int64 damage_count = 4;
inline bool buff_proto_buff_damage::has_damage_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void buff_proto_buff_damage::set_has_damage_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void buff_proto_buff_damage::clear_has_damage_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void buff_proto_buff_damage::clear_damage_count() {
  damage_count_ = GOOGLE_LONGLONG(0);
  clear_has_damage_count();
}
inline ::google::protobuf::int64 buff_proto_buff_damage::damage_count() const {
  return damage_count_;
}
inline void buff_proto_buff_damage::set_damage_count(::google::protobuf::int64 value) {
  set_has_damage_count();
  damage_count_ = value;
}

// optional int64 elem_damage_count = 5;
inline bool buff_proto_buff_damage::has_elem_damage_count() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void buff_proto_buff_damage::set_has_elem_damage_count() {
  _has_bits_[0] |= 0x00000010u;
}
inline void buff_proto_buff_damage::clear_has_elem_damage_count() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void buff_proto_buff_damage::clear_elem_damage_count() {
  elem_damage_count_ = GOOGLE_LONGLONG(0);
  clear_has_elem_damage_count();
}
inline ::google::protobuf::int64 buff_proto_buff_damage::elem_damage_count() const {
  return elem_damage_count_;
}
inline void buff_proto_buff_damage::set_elem_damage_count(::google::protobuf::int64 value) {
  set_has_elem_damage_count();
  elem_damage_count_ = value;
}

// optional bool is_double = 6 [default = false];
inline bool buff_proto_buff_damage::has_is_double() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void buff_proto_buff_damage::set_has_is_double() {
  _has_bits_[0] |= 0x00000020u;
}
inline void buff_proto_buff_damage::clear_has_is_double() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void buff_proto_buff_damage::clear_is_double() {
  is_double_ = false;
  clear_has_is_double();
}
inline bool buff_proto_buff_damage::is_double() const {
  return is_double_;
}
inline void buff_proto_buff_damage::set_is_double(bool value) {
  set_has_is_double();
  is_double_ = value;
}

// optional bool is_dead = 7 [default = false];
inline bool buff_proto_buff_damage::has_is_dead() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void buff_proto_buff_damage::set_has_is_dead() {
  _has_bits_[0] |= 0x00000040u;
}
inline void buff_proto_buff_damage::clear_has_is_dead() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void buff_proto_buff_damage::clear_is_dead() {
  is_dead_ = false;
  clear_has_is_dead();
}
inline bool buff_proto_buff_damage::is_dead() const {
  return is_dead_;
}
inline void buff_proto_buff_damage::set_is_dead(bool value) {
  set_has_is_dead();
  is_dead_ = value;
}

// optional int32 skill_template_id = 8 [default = 0];
inline bool buff_proto_buff_damage::has_skill_template_id() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void buff_proto_buff_damage::set_has_skill_template_id() {
  _has_bits_[0] |= 0x00000080u;
}
inline void buff_proto_buff_damage::clear_has_skill_template_id() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void buff_proto_buff_damage::clear_skill_template_id() {
  skill_template_id_ = 0;
  clear_has_skill_template_id();
}
inline ::google::protobuf::int32 buff_proto_buff_damage::skill_template_id() const {
  return skill_template_id_;
}
inline void buff_proto_buff_damage::set_skill_template_id(::google::protobuf::int32 value) {
  set_has_skill_template_id();
  skill_template_id_ = value;
}

// optional int64 end_hp = 9 [default = 0];
inline bool buff_proto_buff_damage::has_end_hp() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void buff_proto_buff_damage::set_has_end_hp() {
  _has_bits_[0] |= 0x00000100u;
}
inline void buff_proto_buff_damage::clear_has_end_hp() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void buff_proto_buff_damage::clear_end_hp() {
  end_hp_ = GOOGLE_LONGLONG(0);
  clear_has_end_hp();
}
inline ::google::protobuf::int64 buff_proto_buff_damage::end_hp() const {
  return end_hp_;
}
inline void buff_proto_buff_damage::set_end_hp(::google::protobuf::int64 value) {
  set_has_end_hp();
  end_hp_ = value;
}

// -------------------------------------------------------------------

// buff_proto_buff_info

// optional int64 buff_guid = 1;
inline bool buff_proto_buff_info::has_buff_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void buff_proto_buff_info::set_has_buff_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void buff_proto_buff_info::clear_has_buff_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void buff_proto_buff_info::clear_buff_guid() {
  buff_guid_ = GOOGLE_LONGLONG(0);
  clear_has_buff_guid();
}
inline ::google::protobuf::int64 buff_proto_buff_info::buff_guid() const {
  return buff_guid_;
}
inline void buff_proto_buff_info::set_buff_guid(::google::protobuf::int64 value) {
  set_has_buff_guid();
  buff_guid_ = value;
}

// optional int64 sender_guid = 2;
inline bool buff_proto_buff_info::has_sender_guid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void buff_proto_buff_info::set_has_sender_guid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void buff_proto_buff_info::clear_has_sender_guid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void buff_proto_buff_info::clear_sender_guid() {
  sender_guid_ = GOOGLE_LONGLONG(0);
  clear_has_sender_guid();
}
inline ::google::protobuf::int64 buff_proto_buff_info::sender_guid() const {
  return sender_guid_;
}
inline void buff_proto_buff_info::set_sender_guid(::google::protobuf::int64 value) {
  set_has_sender_guid();
  sender_guid_ = value;
}

// repeated int32 data_ary = 3;
inline int buff_proto_buff_info::data_ary_size() const {
  return data_ary_.size();
}
inline void buff_proto_buff_info::clear_data_ary() {
  data_ary_.Clear();
}
inline ::google::protobuf::int32 buff_proto_buff_info::data_ary(int index) const {
  return data_ary_.Get(index);
}
inline void buff_proto_buff_info::set_data_ary(int index, ::google::protobuf::int32 value) {
  data_ary_.Set(index, value);
}
inline void buff_proto_buff_info::add_data_ary(::google::protobuf::int32 value) {
  data_ary_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
buff_proto_buff_info::data_ary() const {
  return data_ary_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
buff_proto_buff_info::mutable_data_ary() {
  return &data_ary_;
}

// -------------------------------------------------------------------

// buff_proto_buff_info_all

// optional int64 target = 1;
inline bool buff_proto_buff_info_all::has_target() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void buff_proto_buff_info_all::set_has_target() {
  _has_bits_[0] |= 0x00000001u;
}
inline void buff_proto_buff_info_all::clear_has_target() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void buff_proto_buff_info_all::clear_target() {
  target_ = GOOGLE_LONGLONG(0);
  clear_has_target();
}
inline ::google::protobuf::int64 buff_proto_buff_info_all::target() const {
  return target_;
}
inline void buff_proto_buff_info_all::set_target(::google::protobuf::int64 value) {
  set_has_target();
  target_ = value;
}

// repeated .faith.buff_proto.buff_info buff_info = 2;
inline int buff_proto_buff_info_all::buff_info_size() const {
  return buff_info_.size();
}
inline void buff_proto_buff_info_all::clear_buff_info() {
  buff_info_.Clear();
}
inline const ::faith::buff_proto_buff_info& buff_proto_buff_info_all::buff_info(int index) const {
  return buff_info_.Get(index);
}
inline ::faith::buff_proto_buff_info* buff_proto_buff_info_all::mutable_buff_info(int index) {
  return buff_info_.Mutable(index);
}
inline ::faith::buff_proto_buff_info* buff_proto_buff_info_all::add_buff_info() {
  return buff_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >&
buff_proto_buff_info_all::buff_info() const {
  return buff_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::faith::buff_proto_buff_info >*
buff_proto_buff_info_all::mutable_buff_info() {
  return &buff_info_;
}

// -------------------------------------------------------------------

// buff_proto


// @@protoc_insertion_point(namespace_scope)

}  // namespace faith

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::faith::e_buff_operation_type>() {
  return ::faith::e_buff_operation_type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::faith::e_buff_damage_type>() {
  return ::faith::e_buff_damage_type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_buff_2eproto__INCLUDED
