// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: convert.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "convert.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hld {

namespace {

const ::google::protobuf::Descriptor* convert_proto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  convert_proto_reflection_ = NULL;
const ::google::protobuf::Descriptor* convert_proto_convert_info_all_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  convert_proto_convert_info_all_reflection_ = NULL;
const ::google::protobuf::Descriptor* convert_proto_convert_info_one_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  convert_proto_convert_info_one_reflection_ = NULL;
const ::google::protobuf::Descriptor* convert_proto_convert_operate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  convert_proto_convert_operate_reflection_ = NULL;
const ::google::protobuf::Descriptor* convert_proto_convert_operate_end_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  convert_proto_convert_operate_end_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_convert_2eproto() {
  protobuf_AddDesc_convert_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "convert.proto");
  GOOGLE_CHECK(file != NULL);
  convert_proto_descriptor_ = file->message_type(0);
  static const int convert_proto_offsets_[1] = {
  };
  convert_proto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      convert_proto_descriptor_,
      convert_proto::default_instance_,
      convert_proto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(convert_proto));
  convert_proto_convert_info_all_descriptor_ = convert_proto_descriptor_->nested_type(0);
  static const int convert_proto_convert_info_all_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_all, convert_times_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_all, convert_max_times_),
  };
  convert_proto_convert_info_all_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      convert_proto_convert_info_all_descriptor_,
      convert_proto_convert_info_all::default_instance_,
      convert_proto_convert_info_all_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_all, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_all, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(convert_proto_convert_info_all));
  convert_proto_convert_info_one_descriptor_ = convert_proto_descriptor_->nested_type(1);
  static const int convert_proto_convert_info_one_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_one, convert_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_one, convert_times_),
  };
  convert_proto_convert_info_one_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      convert_proto_convert_info_one_descriptor_,
      convert_proto_convert_info_one::default_instance_,
      convert_proto_convert_info_one_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_one, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_info_one, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(convert_proto_convert_info_one));
  convert_proto_convert_operate_descriptor_ = convert_proto_descriptor_->nested_type(2);
  static const int convert_proto_convert_operate_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate, convert_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate, convert_num_),
  };
  convert_proto_convert_operate_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      convert_proto_convert_operate_descriptor_,
      convert_proto_convert_operate::default_instance_,
      convert_proto_convert_operate_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(convert_proto_convert_operate));
  convert_proto_convert_operate_end_descriptor_ = convert_proto_descriptor_->nested_type(3);
  static const int convert_proto_convert_operate_end_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, opereate_result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, convert_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, convert_num_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, convert_reward_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, is_tip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, str_exp_),
  };
  convert_proto_convert_operate_end_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      convert_proto_convert_operate_end_descriptor_,
      convert_proto_convert_operate_end::default_instance_,
      convert_proto_convert_operate_end_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(convert_proto_convert_operate_end, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(convert_proto_convert_operate_end));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_convert_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    convert_proto_descriptor_, &convert_proto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    convert_proto_convert_info_all_descriptor_, &convert_proto_convert_info_all::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    convert_proto_convert_info_one_descriptor_, &convert_proto_convert_info_one::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    convert_proto_convert_operate_descriptor_, &convert_proto_convert_operate::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    convert_proto_convert_operate_end_descriptor_, &convert_proto_convert_operate_end::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_convert_2eproto() {
  delete convert_proto::default_instance_;
  delete convert_proto_reflection_;
  delete convert_proto_convert_info_all::default_instance_;
  delete convert_proto_convert_info_all_reflection_;
  delete convert_proto_convert_info_one::default_instance_;
  delete convert_proto_convert_info_one_reflection_;
  delete convert_proto_convert_operate::default_instance_;
  delete convert_proto_convert_operate_reflection_;
  delete convert_proto_convert_operate_end::default_instance_;
  delete convert_proto_convert_operate_end_reflection_;
}

void protobuf_AddDesc_convert_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rconvert.proto\022\003hld\"\351\002\n\rconvert_proto\032D"
    "\n\020convert_info_all\022\025\n\rconvert_times\030\001 \003("
    "\005\022\031\n\021convert_max_times\030\002 \003(\005\032\?\n\020convert_"
    "info_one\022\024\n\014convert_type\030\001 \001(\005\022\025\n\rconver"
    "t_times\030\002 \001(\005\032<\n\017convert_operate\022\024\n\014conv"
    "ert_type\030\001 \001(\005\022\023\n\013convert_num\030\002 \001(\005\032\222\001\n\023"
    "convert_operate_end\022\027\n\017opereate_result\030\001"
    " \001(\005\022\024\n\014convert_type\030\002 \001(\005\022\023\n\013convert_nu"
    "m\030\003 \001(\005\022\026\n\016convert_reward\030\004 \003(\005\022\016\n\006is_ti"
    "p\030\005 \001(\005\022\017\n\007str_exp\030\006 \001(\t", 384);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "convert.proto", &protobuf_RegisterTypes);
  convert_proto::default_instance_ = new convert_proto();
  convert_proto_convert_info_all::default_instance_ = new convert_proto_convert_info_all();
  convert_proto_convert_info_one::default_instance_ = new convert_proto_convert_info_one();
  convert_proto_convert_operate::default_instance_ = new convert_proto_convert_operate();
  convert_proto_convert_operate_end::default_instance_ = new convert_proto_convert_operate_end();
  convert_proto::default_instance_->InitAsDefaultInstance();
  convert_proto_convert_info_all::default_instance_->InitAsDefaultInstance();
  convert_proto_convert_info_one::default_instance_->InitAsDefaultInstance();
  convert_proto_convert_operate::default_instance_->InitAsDefaultInstance();
  convert_proto_convert_operate_end::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_convert_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_convert_2eproto {
  StaticDescriptorInitializer_convert_2eproto() {
    protobuf_AddDesc_convert_2eproto();
  }
} static_descriptor_initializer_convert_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int convert_proto_convert_info_all::kConvertTimesFieldNumber;
const int convert_proto_convert_info_all::kConvertMaxTimesFieldNumber;
#endif  // !_MSC_VER

convert_proto_convert_info_all::convert_proto_convert_info_all()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void convert_proto_convert_info_all::InitAsDefaultInstance() {
}

convert_proto_convert_info_all::convert_proto_convert_info_all(const convert_proto_convert_info_all& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void convert_proto_convert_info_all::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

convert_proto_convert_info_all::~convert_proto_convert_info_all() {
  SharedDtor();
}

void convert_proto_convert_info_all::SharedDtor() {
  if (this != default_instance_) {
  }
}

void convert_proto_convert_info_all::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* convert_proto_convert_info_all::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return convert_proto_convert_info_all_descriptor_;
}

const convert_proto_convert_info_all& convert_proto_convert_info_all::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_convert_2eproto();
  return *default_instance_;
}

convert_proto_convert_info_all* convert_proto_convert_info_all::default_instance_ = NULL;

convert_proto_convert_info_all* convert_proto_convert_info_all::New() const {
  return new convert_proto_convert_info_all;
}

void convert_proto_convert_info_all::Clear() {
  convert_times_.Clear();
  convert_max_times_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool convert_proto_convert_info_all::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 convert_times = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_times:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_convert_times())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_convert_times())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_convert_times;
        if (input->ExpectTag(16)) goto parse_convert_max_times;
        break;
      }

      // repeated int32 convert_max_times = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_max_times:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_convert_max_times())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_convert_max_times())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_convert_max_times;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void convert_proto_convert_info_all::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 convert_times = 1;
  for (int i = 0; i < this->convert_times_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->convert_times(i), output);
  }

  // repeated int32 convert_max_times = 2;
  for (int i = 0; i < this->convert_max_times_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->convert_max_times(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* convert_proto_convert_info_all::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 convert_times = 1;
  for (int i = 0; i < this->convert_times_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->convert_times(i), target);
  }

  // repeated int32 convert_max_times = 2;
  for (int i = 0; i < this->convert_max_times_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->convert_max_times(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int convert_proto_convert_info_all::ByteSize() const {
  int total_size = 0;

  // repeated int32 convert_times = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->convert_times_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->convert_times(i));
    }
    total_size += 1 * this->convert_times_size() + data_size;
  }

  // repeated int32 convert_max_times = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->convert_max_times_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->convert_max_times(i));
    }
    total_size += 1 * this->convert_max_times_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void convert_proto_convert_info_all::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const convert_proto_convert_info_all* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const convert_proto_convert_info_all*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void convert_proto_convert_info_all::MergeFrom(const convert_proto_convert_info_all& from) {
  GOOGLE_CHECK_NE(&from, this);
  convert_times_.MergeFrom(from.convert_times_);
  convert_max_times_.MergeFrom(from.convert_max_times_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void convert_proto_convert_info_all::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void convert_proto_convert_info_all::CopyFrom(const convert_proto_convert_info_all& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool convert_proto_convert_info_all::IsInitialized() const {

  return true;
}

void convert_proto_convert_info_all::Swap(convert_proto_convert_info_all* other) {
  if (other != this) {
    convert_times_.Swap(&other->convert_times_);
    convert_max_times_.Swap(&other->convert_max_times_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata convert_proto_convert_info_all::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = convert_proto_convert_info_all_descriptor_;
  metadata.reflection = convert_proto_convert_info_all_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int convert_proto_convert_info_one::kConvertTypeFieldNumber;
const int convert_proto_convert_info_one::kConvertTimesFieldNumber;
#endif  // !_MSC_VER

convert_proto_convert_info_one::convert_proto_convert_info_one()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void convert_proto_convert_info_one::InitAsDefaultInstance() {
}

convert_proto_convert_info_one::convert_proto_convert_info_one(const convert_proto_convert_info_one& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void convert_proto_convert_info_one::SharedCtor() {
  _cached_size_ = 0;
  convert_type_ = 0;
  convert_times_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

convert_proto_convert_info_one::~convert_proto_convert_info_one() {
  SharedDtor();
}

void convert_proto_convert_info_one::SharedDtor() {
  if (this != default_instance_) {
  }
}

void convert_proto_convert_info_one::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* convert_proto_convert_info_one::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return convert_proto_convert_info_one_descriptor_;
}

const convert_proto_convert_info_one& convert_proto_convert_info_one::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_convert_2eproto();
  return *default_instance_;
}

convert_proto_convert_info_one* convert_proto_convert_info_one::default_instance_ = NULL;

convert_proto_convert_info_one* convert_proto_convert_info_one::New() const {
  return new convert_proto_convert_info_one;
}

void convert_proto_convert_info_one::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    convert_type_ = 0;
    convert_times_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool convert_proto_convert_info_one::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 convert_type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &convert_type_)));
          set_has_convert_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_convert_times;
        break;
      }

      // optional int32 convert_times = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_times:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &convert_times_)));
          set_has_convert_times();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void convert_proto_convert_info_one::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 convert_type = 1;
  if (has_convert_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->convert_type(), output);
  }

  // optional int32 convert_times = 2;
  if (has_convert_times()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->convert_times(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* convert_proto_convert_info_one::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 convert_type = 1;
  if (has_convert_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->convert_type(), target);
  }

  // optional int32 convert_times = 2;
  if (has_convert_times()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->convert_times(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int convert_proto_convert_info_one::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 convert_type = 1;
    if (has_convert_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->convert_type());
    }

    // optional int32 convert_times = 2;
    if (has_convert_times()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->convert_times());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void convert_proto_convert_info_one::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const convert_proto_convert_info_one* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const convert_proto_convert_info_one*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void convert_proto_convert_info_one::MergeFrom(const convert_proto_convert_info_one& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_convert_type()) {
      set_convert_type(from.convert_type());
    }
    if (from.has_convert_times()) {
      set_convert_times(from.convert_times());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void convert_proto_convert_info_one::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void convert_proto_convert_info_one::CopyFrom(const convert_proto_convert_info_one& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool convert_proto_convert_info_one::IsInitialized() const {

  return true;
}

void convert_proto_convert_info_one::Swap(convert_proto_convert_info_one* other) {
  if (other != this) {
    std::swap(convert_type_, other->convert_type_);
    std::swap(convert_times_, other->convert_times_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata convert_proto_convert_info_one::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = convert_proto_convert_info_one_descriptor_;
  metadata.reflection = convert_proto_convert_info_one_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int convert_proto_convert_operate::kConvertTypeFieldNumber;
const int convert_proto_convert_operate::kConvertNumFieldNumber;
#endif  // !_MSC_VER

convert_proto_convert_operate::convert_proto_convert_operate()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void convert_proto_convert_operate::InitAsDefaultInstance() {
}

convert_proto_convert_operate::convert_proto_convert_operate(const convert_proto_convert_operate& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void convert_proto_convert_operate::SharedCtor() {
  _cached_size_ = 0;
  convert_type_ = 0;
  convert_num_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

convert_proto_convert_operate::~convert_proto_convert_operate() {
  SharedDtor();
}

void convert_proto_convert_operate::SharedDtor() {
  if (this != default_instance_) {
  }
}

void convert_proto_convert_operate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* convert_proto_convert_operate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return convert_proto_convert_operate_descriptor_;
}

const convert_proto_convert_operate& convert_proto_convert_operate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_convert_2eproto();
  return *default_instance_;
}

convert_proto_convert_operate* convert_proto_convert_operate::default_instance_ = NULL;

convert_proto_convert_operate* convert_proto_convert_operate::New() const {
  return new convert_proto_convert_operate;
}

void convert_proto_convert_operate::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    convert_type_ = 0;
    convert_num_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool convert_proto_convert_operate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 convert_type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &convert_type_)));
          set_has_convert_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_convert_num;
        break;
      }

      // optional int32 convert_num = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &convert_num_)));
          set_has_convert_num();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void convert_proto_convert_operate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 convert_type = 1;
  if (has_convert_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->convert_type(), output);
  }

  // optional int32 convert_num = 2;
  if (has_convert_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->convert_num(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* convert_proto_convert_operate::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 convert_type = 1;
  if (has_convert_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->convert_type(), target);
  }

  // optional int32 convert_num = 2;
  if (has_convert_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->convert_num(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int convert_proto_convert_operate::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 convert_type = 1;
    if (has_convert_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->convert_type());
    }

    // optional int32 convert_num = 2;
    if (has_convert_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->convert_num());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void convert_proto_convert_operate::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const convert_proto_convert_operate* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const convert_proto_convert_operate*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void convert_proto_convert_operate::MergeFrom(const convert_proto_convert_operate& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_convert_type()) {
      set_convert_type(from.convert_type());
    }
    if (from.has_convert_num()) {
      set_convert_num(from.convert_num());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void convert_proto_convert_operate::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void convert_proto_convert_operate::CopyFrom(const convert_proto_convert_operate& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool convert_proto_convert_operate::IsInitialized() const {

  return true;
}

void convert_proto_convert_operate::Swap(convert_proto_convert_operate* other) {
  if (other != this) {
    std::swap(convert_type_, other->convert_type_);
    std::swap(convert_num_, other->convert_num_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata convert_proto_convert_operate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = convert_proto_convert_operate_descriptor_;
  metadata.reflection = convert_proto_convert_operate_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int convert_proto_convert_operate_end::kOpereateResultFieldNumber;
const int convert_proto_convert_operate_end::kConvertTypeFieldNumber;
const int convert_proto_convert_operate_end::kConvertNumFieldNumber;
const int convert_proto_convert_operate_end::kConvertRewardFieldNumber;
const int convert_proto_convert_operate_end::kIsTipFieldNumber;
const int convert_proto_convert_operate_end::kStrExpFieldNumber;
#endif  // !_MSC_VER

convert_proto_convert_operate_end::convert_proto_convert_operate_end()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void convert_proto_convert_operate_end::InitAsDefaultInstance() {
}

convert_proto_convert_operate_end::convert_proto_convert_operate_end(const convert_proto_convert_operate_end& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void convert_proto_convert_operate_end::SharedCtor() {
  _cached_size_ = 0;
  opereate_result_ = 0;
  convert_type_ = 0;
  convert_num_ = 0;
  is_tip_ = 0;
  str_exp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

convert_proto_convert_operate_end::~convert_proto_convert_operate_end() {
  SharedDtor();
}

void convert_proto_convert_operate_end::SharedDtor() {
  if (str_exp_ != &::google::protobuf::internal::kEmptyString) {
    delete str_exp_;
  }
  if (this != default_instance_) {
  }
}

void convert_proto_convert_operate_end::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* convert_proto_convert_operate_end::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return convert_proto_convert_operate_end_descriptor_;
}

const convert_proto_convert_operate_end& convert_proto_convert_operate_end::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_convert_2eproto();
  return *default_instance_;
}

convert_proto_convert_operate_end* convert_proto_convert_operate_end::default_instance_ = NULL;

convert_proto_convert_operate_end* convert_proto_convert_operate_end::New() const {
  return new convert_proto_convert_operate_end;
}

void convert_proto_convert_operate_end::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    opereate_result_ = 0;
    convert_type_ = 0;
    convert_num_ = 0;
    is_tip_ = 0;
    if (has_str_exp()) {
      if (str_exp_ != &::google::protobuf::internal::kEmptyString) {
        str_exp_->clear();
      }
    }
  }
  convert_reward_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool convert_proto_convert_operate_end::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 opereate_result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &opereate_result_)));
          set_has_opereate_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_convert_type;
        break;
      }

      // optional int32 convert_type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &convert_type_)));
          set_has_convert_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_convert_num;
        break;
      }

      // optional int32 convert_num = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &convert_num_)));
          set_has_convert_num();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_convert_reward;
        break;
      }

      // repeated int32 convert_reward = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_convert_reward:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_convert_reward())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_convert_reward())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_convert_reward;
        if (input->ExpectTag(40)) goto parse_is_tip;
        break;
      }

      // optional int32 is_tip = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_is_tip:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &is_tip_)));
          set_has_is_tip();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_str_exp;
        break;
      }

      // optional string str_exp = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_str_exp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_str_exp()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->str_exp().data(), this->str_exp().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void convert_proto_convert_operate_end::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 opereate_result = 1;
  if (has_opereate_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->opereate_result(), output);
  }

  // optional int32 convert_type = 2;
  if (has_convert_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->convert_type(), output);
  }

  // optional int32 convert_num = 3;
  if (has_convert_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->convert_num(), output);
  }

  // repeated int32 convert_reward = 4;
  for (int i = 0; i < this->convert_reward_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->convert_reward(i), output);
  }

  // optional int32 is_tip = 5;
  if (has_is_tip()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->is_tip(), output);
  }

  // optional string str_exp = 6;
  if (has_str_exp()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->str_exp().data(), this->str_exp().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->str_exp(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* convert_proto_convert_operate_end::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 opereate_result = 1;
  if (has_opereate_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->opereate_result(), target);
  }

  // optional int32 convert_type = 2;
  if (has_convert_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->convert_type(), target);
  }

  // optional int32 convert_num = 3;
  if (has_convert_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->convert_num(), target);
  }

  // repeated int32 convert_reward = 4;
  for (int i = 0; i < this->convert_reward_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->convert_reward(i), target);
  }

  // optional int32 is_tip = 5;
  if (has_is_tip()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->is_tip(), target);
  }

  // optional string str_exp = 6;
  if (has_str_exp()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->str_exp().data(), this->str_exp().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->str_exp(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int convert_proto_convert_operate_end::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 opereate_result = 1;
    if (has_opereate_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->opereate_result());
    }

    // optional int32 convert_type = 2;
    if (has_convert_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->convert_type());
    }

    // optional int32 convert_num = 3;
    if (has_convert_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->convert_num());
    }

    // optional int32 is_tip = 5;
    if (has_is_tip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->is_tip());
    }

    // optional string str_exp = 6;
    if (has_str_exp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->str_exp());
    }

  }
  // repeated int32 convert_reward = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->convert_reward_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->convert_reward(i));
    }
    total_size += 1 * this->convert_reward_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void convert_proto_convert_operate_end::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const convert_proto_convert_operate_end* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const convert_proto_convert_operate_end*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void convert_proto_convert_operate_end::MergeFrom(const convert_proto_convert_operate_end& from) {
  GOOGLE_CHECK_NE(&from, this);
  convert_reward_.MergeFrom(from.convert_reward_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_opereate_result()) {
      set_opereate_result(from.opereate_result());
    }
    if (from.has_convert_type()) {
      set_convert_type(from.convert_type());
    }
    if (from.has_convert_num()) {
      set_convert_num(from.convert_num());
    }
    if (from.has_is_tip()) {
      set_is_tip(from.is_tip());
    }
    if (from.has_str_exp()) {
      set_str_exp(from.str_exp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void convert_proto_convert_operate_end::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void convert_proto_convert_operate_end::CopyFrom(const convert_proto_convert_operate_end& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool convert_proto_convert_operate_end::IsInitialized() const {

  return true;
}

void convert_proto_convert_operate_end::Swap(convert_proto_convert_operate_end* other) {
  if (other != this) {
    std::swap(opereate_result_, other->opereate_result_);
    std::swap(convert_type_, other->convert_type_);
    std::swap(convert_num_, other->convert_num_);
    convert_reward_.Swap(&other->convert_reward_);
    std::swap(is_tip_, other->is_tip_);
    std::swap(str_exp_, other->str_exp_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata convert_proto_convert_operate_end::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = convert_proto_convert_operate_end_descriptor_;
  metadata.reflection = convert_proto_convert_operate_end_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
#endif  // !_MSC_VER

convert_proto::convert_proto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void convert_proto::InitAsDefaultInstance() {
}

convert_proto::convert_proto(const convert_proto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void convert_proto::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

convert_proto::~convert_proto() {
  SharedDtor();
}

void convert_proto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void convert_proto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* convert_proto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return convert_proto_descriptor_;
}

const convert_proto& convert_proto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_convert_2eproto();
  return *default_instance_;
}

convert_proto* convert_proto::default_instance_ = NULL;

convert_proto* convert_proto::New() const {
  return new convert_proto;
}

void convert_proto::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool convert_proto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void convert_proto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* convert_proto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int convert_proto::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void convert_proto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const convert_proto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const convert_proto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void convert_proto::MergeFrom(const convert_proto& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void convert_proto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void convert_proto::CopyFrom(const convert_proto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool convert_proto::IsInitialized() const {

  return true;
}

void convert_proto::Swap(convert_proto* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata convert_proto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = convert_proto_descriptor_;
  metadata.reflection = convert_proto_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hld

// @@protoc_insertion_point(global_scope)
