// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

#ifndef PROTOBUF_error_2eproto__INCLUDED
#define PROTOBUF_error_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace faith {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_error_2eproto();
void protobuf_AssignDesc_error_2eproto();
void protobuf_ShutdownFile_error_2eproto();


enum e_error_code {
  e_error_code_success = 1,
  e_error_code_success_create_account = 2,
  e_error_code_success_queue_login = 3,
  e_error_code_success_queue_complete = 4,
  e_error_code_no_param = 1001,
  e_error_code_fast = 1002,
  e_error_code_no_template = 1003,
  e_error_code_template_param = 1004,
  e_error_code_no_money = 1005,
  e_error_code_no_item = 1006,
  e_error_code_db_error = 1007,
  e_error_code_repeated = 1008,
  e_error_code_dead = 1009,
  e_error_code_no_component = 1010,
  e_error_code_state_error = 1011,
  e_error_code_no_data = 1012,
  e_error_code_login_password_error = 1000000,
  e_error_code_login_repeat_request = 1000001,
  e_error_code_login_invalid_bi = 1000002,
  e_error_code_login_invalid_token = 1000003,
  e_error_code_login_invalid_account = 1000004,
  e_error_code_login_server_internal = 1000005,
  e_error_code_login_aleady_logined = 1000006,
  e_error_code_login_captcha_error = 1000007,
  e_error_code_login_login_queue_full = 1000008,
  e_error_code_login_account_disable = 1000009,
  e_error_code_login_invalid_reconnect_account = 1000010,
  e_error_code_login_gate_login = 1000011,
  e_error_code_login_begin_time = 1000012,
  e_error_code_login_ban = 1000013,
  e_error_code_login_login_full = 1000014,
  e_error_code_login_online_time_limit = 1000015,
  e_error_code_login_online_duration_over = 1000016,
  e_error_code_enter_server_internal_error = 1001000,
  e_error_code_enter_area_not_exist = 1001001,
  e_error_code_enter_no_allow = 1001002,
  e_error_code_enter_error_server_id = 1001003,
  e_error_code_enter_only_create = 1001004,
  e_error_code_map_max_players = 1002000,
  e_error_code_map_map_not_found = 1002001,
  e_error_code_map_too_many_instances = 1002002,
  e_error_code_map_in_combat = 1002003,
  e_error_code_map_low_exp_level = 1002004,
  e_error_code_map_low_force = 1002005,
  e_error_code_map_no_item = 1002006,
  e_error_code_map_no_buff = 1002007,
  e_error_code_map_no_rewarded_quest = 1002008,
  e_error_code_map_in_stall = 1002009,
  e_error_code_map_dead = 1002010,
  e_error_code_map_tran_delete_all_buff = 1002011,
  e_error_code_map_no_job = 1002012,
  e_error_code_map_sex_not_right = 1002013,
  e_error_code_map_ip_limit = 1002014,
  e_error_code_map_instance_full = 1002015,
  e_error_code_map_enter_times_hot = 1002016,
  e_error_code_map_finish_times_hot = 1002017,
  e_error_code_map_not_in_team = 1002018,
  e_error_code_map_db_operationing = 1002019,
  e_error_code_map_flying = 1002020,
  e_error_code_map_mt = 1002021,
  e_error_code_map_enter_scene = 1002022,
  e_error_code_map_init_map_err = 1002023,
  e_error_code_map_enter_map_cd = 1002024,
  e_error_code_map_pk_king_not_begin = 1002025,
  e_error_code_map_pk_king_no_eligibility = 1002026,
  e_error_code_map_broken_sky_not_begin = 1002027,
  e_error_code_map_broken_sky_game_over = 1002028,
  e_error_code_map_cross_server_pk_not_begin = 1002029,
  e_error_code_map_cross_server_pk_session_error = 1002030,
  e_error_code_map_cross_server_pk_end = 1002031,
  e_error_code_map_cross_server_pk_not_start = 1002032,
  e_error_code_map_cross_server_world_boss_begin = 1002033,
  e_error_code_map_cross_server_world_boss_end = 1002034,
  e_error_code_map_cross_server_world_boss_not_start = 1002035,
  e_error_code_map_cross_city_war_not_begin = 1002036,
  e_error_code_map_cross_city_war_map_error = 1002037,
  e_error_code_map_cross_city_war_map_not_find = 1002038,
  e_error_code_map_cross_city_war_map_end = 1002039,
  e_error_code_map_cross_territory_war_not_begin = 1002040,
  e_error_code_map_no_territory_war_qualification = 1002041,
  e_error_code_map_pk_king_ready_end = 1002042,
  e_error_code_map_pk_king_ready_not_join_time = 1002043,
  e_error_code_map_attack_city_game_not_open = 1002044,
  e_error_code_map_attack_city_game_not_begin = 1002045,
  e_error_code_map_attack_city_map_not_join = 1002046,
  e_error_code_map_attack_city_legion_not_join = 1002047,
  e_error_code_map_attack_city_player_max = 1002048,
  e_error_code_map_attack_city_game_end = 1002049,
  e_error_code_map_map_locked = 1002050,
  e_error_code_map_lack_of_money = 1002051,
  e_error_code_map_lack_of_times = 1002052,
  e_error_code_map_player_level_not_enough = 1002053,
  e_error_code_map_player_vip_level_not_enough = 1002054,
  e_error_code_map_cur_map_cant_ready = 1002055,
  e_error_code_map_func_condition_lock = 1002056,
  e_error_code_map_item_num_not_enough = 1002057,
  e_error_code_item_can_not_use = 1003001,
  e_error_code_item_no_item = 1003002,
  e_error_code_item_no_target = 1003003,
  e_error_code_item_create_item = 1003004,
  e_error_code_item_spelling = 1003005,
  e_error_code_item_cd = 1003006,
  e_error_code_item_in_combat = 1003007,
  e_error_code_item_quest = 1003008,
  e_error_code_item_target = 1003009,
  e_error_code_item_regin = 1003010,
  e_error_code_item_level = 1003011,
  e_error_code_item_class = 1003012,
  e_error_code_item_camp = 1003013,
  e_error_code_item_race = 1003014,
  e_error_code_item_gender = 1003015,
  e_error_code_item_spell_learn = 1003016,
  e_error_code_item_specialty_learn = 1003017,
  e_error_code_item_pet_spell_learn = 1003018,
  e_error_code_item_compse_learn = 1003019,
  e_error_code_item_not_identified = 1003020,
  e_error_code_item_not_enough_item = 1003021,
  e_error_code_item_target_too_far = 1003022,
  e_error_code_item_cannot_open_gift_bag = 1003023,
  e_error_code_item_cannot_use_qust_point_bag = 1003024,
  e_error_code_item_cannot_use_prestige_bag = 1003025,
  e_error_code_item_cannot_use_presting_bag = 1003026,
  e_error_code_item_no_catch_pet_skill = 1003027,
  e_error_code_item_all_pet_slot_opened = 1003028,
  e_error_code_item_error_metemp_sychosis_times = 1003029,
  e_error_code_item_spell_learned = 1003030,
  e_error_code_item_success_hc = 1003031,
  e_error_code_item_pk_cannot_use_item1 = 1003032,
  e_error_code_item_item_is_using = 1003033,
  e_error_code_item_invalid = 1003034,
  e_error_code_item_new_position = 1003035,
  e_error_code_item_bag_capacity = 1003036,
  e_error_code_item_never_can_be_discard = 1003037,
  e_error_code_item_ca_not_enough = 1003038,
  e_error_code_item_noneed_item = 1003039,
  e_error_code_item_script_trigger_error = 1003040,
  e_error_code_item_peer_level = 1003041,
  e_error_code_item_vip_level = 1003042,
  e_error_code_item_yuanbao = 1003043,
  e_error_code_item_yuanbao_bind = 1003044,
  e_error_code_item_inherit = 1003045,
  e_error_code_item_advance = 1003046,
  e_error_code_item_upgrade = 1003047,
  e_error_code_item_upgrade_lower1 = 1003048,
  e_error_code_item_upgrade_lower2 = 1003049,
  e_error_code_item_upgrade_lower3 = 1003050,
  e_error_code_item_upgrade_lower4 = 1003051,
  e_error_code_item_upgrade_lower5 = 1003052,
  e_error_code_item_item_use_in_cd = 1003053,
  e_error_code_item_money = 1003054,
  e_error_code_item_jewel = 1003055,
  e_error_code_item_full_level = 1003056,
  e_error_code_item_matirial_not_enough = 1003057,
  e_error_code_item_godassembly = 1003058,
  e_error_code_item_bag_full = 1003059,
  e_error_code_item_composit = 1003060,
  e_error_code_item_add_star_critical = 1003061,
  e_error_code_item_shape_wing_cant_up = 1003062,
  e_error_code_item_chant_show_unactivate_wing = 1003063,
  e_error_code_item_had_this_shape_wing = 1003064,
  e_error_code_item_mount_class_not_reach = 1003065,
  e_error_code_item_pound = 1003066,
  e_error_code_item_equip_same_type = 1003067,
  e_error_code_item_equip_full = 1003068,
  e_error_code_item_element_heart_group_too_high = 1003069,
  e_error_code_item_element_one_refine_no_time = 1003070,
  e_error_code_item_element_ten_refine_no_time = 1003071,
  e_error_code_item_godassembled = 1003072,
  e_error_code_item_spirit_promote_max_level = 1003073,
  e_error_code_item_spirit_promote_not_enough = 1003074,
  e_error_code_item_break_will_active = 1003075,
  e_error_code_item_break_will_no_level = 1003076,
  e_error_code_item_awaken_fetter_no_level = 1003077,
  e_error_code_item_invalid_player_state = 1003078,
  e_error_code_item_invalid_item_template = 1003079,
  e_error_code_item_invalid_prop_template = 1003080,
  e_error_code_item_invalid_use_num = 1003081,
  e_error_code_item_class_type_limit = 1003082,
  e_error_code_item_level_limit = 1003083,
  e_error_code_item_in_cd = 1003084,
  e_error_code_item_fruit_upper_limit = 1003086,
  e_error_code_item_readd_title = 1003087,
  e_error_code_item_element_bag_full = 1003088,
  e_error_code_item_cant_unlock_mount_illusion = 1003089,
  e_error_code_item_cant_unlock_wing_illusion = 1003090,
  e_error_code_item_has_unlocked = 1003091,
  e_error_code_item_over_time = 1003092
};
bool e_error_code_IsValid(int value);
const e_error_code e_error_code_MIN = e_error_code_success;
const e_error_code e_error_code_MAX = e_error_code_item_over_time;
const int e_error_code_ARRAYSIZE = e_error_code_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_error_code_descriptor();
inline const ::std::string& e_error_code_Name(e_error_code value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_error_code_descriptor(), value);
}
inline bool e_error_code_Parse(
    const ::std::string& name, e_error_code* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_error_code>(
    e_error_code_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace faith

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::faith::e_error_code>() {
  return ::faith::e_error_code_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_error_2eproto__INCLUDED
