// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: first_time_do.proto
// Protobuf C++ Version: 5.29.3

#include "first_time_do.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace faith {

inline constexpr first_time_do_proto_first_do_record::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : do_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR first_time_do_proto_first_do_record::first_time_do_proto_first_do_record(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct first_time_do_proto_first_do_recordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR first_time_do_proto_first_do_recordDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~first_time_do_proto_first_do_recordDefaultTypeInternal() {}
  union {
    first_time_do_proto_first_do_record _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 first_time_do_proto_first_do_recordDefaultTypeInternal _first_time_do_proto_first_do_record_default_instance_;

inline constexpr first_time_do_proto_add_first_time_do_record::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : do_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR first_time_do_proto_add_first_time_do_record::first_time_do_proto_add_first_time_do_record(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct first_time_do_proto_add_first_time_do_recordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR first_time_do_proto_add_first_time_do_recordDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~first_time_do_proto_add_first_time_do_recordDefaultTypeInternal() {}
  union {
    first_time_do_proto_add_first_time_do_record _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 first_time_do_proto_add_first_time_do_recordDefaultTypeInternal _first_time_do_proto_add_first_time_do_record_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR first_time_do_proto::first_time_do_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct first_time_do_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR first_time_do_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~first_time_do_protoDefaultTypeInternal() {}
  union {
    first_time_do_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 first_time_do_protoDefaultTypeInternal _first_time_do_proto_default_instance_;

inline constexpr first_time_do_proto_update_first_time_do_records::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : records_{},
        records_num_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR first_time_do_proto_update_first_time_do_records::first_time_do_proto_update_first_time_do_records(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct first_time_do_proto_update_first_time_do_recordsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR first_time_do_proto_update_first_time_do_recordsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~first_time_do_proto_update_first_time_do_recordsDefaultTypeInternal() {}
  union {
    first_time_do_proto_update_first_time_do_records _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 first_time_do_proto_update_first_time_do_recordsDefaultTypeInternal _first_time_do_proto_update_first_time_do_records_default_instance_;

inline constexpr first_time_do_proto_sync_first_time_do_record::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        record_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR first_time_do_proto_sync_first_time_do_record::first_time_do_proto_sync_first_time_do_record(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct first_time_do_proto_sync_first_time_do_recordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR first_time_do_proto_sync_first_time_do_recordDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~first_time_do_proto_sync_first_time_do_recordDefaultTypeInternal() {}
  union {
    first_time_do_proto_sync_first_time_do_record _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 first_time_do_proto_sync_first_time_do_recordDefaultTypeInternal _first_time_do_proto_sync_first_time_do_record_default_instance_;
}  // namespace faith
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_first_5ftime_5fdo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_first_5ftime_5fdo_2eproto = nullptr;
const ::uint32_t
    TableStruct_first_5ftime_5fdo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_first_do_record, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_first_do_record, _impl_.do_type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_update_first_time_do_records, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_update_first_time_do_records, _impl_.records_num_),
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_update_first_time_do_records, _impl_.records_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_add_first_time_do_record, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_add_first_time_do_record, _impl_.do_type_),
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_sync_first_time_do_record, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_sync_first_time_do_record, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto_sync_first_time_do_record, _impl_.record_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::first_time_do_proto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::faith::first_time_do_proto_first_do_record)},
        {9, -1, -1, sizeof(::faith::first_time_do_proto_update_first_time_do_records)},
        {19, -1, -1, sizeof(::faith::first_time_do_proto_add_first_time_do_record)},
        {28, 37, -1, sizeof(::faith::first_time_do_proto_sync_first_time_do_record)},
        {38, -1, -1, sizeof(::faith::first_time_do_proto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::faith::_first_time_do_proto_first_do_record_default_instance_._instance,
    &::faith::_first_time_do_proto_update_first_time_do_records_default_instance_._instance,
    &::faith::_first_time_do_proto_add_first_time_do_record_default_instance_._instance,
    &::faith::_first_time_do_proto_sync_first_time_do_record_default_instance_._instance,
    &::faith::_first_time_do_proto_default_instance_._instance,
};
const char descriptor_table_protodef_first_5ftime_5fdo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023first_time_do.proto\022\005faith\"\261\002\n\023first_t"
    "ime_do_proto\032\"\n\017first_do_record\022\017\n\007do_ty"
    "pe\030\001 \001(\005\032p\n\034update_first_time_do_records"
    "\022\023\n\013records_num\030\001 \001(\005\022;\n\007records\030\002 \003(\0132*"
    ".faith.first_time_do_proto.first_do_reco"
    "rd\032+\n\030add_first_time_do_record\022\017\n\007do_typ"
    "e\030\001 \001(\005\032W\n\031sync_first_time_do_record\022:\n\006"
    "record\030\001 \001(\0132*.faith.first_time_do_proto"
    ".first_do_recordb\006proto3"
};
static ::absl::once_flag descriptor_table_first_5ftime_5fdo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_first_5ftime_5fdo_2eproto = {
    false,
    false,
    344,
    descriptor_table_protodef_first_5ftime_5fdo_2eproto,
    "first_time_do.proto",
    &descriptor_table_first_5ftime_5fdo_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_first_5ftime_5fdo_2eproto::offsets,
    file_level_enum_descriptors_first_5ftime_5fdo_2eproto,
    file_level_service_descriptors_first_5ftime_5fdo_2eproto,
};
namespace faith {
// ===================================================================

class first_time_do_proto_first_do_record::_Internal {
 public:
};

first_time_do_proto_first_do_record::first_time_do_proto_first_do_record(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.first_time_do_proto.first_do_record)
}
first_time_do_proto_first_do_record::first_time_do_proto_first_do_record(
    ::google::protobuf::Arena* arena, const first_time_do_proto_first_do_record& from)
    : first_time_do_proto_first_do_record(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE first_time_do_proto_first_do_record::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void first_time_do_proto_first_do_record::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.do_type_ = {};
}
first_time_do_proto_first_do_record::~first_time_do_proto_first_do_record() {
  // @@protoc_insertion_point(destructor:faith.first_time_do_proto.first_do_record)
  SharedDtor(*this);
}
inline void first_time_do_proto_first_do_record::SharedDtor(MessageLite& self) {
  first_time_do_proto_first_do_record& this_ = static_cast<first_time_do_proto_first_do_record&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* first_time_do_proto_first_do_record::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) first_time_do_proto_first_do_record(arena);
}
constexpr auto first_time_do_proto_first_do_record::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(first_time_do_proto_first_do_record),
                                            alignof(first_time_do_proto_first_do_record));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull first_time_do_proto_first_do_record::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_first_time_do_proto_first_do_record_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &first_time_do_proto_first_do_record::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<first_time_do_proto_first_do_record>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &first_time_do_proto_first_do_record::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<first_time_do_proto_first_do_record>(), &first_time_do_proto_first_do_record::ByteSizeLong,
            &first_time_do_proto_first_do_record::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(first_time_do_proto_first_do_record, _impl_._cached_size_),
        false,
    },
    &first_time_do_proto_first_do_record::kDescriptorMethods,
    &descriptor_table_first_5ftime_5fdo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* first_time_do_proto_first_do_record::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> first_time_do_proto_first_do_record::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::first_time_do_proto_first_do_record>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 do_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(first_time_do_proto_first_do_record, _impl_.do_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(first_time_do_proto_first_do_record, _impl_.do_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 do_type = 1;
    {PROTOBUF_FIELD_OFFSET(first_time_do_proto_first_do_record, _impl_.do_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void first_time_do_proto_first_do_record::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.first_time_do_proto.first_do_record)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.do_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* first_time_do_proto_first_do_record::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const first_time_do_proto_first_do_record& this_ = static_cast<const first_time_do_proto_first_do_record&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* first_time_do_proto_first_do_record::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const first_time_do_proto_first_do_record& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.first_time_do_proto.first_do_record)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 do_type = 1;
          if (this_._internal_do_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_do_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.first_time_do_proto.first_do_record)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t first_time_do_proto_first_do_record::ByteSizeLong(const MessageLite& base) {
          const first_time_do_proto_first_do_record& this_ = static_cast<const first_time_do_proto_first_do_record&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t first_time_do_proto_first_do_record::ByteSizeLong() const {
          const first_time_do_proto_first_do_record& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.first_time_do_proto.first_do_record)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 do_type = 1;
            if (this_._internal_do_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_do_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void first_time_do_proto_first_do_record::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<first_time_do_proto_first_do_record*>(&to_msg);
  auto& from = static_cast<const first_time_do_proto_first_do_record&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.first_time_do_proto.first_do_record)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_do_type() != 0) {
    _this->_impl_.do_type_ = from._impl_.do_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void first_time_do_proto_first_do_record::CopyFrom(const first_time_do_proto_first_do_record& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.first_time_do_proto.first_do_record)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void first_time_do_proto_first_do_record::InternalSwap(first_time_do_proto_first_do_record* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.do_type_, other->_impl_.do_type_);
}

::google::protobuf::Metadata first_time_do_proto_first_do_record::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class first_time_do_proto_update_first_time_do_records::_Internal {
 public:
};

first_time_do_proto_update_first_time_do_records::first_time_do_proto_update_first_time_do_records(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.first_time_do_proto.update_first_time_do_records)
}
inline PROTOBUF_NDEBUG_INLINE first_time_do_proto_update_first_time_do_records::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::faith::first_time_do_proto_update_first_time_do_records& from_msg)
      : records_{visibility, arena, from.records_},
        _cached_size_{0} {}

first_time_do_proto_update_first_time_do_records::first_time_do_proto_update_first_time_do_records(
    ::google::protobuf::Arena* arena,
    const first_time_do_proto_update_first_time_do_records& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  first_time_do_proto_update_first_time_do_records* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.records_num_ = from._impl_.records_num_;

  // @@protoc_insertion_point(copy_constructor:faith.first_time_do_proto.update_first_time_do_records)
}
inline PROTOBUF_NDEBUG_INLINE first_time_do_proto_update_first_time_do_records::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : records_{visibility, arena},
        _cached_size_{0} {}

inline void first_time_do_proto_update_first_time_do_records::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.records_num_ = {};
}
first_time_do_proto_update_first_time_do_records::~first_time_do_proto_update_first_time_do_records() {
  // @@protoc_insertion_point(destructor:faith.first_time_do_proto.update_first_time_do_records)
  SharedDtor(*this);
}
inline void first_time_do_proto_update_first_time_do_records::SharedDtor(MessageLite& self) {
  first_time_do_proto_update_first_time_do_records& this_ = static_cast<first_time_do_proto_update_first_time_do_records&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* first_time_do_proto_update_first_time_do_records::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) first_time_do_proto_update_first_time_do_records(arena);
}
constexpr auto first_time_do_proto_update_first_time_do_records::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(first_time_do_proto_update_first_time_do_records, _impl_.records_) +
          decltype(first_time_do_proto_update_first_time_do_records::_impl_.records_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(first_time_do_proto_update_first_time_do_records), alignof(first_time_do_proto_update_first_time_do_records), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&first_time_do_proto_update_first_time_do_records::PlacementNew_,
                                 sizeof(first_time_do_proto_update_first_time_do_records),
                                 alignof(first_time_do_proto_update_first_time_do_records));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull first_time_do_proto_update_first_time_do_records::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_first_time_do_proto_update_first_time_do_records_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &first_time_do_proto_update_first_time_do_records::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<first_time_do_proto_update_first_time_do_records>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &first_time_do_proto_update_first_time_do_records::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<first_time_do_proto_update_first_time_do_records>(), &first_time_do_proto_update_first_time_do_records::ByteSizeLong,
            &first_time_do_proto_update_first_time_do_records::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(first_time_do_proto_update_first_time_do_records, _impl_._cached_size_),
        false,
    },
    &first_time_do_proto_update_first_time_do_records::kDescriptorMethods,
    &descriptor_table_first_5ftime_5fdo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* first_time_do_proto_update_first_time_do_records::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> first_time_do_proto_update_first_time_do_records::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::first_time_do_proto_update_first_time_do_records>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .faith.first_time_do_proto.first_do_record records = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(first_time_do_proto_update_first_time_do_records, _impl_.records_)}},
    // int32 records_num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(first_time_do_proto_update_first_time_do_records, _impl_.records_num_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(first_time_do_proto_update_first_time_do_records, _impl_.records_num_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 records_num = 1;
    {PROTOBUF_FIELD_OFFSET(first_time_do_proto_update_first_time_do_records, _impl_.records_num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .faith.first_time_do_proto.first_do_record records = 2;
    {PROTOBUF_FIELD_OFFSET(first_time_do_proto_update_first_time_do_records, _impl_.records_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::faith::first_time_do_proto_first_do_record>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void first_time_do_proto_update_first_time_do_records::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.first_time_do_proto.update_first_time_do_records)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.records_.Clear();
  _impl_.records_num_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* first_time_do_proto_update_first_time_do_records::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const first_time_do_proto_update_first_time_do_records& this_ = static_cast<const first_time_do_proto_update_first_time_do_records&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* first_time_do_proto_update_first_time_do_records::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const first_time_do_proto_update_first_time_do_records& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.first_time_do_proto.update_first_time_do_records)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 records_num = 1;
          if (this_._internal_records_num() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_records_num(), target);
          }

          // repeated .faith.first_time_do_proto.first_do_record records = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_records_size());
               i < n; i++) {
            const auto& repfield = this_._internal_records().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.first_time_do_proto.update_first_time_do_records)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t first_time_do_proto_update_first_time_do_records::ByteSizeLong(const MessageLite& base) {
          const first_time_do_proto_update_first_time_do_records& this_ = static_cast<const first_time_do_proto_update_first_time_do_records&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t first_time_do_proto_update_first_time_do_records::ByteSizeLong() const {
          const first_time_do_proto_update_first_time_do_records& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.first_time_do_proto.update_first_time_do_records)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .faith.first_time_do_proto.first_do_record records = 2;
            {
              total_size += 1UL * this_._internal_records_size();
              for (const auto& msg : this_._internal_records()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int32 records_num = 1;
            if (this_._internal_records_num() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_records_num());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void first_time_do_proto_update_first_time_do_records::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<first_time_do_proto_update_first_time_do_records*>(&to_msg);
  auto& from = static_cast<const first_time_do_proto_update_first_time_do_records&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.first_time_do_proto.update_first_time_do_records)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_records()->MergeFrom(
      from._internal_records());
  if (from._internal_records_num() != 0) {
    _this->_impl_.records_num_ = from._impl_.records_num_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void first_time_do_proto_update_first_time_do_records::CopyFrom(const first_time_do_proto_update_first_time_do_records& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.first_time_do_proto.update_first_time_do_records)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void first_time_do_proto_update_first_time_do_records::InternalSwap(first_time_do_proto_update_first_time_do_records* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.records_.InternalSwap(&other->_impl_.records_);
        swap(_impl_.records_num_, other->_impl_.records_num_);
}

::google::protobuf::Metadata first_time_do_proto_update_first_time_do_records::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class first_time_do_proto_add_first_time_do_record::_Internal {
 public:
};

first_time_do_proto_add_first_time_do_record::first_time_do_proto_add_first_time_do_record(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.first_time_do_proto.add_first_time_do_record)
}
first_time_do_proto_add_first_time_do_record::first_time_do_proto_add_first_time_do_record(
    ::google::protobuf::Arena* arena, const first_time_do_proto_add_first_time_do_record& from)
    : first_time_do_proto_add_first_time_do_record(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE first_time_do_proto_add_first_time_do_record::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void first_time_do_proto_add_first_time_do_record::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.do_type_ = {};
}
first_time_do_proto_add_first_time_do_record::~first_time_do_proto_add_first_time_do_record() {
  // @@protoc_insertion_point(destructor:faith.first_time_do_proto.add_first_time_do_record)
  SharedDtor(*this);
}
inline void first_time_do_proto_add_first_time_do_record::SharedDtor(MessageLite& self) {
  first_time_do_proto_add_first_time_do_record& this_ = static_cast<first_time_do_proto_add_first_time_do_record&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* first_time_do_proto_add_first_time_do_record::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) first_time_do_proto_add_first_time_do_record(arena);
}
constexpr auto first_time_do_proto_add_first_time_do_record::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(first_time_do_proto_add_first_time_do_record),
                                            alignof(first_time_do_proto_add_first_time_do_record));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull first_time_do_proto_add_first_time_do_record::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_first_time_do_proto_add_first_time_do_record_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &first_time_do_proto_add_first_time_do_record::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<first_time_do_proto_add_first_time_do_record>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &first_time_do_proto_add_first_time_do_record::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<first_time_do_proto_add_first_time_do_record>(), &first_time_do_proto_add_first_time_do_record::ByteSizeLong,
            &first_time_do_proto_add_first_time_do_record::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(first_time_do_proto_add_first_time_do_record, _impl_._cached_size_),
        false,
    },
    &first_time_do_proto_add_first_time_do_record::kDescriptorMethods,
    &descriptor_table_first_5ftime_5fdo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* first_time_do_proto_add_first_time_do_record::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> first_time_do_proto_add_first_time_do_record::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::first_time_do_proto_add_first_time_do_record>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 do_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(first_time_do_proto_add_first_time_do_record, _impl_.do_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(first_time_do_proto_add_first_time_do_record, _impl_.do_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 do_type = 1;
    {PROTOBUF_FIELD_OFFSET(first_time_do_proto_add_first_time_do_record, _impl_.do_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void first_time_do_proto_add_first_time_do_record::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.first_time_do_proto.add_first_time_do_record)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.do_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* first_time_do_proto_add_first_time_do_record::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const first_time_do_proto_add_first_time_do_record& this_ = static_cast<const first_time_do_proto_add_first_time_do_record&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* first_time_do_proto_add_first_time_do_record::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const first_time_do_proto_add_first_time_do_record& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.first_time_do_proto.add_first_time_do_record)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 do_type = 1;
          if (this_._internal_do_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_do_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.first_time_do_proto.add_first_time_do_record)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t first_time_do_proto_add_first_time_do_record::ByteSizeLong(const MessageLite& base) {
          const first_time_do_proto_add_first_time_do_record& this_ = static_cast<const first_time_do_proto_add_first_time_do_record&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t first_time_do_proto_add_first_time_do_record::ByteSizeLong() const {
          const first_time_do_proto_add_first_time_do_record& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.first_time_do_proto.add_first_time_do_record)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 do_type = 1;
            if (this_._internal_do_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_do_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void first_time_do_proto_add_first_time_do_record::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<first_time_do_proto_add_first_time_do_record*>(&to_msg);
  auto& from = static_cast<const first_time_do_proto_add_first_time_do_record&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.first_time_do_proto.add_first_time_do_record)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_do_type() != 0) {
    _this->_impl_.do_type_ = from._impl_.do_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void first_time_do_proto_add_first_time_do_record::CopyFrom(const first_time_do_proto_add_first_time_do_record& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.first_time_do_proto.add_first_time_do_record)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void first_time_do_proto_add_first_time_do_record::InternalSwap(first_time_do_proto_add_first_time_do_record* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.do_type_, other->_impl_.do_type_);
}

::google::protobuf::Metadata first_time_do_proto_add_first_time_do_record::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class first_time_do_proto_sync_first_time_do_record::_Internal {
 public:
  using HasBits =
      decltype(std::declval<first_time_do_proto_sync_first_time_do_record>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(first_time_do_proto_sync_first_time_do_record, _impl_._has_bits_);
};

first_time_do_proto_sync_first_time_do_record::first_time_do_proto_sync_first_time_do_record(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.first_time_do_proto.sync_first_time_do_record)
}
inline PROTOBUF_NDEBUG_INLINE first_time_do_proto_sync_first_time_do_record::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::faith::first_time_do_proto_sync_first_time_do_record& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

first_time_do_proto_sync_first_time_do_record::first_time_do_proto_sync_first_time_do_record(
    ::google::protobuf::Arena* arena,
    const first_time_do_proto_sync_first_time_do_record& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  first_time_do_proto_sync_first_time_do_record* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.record_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::faith::first_time_do_proto_first_do_record>(
                              arena, *from._impl_.record_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:faith.first_time_do_proto.sync_first_time_do_record)
}
inline PROTOBUF_NDEBUG_INLINE first_time_do_proto_sync_first_time_do_record::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void first_time_do_proto_sync_first_time_do_record::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.record_ = {};
}
first_time_do_proto_sync_first_time_do_record::~first_time_do_proto_sync_first_time_do_record() {
  // @@protoc_insertion_point(destructor:faith.first_time_do_proto.sync_first_time_do_record)
  SharedDtor(*this);
}
inline void first_time_do_proto_sync_first_time_do_record::SharedDtor(MessageLite& self) {
  first_time_do_proto_sync_first_time_do_record& this_ = static_cast<first_time_do_proto_sync_first_time_do_record&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.record_;
  this_._impl_.~Impl_();
}

inline void* first_time_do_proto_sync_first_time_do_record::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) first_time_do_proto_sync_first_time_do_record(arena);
}
constexpr auto first_time_do_proto_sync_first_time_do_record::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(first_time_do_proto_sync_first_time_do_record),
                                            alignof(first_time_do_proto_sync_first_time_do_record));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull first_time_do_proto_sync_first_time_do_record::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_first_time_do_proto_sync_first_time_do_record_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &first_time_do_proto_sync_first_time_do_record::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<first_time_do_proto_sync_first_time_do_record>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &first_time_do_proto_sync_first_time_do_record::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<first_time_do_proto_sync_first_time_do_record>(), &first_time_do_proto_sync_first_time_do_record::ByteSizeLong,
            &first_time_do_proto_sync_first_time_do_record::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(first_time_do_proto_sync_first_time_do_record, _impl_._cached_size_),
        false,
    },
    &first_time_do_proto_sync_first_time_do_record::kDescriptorMethods,
    &descriptor_table_first_5ftime_5fdo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* first_time_do_proto_sync_first_time_do_record::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> first_time_do_proto_sync_first_time_do_record::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(first_time_do_proto_sync_first_time_do_record, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::first_time_do_proto_sync_first_time_do_record>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .faith.first_time_do_proto.first_do_record record = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(first_time_do_proto_sync_first_time_do_record, _impl_.record_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .faith.first_time_do_proto.first_do_record record = 1;
    {PROTOBUF_FIELD_OFFSET(first_time_do_proto_sync_first_time_do_record, _impl_.record_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::faith::first_time_do_proto_first_do_record>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void first_time_do_proto_sync_first_time_do_record::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.first_time_do_proto.sync_first_time_do_record)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.record_ != nullptr);
    _impl_.record_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* first_time_do_proto_sync_first_time_do_record::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const first_time_do_proto_sync_first_time_do_record& this_ = static_cast<const first_time_do_proto_sync_first_time_do_record&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* first_time_do_proto_sync_first_time_do_record::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const first_time_do_proto_sync_first_time_do_record& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.first_time_do_proto.sync_first_time_do_record)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .faith.first_time_do_proto.first_do_record record = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.record_, this_._impl_.record_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.first_time_do_proto.sync_first_time_do_record)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t first_time_do_proto_sync_first_time_do_record::ByteSizeLong(const MessageLite& base) {
          const first_time_do_proto_sync_first_time_do_record& this_ = static_cast<const first_time_do_proto_sync_first_time_do_record&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t first_time_do_proto_sync_first_time_do_record::ByteSizeLong() const {
          const first_time_do_proto_sync_first_time_do_record& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.first_time_do_proto.sync_first_time_do_record)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .faith.first_time_do_proto.first_do_record record = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.record_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void first_time_do_proto_sync_first_time_do_record::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<first_time_do_proto_sync_first_time_do_record*>(&to_msg);
  auto& from = static_cast<const first_time_do_proto_sync_first_time_do_record&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.first_time_do_proto.sync_first_time_do_record)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.record_ != nullptr);
    if (_this->_impl_.record_ == nullptr) {
      _this->_impl_.record_ =
          ::google::protobuf::Message::CopyConstruct<::faith::first_time_do_proto_first_do_record>(arena, *from._impl_.record_);
    } else {
      _this->_impl_.record_->MergeFrom(*from._impl_.record_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void first_time_do_proto_sync_first_time_do_record::CopyFrom(const first_time_do_proto_sync_first_time_do_record& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.first_time_do_proto.sync_first_time_do_record)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void first_time_do_proto_sync_first_time_do_record::InternalSwap(first_time_do_proto_sync_first_time_do_record* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.record_, other->_impl_.record_);
}

::google::protobuf::Metadata first_time_do_proto_sync_first_time_do_record::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class first_time_do_proto::_Internal {
 public:
};

first_time_do_proto::first_time_do_proto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:faith.first_time_do_proto)
}
first_time_do_proto::first_time_do_proto(
    ::google::protobuf::Arena* arena,
    const first_time_do_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  first_time_do_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:faith.first_time_do_proto)
}

inline void* first_time_do_proto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) first_time_do_proto(arena);
}
constexpr auto first_time_do_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(first_time_do_proto),
                                            alignof(first_time_do_proto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull first_time_do_proto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_first_time_do_proto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &first_time_do_proto::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<first_time_do_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &first_time_do_proto::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<first_time_do_proto>(), &first_time_do_proto::ByteSizeLong,
            &first_time_do_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(first_time_do_proto, _impl_._cached_size_),
        false,
    },
    &first_time_do_proto::kDescriptorMethods,
    &descriptor_table_first_5ftime_5fdo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* first_time_do_proto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> first_time_do_proto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::first_time_do_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata first_time_do_proto::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace faith
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_first_5ftime_5fdo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
