// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "net.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace faith {

namespace {

const ::google::protobuf::EnumDescriptor* proto_header_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_net_2eproto() {
  protobuf_AddDesc_net_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "net.proto");
  GOOGLE_CHECK(file != NULL);
  proto_header_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_net_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_net_2eproto() {
}

void protobuf_AddDesc_net_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tnet.proto\022\003hld*\204\234\003\n\014proto_header\022\'\n\"e_"
    "msgindex_s2c_proto_version_wrong\020\220N\022 \n\033e"
    "_msgindex_s2c_common_error\020\221N\022\032\n\025e_msgin"
    "dex_c2fep_ping\020\222N\022\032\n\025e_msgindex_fep2c_pi"
    "ng\020\223N\022\031\n\024e_msgindex_c2cs_ping\020\224N\022\031\n\024e_ms"
    "gindex_cs2c_ping\020\225N\022 \n\033e_msgindex_c2sp_s"
    "erver_list\020\226N\022 \n\033e_msgindex_sp2c_server_"
    "list\020\227N\022\036\n\031e_msgindex_sp2c_role_list\020\230N\022"
    "!\n\034e_msgindex_s2c_rdeencryption\020\364N\022#\n\036e_"
    "msgindex_c2s_encryption_data\020\365N\022#\n\036e_msg"
    "index_s2c_encryption_data\020\366N\022 \n\033e_msgind"
    "ex_c2s_client_login\020\330O\022 \n\033e_msgindex_s2c"
    "_client_login\020\331O\022&\n!e_msgindex_s2c_login"
    "_queue_status\020\332O\022\032\n\025e_msgindex_c2s_logou"
    "t\020\333O\022\032\n\025e_msgindex_s2c_logout\020\334O\022#\n\036e_ms"
    "gindex_s2c_kickout_account\020\335O\022\035\n\030e_msgin"
    "dex_c2s_enum_char\020\336O\022\035\n\030e_msgindex_s2c_e"
    "num_char\020\337O\022\037\n\032e_msgindex_c2s_create_cha"
    "r\020\340O\022\037\n\032e_msgindex_s2c_create_char\020\341O\022\034\n"
    "\027e_msgindex_c2s_del_char\020\342O\022\034\n\027e_msginde"
    "x_s2c_del_char\020\343O\022#\n\036e_msgindex_c2s_logi"
    "n_reconnect\020\344O\022#\n\036e_msgindex_s2c_login_r"
    "econnect\020\345O\022\036\n\031e_msgindex_c2s_enter_game"
    "\020\275P\022\036\n\031e_msgindex_s2c_enter_game\020\276P\022\037\n\032e"
    "_msgindex_c2s_enter_scene\020\277P\022\037\n\032e_msgind"
    "ex_s2c_enter_scene\020\300P\022\"\n\035e_msgindex_c2s_"
    "transfer_scene\020\301P\022\"\n\035e_msgindex_s2c_tran"
    "sfer_scene\020\302P\022*\n%e_msgindex_s2c_map_sync"
    "_all_unit_info\020\303P\022*\n%e_msgindex_s2c_map_"
    "sync_one_unit_info\020\304P\022 \n\033e_msgindex_s2c_"
    "map_line_ary\020\305P\022&\n!e_msgindex_c2s_transf"
    "er_scene_pos\020\306P\022#\n\036e_msgindex_c2s_map_lo"
    "ad_finish\020\307P\022#\n\036e_msgindex_s2c_set_timek"
    "eeping\020\310P\022(\n#e_msgindex_s2c_wave_trigger"
    "_message\020\311P\022\036\n\031e_msgindex_s2c_boss_state"
    "\020\312P\022%\n e_msgindex_s2c_update_map_record\020"
    "\313P\022)\n$e_msgindex_s2c_update_map_record_a"
    "ll\020\314P\022%\n e_msgindex_s2c_protect_npc_stat"
    "e\020\315P\022\"\n\035e_msgindex_s2c_map_game_state\020\316P"
    "\022!\n\034e_msgindex_s2c_map_game_over\020\317P\022!\n\034e"
    "_msgindex_c2s_map_game_gift\020\320P\022!\n\034e_msgi"
    "ndex_s2c_map_game_gift\020\321P\022 \n\033e_msgindex_"
    "s2c_pop_plot_tip\020\322P\022-\n(e_msgindex_s2c_se"
    "nd_msg_to_insert_player\020\323P\022#\n\036e_msgindex"
    "_c2s_get_best_record\020\324P\022\'\n\"e_msgindex_s2"
    "c_get_best_record_end\020\325P\022\"\n\035e_msgindex_s"
    "2c_transfer_error\020\330P\022+\n&e_msgindex_c2s_t"
    "ransfer_to_pk_king_map\020\331P\022%\n e_msgindex_"
    "s2c_pk_king_game_over\020\332P\022.\n)e_msgindex_c"
    "2s_transfer_to_broken_sky_map\020\333P\022(\n#e_ms"
    "gindex_s2c_broken_sky_boss_dead\020\334P\022(\n#e_"
    "msgindex_s2c_broken_sky_game_over\020\335P\022\035\n\030"
    "e_msgindex_c2s_leave_map\020\336P\022 \n\033e_msginde"
    "x_s2c_bosses_state\020\337P\022,\n\'e_msgindex_s2c_"
    "transfer_local_scene_end\020\340P\022$\n\037e_msginde"
    "x_c2s_get_one_map_info\020\341P\022(\n#e_msgindex_"
    "s2c_get_one_map_info_end\020\342P\022\'\n\"e_msginde"
    "x_c2s_transfer_scene_born\020\343P\022$\n\037e_msgind"
    "ex_s2c_server_exp_level\020\344P\022)\n$e_msgindex"
    "_s2c_reconnect_enter_scene\020\345P\022#\n\036e_msgin"
    "dex_s2c_need_hot_update\020\346P\0221\n,e_msgindex"
    "_s2c_gain_treasure_info_update_one\020\347P\0221\n"
    ",e_msgindex_s2c_gain_treasure_info_updat"
    "e_all\020\350P\0221\n,e_msgindex_c2s_gain_treasure"
    "_req_kill_record\020\351P\0221\n,e_msgindex_s2c_ga"
    "in_treasure_kill_record_end\020\352P\0226\n1e_msgi"
    "ndex_c2s_gain_treasure_req_gain_item_rec"
    "ord\020\353P\0226\n1e_msgindex_s2c_gain_treasure_g"
    "ain_item_record_end\020\354P\022/\n*e_msgindex_s2c"
    "_gain_treasure_boss_info_one\020\355P\022/\n*e_msg"
    "index_s2c_gain_treasure_boss_info_all\020\356P"
    "\022(\n#e_msgindex_s2c_boss_island_info_one\020"
    "\357P\022(\n#e_msgindex_s2c_boss_island_info_al"
    "l\020\360P\022/\n*e_msgindex_s2c_player_boss_islan"
    "d_info_one\020\361P\022/\n*e_msgindex_s2c_player_b"
    "oss_island_info_all\020\362P\022(\n#e_msgindex_s2c"
    "_player_server_config\020\363P\022(\n#e_msgindex_c"
    "2s_get_first_raid_award\020\364P\022%\n e_msgindex"
    "_s2c_need_cross_server\020\365P\022(\n#e_msgindex_"
    "s2c_need_cross_server_pk\020\366P\022.\n)e_msginde"
    "x_s2c_need_cross_server_activity\020\367P\022-\n(e"
    "_msgindex_c2s_transfer_to_shui_jing_map\020"
    "\370P\022#\n\036e_msgindex_c2s_get_world_level\020\371P\022"
    "$\n\037e_msgindex_s2c_send_world_level\020\372P\022+\n"
    "&e_msgindex_s2c_need_cross_server_harry\020"
    "\373P\022 \n\033e_msgindex_s2c_random_array\020\374P\022.\n)"
    "e_msgindex_s2c_need_cross_server_city_wa"
    "r\020\375P\0223\n.e_msgindex_s2c_need_cross_server"
    "_territory_war\020\376P\0220\n+e_msgindex_s2c_need"
    "_cross_server_world_boss\020\377P\022,\n\'e_msginde"
    "x_s2c_need_cross_server_ladder\020\200Q\022%\n e_m"
    "sgindex_s2c_need_cross_gm_one\020\201Q\022%\n e_ms"
    "gindex_s2c_need_cross_gm_all\020\202Q\022$\n\037e_msg"
    "index_s2c_send_server_name\020\203Q\022*\n%e_mgsin"
    "dex_s2c_transfer_new_map_error\020\204Q\022-\n(e_m"
    "gsindex_s2c_send_boss_damage_list_msg\020\205Q"
    "\0223\n.e_msgindex_s2c_send_leave_boss_damag"
    "e_list_msg\020\206Q\022)\n$e_msgindex_s2c_send_hel"
    "p_success_msg\020\207Q\022*\n%e_msgindex_s2c_send_"
    "the_attacker_info\020\210Q\022,\n\'e_msgindex_c2s_s"
    "end_buy_simage_boss_num\020\211Q\0220\n+e_msgindex"
    "_s2c_send_buy_simage_boss_num_end\020\212Q\022+\n&"
    "e_msgindex_s2c_can_transfer_other_line\020\213"
    "Q\022+\n&e_msgindex_s2c_legion_auction_item_"
    "tip\020\214Q\022%\n e_msgindex_s2c_is_close_exchan"
    "ge\020\215Q\022 \n\033e_msgindex_s2c_reset_camera\020\216Q\022"
    "%\n e_msgindex_c2s_fuben_vip_mopping\020\217Q\022)"
    "\n$e_msgindex_s2c_fuben_vip_mopping_end\020\220"
    "Q\022&\n!e_msgindex_c2s_load_character_att\020\247"
    "Q\022\"\n\035e_msgindex_s2c_load_role_info\020\250Q\022%\n"
    " e_msgindex_s2c_character_all_att\020\251Q\022%\n "
    "e_msgindex_c2s_character_one_att\020\252Q\022%\n e"
    "_msgindex_s2c_character_one_att\020\253Q\022)\n$e_"
    "msgindex_s2c_sync_unit_create_info\020\254Q\022(\n"
    "#e_msgindex_s2c_sync_unit_world_info\020\255Q\022"
    "(\n#e_msgindex_s2c_sync_unit_other_info\020\256"
    "Q\022&\n!e_msgindex_c2s_character_position\020\257"
    "Q\022&\n!e_msgindex_s2c_character_position\020\260"
    "Q\022\035\n\030e_msgindex_c2s_spawn_npc\020\261Q\022&\n!e_ms"
    "gindex_c2s_map_targger_volume\020\262Q\022\035\n\030e_ms"
    "gindex_c2s_game_over\020\263Q\022\035\n\030e_msgindex_s2"
    "c_game_over\020\264Q\022#\n\036e_msgindex_c2s_charact"
    "er_fuhuo\020\265Q\022#\n\036e_msgindex_s2c_character_"
    "fuhuo\020\266Q\022\035\n\030e_msgindex_s2c_unit_dead\020\267Q\022"
    "\"\n\035e_msgindex_s2c_player_levelup\020\270Q\022\'\n\"e"
    "_msgindex_s2c_character_money_all\020\271Q\022\'\n\""
    "e_msgindex_s2c_character_money_one\020\272Q\022\"\n"
    "\035e_msgindex_s2c_map_fuben_over\020\273Q\022%\n e_m"
    "sgindex_s2c_fuben_send_notice\020\274Q\022(\n#e_ms"
    "gindex_s2c_fuben_info_to_client\020\275Q\022\"\n\035e_"
    "msgindex_c2s_receive_reward\020\276Q\022%\n e_msgi"
    "ndex_s2c_bag_open_slot_num\020\277Q\022\'\n\"e_msgin"
    "dex_c2s_bag_unlock_slot_req\020\300Q\022-\n(e_msgi"
    "ndex_c2s_character_gmorder_message\020\301Q\022-\n"
    "(e_msgindex_s2c_character_gmorder_messag"
    "e\020\302Q\022+\n&e_msgindex_c2s_character_pick_dr"
    "op_box\020\303Q\022!\n\034e_msgindex_s2c_addition_buf"
    "f\020\304Q\022&\n!e_msgindex_s2c_character_info_on"
    "e\020\305Q\022+\n&e_msgindex_s2c_character_pick_dr"
    "op_box\020\306Q\022*\n%e_msgindex_s2c_character_ba"
    "se_att_all\020\307Q\022*\n%e_msgindex_s2c_characte"
    "r_base_att_one\020\310Q\022&\n!e_msgindex_c2s_char"
    "acter_grade_up\020\311Q\022&\n!e_msgindex_s2c_char"
    "acter_grade_up\020\312Q\022%\n e_msgindex_s2c_char"
    "acter_warning\020\313Q\022#\n\036e_msgindex_s2c_chara"
    "cter_error\020\314Q\022\036\n\031e_msgindex_c2s_lucky_dr"
    "aw\020\315Q\022\036\n\031e_msgindex_s2c_lucky_draw\020\316Q\022\036\n"
    "\031e_msgindex_c2s_mopping_up\020\317Q\022$\n\037e_msgin"
    "dex_s2c_mopping_up_award\020\320Q\022\"\n\035e_msginde"
    "x_s2c_mopping_up_end\020\321Q\022+\n&e_msgindex_c2"
    "s_mopping_up_demons_tower\020\322Q\0225\n0e_msgind"
    "ex_c2s_mopping_up_demons_tower_get_award"
    "\020\323Q\0229\n4e_msgindex_s2c_mopping_up_demons_"
    "tower_get_award_end\020\324Q\0220\n+e_msgindex_s2c"
    "_update_demons_tower_info_end\020\325Q\022\"\n\035e_ms"
    "gindex_c2s_change_pk_mode\020\326Q\022&\n!e_msgind"
    "ex_s2c_change_pk_mode_end\020\327Q\022$\n\037e_msgind"
    "ex_s2c_update_community\020\330Q\022\"\n\035e_msgindex"
    "_s2c_enum_char_item\020\331Q\022)\n$e_msgindex_c2s"
    "_get_meditation_reward\020\332Q\022-\n(e_msgindex_"
    "s2c_get_meditation_reward_end\020\333Q\022\"\n\035e_ms"
    "gindex_s2c_stop_mediation\020\334Q\022(\n#e_msgind"
    "ex_s2c_start_meditation_end\020\335Q\022\"\n\035e_msgi"
    "ndex_c2s_stop_mediation\020\336Q\022$\n\037e_msgindex"
    "_c2s_start_meditation\020\337Q\022&\n!e_msgindex_s"
    "2c_character_time_all\020\340Q\022&\n!e_msgindex_s"
    "2c_character_time_one\020\341Q\022&\n!e_msgindex_s"
    "2c_character_info_all\020\342Q\022 \n\033e_msgindex_s"
    "2c_show_message\020\343Q\022%\n e_msgindex_s2c_sco"
    "re_record_list\020\344Q\0220\n+e_msgindex_s2c_broa"
    "dcast_character_info_one\020\345Q\022%\n e_msginde"
    "x_s2c_addition_buff_all\020\346Q\022(\n#e_msgindex"
    "_s2c_map_arena_fuben_over\020\347Q\022.\n)e_msgind"
    "ex_s2c_find_other_unit_spirit_end\020\350Q\0229\n4"
    "e_msgindex_s2c_find_other_unit_wing_or_m"
    "ount_one_end\020\351Q\022,\n\'e_msgindex_s2c_find_o"
    "ther_unit_buff_end\020\352Q\022\"\n\035e_msgindex_s2c_"
    "show_money_get\020\353Q\022$\n\037e_msgindex_c2s_add_"
    "guide_record\020\354Q\022\'\n\"e_msgindex_s2c_update"
    "_guide_record\020\355Q\022!\n\034e_msgindex_s2c_syn_t"
    "ick_time\020\356Q\022!\n\034e_msgindex_c2s_transfer_b"
    "uff\020\357Q\022)\n$e_msgindex_c2s_get_func_unlock"
    "_award\020\360Q\022-\n(e_msgindex_s2c_get_func_unl"
    "ock_award_end\020\361Q\022%\n e_msgindex_c2s_inter"
    "act_with_npc\020\362Q\022+\n&e_msgindex_s2c_intera"
    "ct_with_npc_state\020\363Q\022(\n#e_msgindex_s2c_a"
    "oi_npc_gather_state\020\364Q\022(\n#e_msgindex_s2c"
    "_finish_gather_result\020\365Q\022\'\n\"e_msgindex_c"
    "2s_req_hit_and_get_npc\020\366Q\022+\n&e_msgindex_"
    "s2c_send_highest_record_all\020\367Q\022+\n&e_msgi"
    "ndex_s2c_send_highest_record_one\020\370Q\0223\n.e"
    "_msgindex_c2s_purchase_patron_saint_mark"
    "_slot\020\371Q\0227\n2e_msgindex_s2c_purchase_patr"
    "on_saint_mark_slot_end\020\372Q\022-\n(e_msgindex_"
    "c2s_grade_up_level_ani_finish\020\373Q\022-\n(e_ms"
    "gindex_s2c_grade_up_level_ani_finish\020\374Q\022"
    "$\n\037e_msgindex_s2c_open_server_time\020\375Q\022.\n"
    ")e_msgindex_s2c_find_other_unit_belief_e"
    "nd\020\376Q\022\'\n\"e_msgindex_s2c_character_get_mo"
    "ney\020\377Q\022&\n!e_msgindex_s2c_pk_fight_back_s"
    "ync\020\200R\022#\n\036e_msgindex_s2c_npc_left_hp_per"
    "\020\201R\022!\n\034e_msgindex_c2s_body_base_att\020\202R\022)"
    "\n$e_msgindex_c2s_refresh_body_base_att\020\203"
    "R\022\'\n\"e_msgindex_s2c_character_logic_all\020"
    "\204R\022\'\n\"e_msgindex_s2c_character_logic_one"
    "\020\205R\022&\n!e_msgindex_c2s_treasure_get_przie"
    "\020\206R\022&\n!e_msgindex_s2c_treasure_get_przie"
    "\020\207R\022(\n#e_msgindex_s2c_treasure_record_li"
    "st\020\210R\022\'\n\"e_msgindex_c2s_guide_trigger_st"
    "art\020\211R\022#\n\036e_msgindex_c2s_treasure_notice"
    "\020\212R\022\'\n\"e_msgindex_c2s_jump_raid_animatio"
    "n\020\213R\022%\n e_msgindex_c2s_change_role_class"
    "\020\214R\022)\n$e_msgindex_s2c_change_role_class_"
    "end\020\215R\022&\n!e_msgindex_c2s_change_player_n"
    "ame\020\216R\022*\n%e_msgindex_s2c_change_player_n"
    "ame_end\020\217R\022\'\n\"e_msgindex_c2s_confirm_cha"
    "nge_name\020\220R\022+\n&e_msgindex_c2s_recharge_s"
    "uccess_by_sdk\020\221R\022!\n\034e_msgindex_s2c_cur_s"
    "erver_id\020\222R\022/\n*e_msgindex_c2s_character_"
    "legion_look_first\020\223R\022-\n(e_msgindex_c2s_c"
    "haracter_auto_use_hp_pot\020\224R\022\037\n\032e_msginde"
    "x_s2c_kill_prompt\020\225R\022!\n\034e_msgindex_c2s_a"
    "sk_unit_dead\020\226R\022/\n*e_msgindex_s2c_find_o"
    "ther_unit_feather_end\020\227R\022)\n$e_msgindex_c"
    "2s_change_sky_suit_shape\020\230R\022-\n(e_msginde"
    "x_s2c_change_sky_suit_shape_end\020\231R\022%\n e_"
    "msgindex_s2c_addition_buff_arr\020\232R\022*\n%e_m"
    "sgindex_c2s_get_person_information\020\233R\022+\n"
    "&e_msgindex_s2c_sync_person_information\020"
    "\234R\022-\n(e_msgindex_c2s_modify_person_infor"
    "mation\020\235R\0220\n+e_msgindex_c2s_get_other_pe"
    "rson_information\020\236R\022+\n&e_msgindex_c2s_ge"
    "t_person_infor_reward\020\237R\022/\n*e_msgindex_s"
    "2c_get_person_infor_reward_end\020\240R\0221\n,e_m"
    "sgindex_s2c_sync_other_person_couple_dat"
    "a\020\241R\022&\n!e_msgindex_s2c_character_gs_valu"
    "e\020\242R\0228\n3e_msgindex_s2c_character_find_ot"
    "her_appearance_info\020\243R\0222\n-e_msgindex_c2s"
    "_character_save_appearance_info\020\244R\022.\n)e_"
    "msgindex_c2s_save_appearance_info_to_id\020"
    "\245R\0222\n-e_msgindex_s2c_save_appearance_inf"
    "o_to_id_end\020\246R\022.\n)e_msgindex_c2s_load_ap"
    "pearance_info_by_id\020\247R\0222\n-e_msgindex_s2c"
    "_load_appearance_info_by_id_end\020\250R\022\034\n\027e_"
    "msgindex_c2s_show_vip\020\251R\022\034\n\027e_msgindex_s"
    "2c_show_vip\020\252R\022\"\n\035e_msgindex_s2c_break_m"
    "ap_over\020\253R\022,\n\'e_msgindex_c2s_change_ench"
    "ant_show_type\020\254R\022\"\n\035e_msgindex_c2s_all_m"
    "opping_up\020\255R\022(\n#e_msgindex_c2s_get_role_"
    "competition\020\266R\022)\n$e_msgindex_s2c_sync_ro"
    "le_competition\020\267R\022-\n(e_msgindex_c2s_get_"
    "competition_lv_reward\020\270R\0221\n,e_msgindex_s"
    "2c_get_competition_lv_reward_end\020\271R\0221\n,e"
    "_msgindex_c2s_get_competition_lv_reward_"
    "all\020\272R\022&\n!e_msgindex_c2s_buy_competition"
    "_lv\020\273R\022*\n%e_msgindex_s2c_buy_competition"
    "_lv_end\020\274R\022&\n!e_msgindex_c2s_buy_speical"
    "_manual\020\275R\022*\n%e_msgindex_s2c_buy_speical"
    "_manual_end\020\276R\022+\n&e_msgindex_c2s_send_sp"
    "ecial_server_msg\020\277R\022+\n&e_msgindex_c2s_ge"
    "t_element_competition\020\300R\022,\n\'e_msgindex_s"
    "2c_sync_element_competition\020\301R\0225\n0e_msgi"
    "ndex_c2s_get_element_competition_lv_rewa"
    "rd\020\302R\0229\n4e_msgindex_s2c_get_element_comp"
    "etition_lv_reward_end\020\303R\0229\n4e_msgindex_c"
    "2s_get_element_competition_lv_reward_all"
    "\020\304R\022.\n)e_msgindex_c2s_buy_element_compet"
    "ition_lv\020\305R\0222\n-e_msgindex_s2c_buy_elemen"
    "t_competition_lv_end\020\306R\022.\n)e_msgindex_c2"
    "s_buy_element_speical_manual\020\307R\0222\n-e_msg"
    "index_s2c_buy_element_speical_manual_end"
    "\020\310R\022#\n\036e_msgindex_c2s_skill_operation\020\351R"
    "\022#\n\036e_msgindex_s2c_skill_operation\020\352R\022\"\n"
    "\035e_msgindex_s2c_skill_info_one\020\353R\022\"\n\035e_m"
    "sgindex_s2c_skill_info_all\020\354R\022 \n\033e_msgin"
    "dex_s2c_skill_sub_cd\020\357R\022&\n!e_msgindex_s2"
    "c_skill_change_skill\020\360R\022&\n!e_msgindex_c2"
    "s_skill_change_index\020\361R\022*\n%e_msgindex_s2"
    "c_skill_sync_fixed_param\020\362R\022\037\n\032e_msginde"
    "x_c2s_skill_spell\020\363R\022\037\n\032e_msgindex_s2c_s"
    "kill_spell\020\364R\022\036\n\031e_msgindex_c2s_skill_ca"
    "st\020\365R\022\036\n\031e_msgindex_s2c_skill_cast\020\366R\022\035\n"
    "\030e_msgindex_s2c_skill_fly\020\367R\022\036\n\031e_msgind"
    "ex_c2s_skill_hurt\020\370R\022-\n(e_msgindex_s2c_s"
    "kill_patron_saint_effect\020\371R\022(\n#e_msginde"
    "x_s2c_update_passive_skill\020\372R\022)\n$e_msgin"
    "dex_s2c_trigger_passive_skill\020\373R\022)\n$e_ms"
    "gindex_s2c_passive_skill_up_leve\020\374R\022)\n$e"
    "_msgindex_c2s_passive_skill_up_leve\020\375R\022\'"
    "\n\"e_msgindex_s2c_passive_skill_equip\020\376R\022"
    "\'\n\"e_msgindex_c2s_passive_skill_equip\020\377R"
    "\022\"\n\035e_msgindex_c2s_item_operation\020\315S\022\"\n\035"
    "e_msgindex_s2c_item_operation\020\316S\022)\n$e_ms"
    "gindex_s2c_item_update_character\020\317S\022\035\n\030e"
    "_msgindex_s2c_item_tidy\020\320S\022+\n&e_msgindex"
    "_s2c_item_recovery_earn_info\020\321S\022\'\n\"e_msg"
    "index_s2c_item_sell_earn_info\020\322S\022!\n\034e_ms"
    "gindex_s2c_item_composit\020\323S\022!\n\034e_msginde"
    "x_c2s_item_composit\020\324S\0225\n0e_msgindex_s2c"
    "_item_succinct_temp_property_value\020\325S\022\"\n"
    "\035e_msgindex_s2c_show_this_whig\020\326S\022\034\n\027e_m"
    "sgindex_s2c_get_item\020\327S\022&\n!e_msgindex_s2"
    "c_change_mount_shape\020\330S\022\033\n\026e_msgindex_s2"
    "c_item_cd\020\331S\022,\n\'e_msgindex_c2s_equip_end"
    "_load_new_shape\020\332S\022(\n#e_msgindex_c2s_set"
    "_quick_call_mount\020\333S\022+\n&e_msgindex_s2c_u"
    "pdate_quick_call_mount\020\334S\022!\n\034e_msgindex_"
    "c2s_get_hope_item\020\335S\022%\n e_msgindex_s2c_g"
    "et_hope_item_end\020\336S\022 \n\033e_msgindex_s2c_it"
    "em_use_end\020\337S\022\037\n\032e_msgindex_s2c_item_del"
    "ete\020\340S\022\"\n\035e_msgindex_s2c_item_merge_end\020"
    "\341S\022\'\n\"e_msgindex_s2c_auto_inherit_result"
    "\020\342S\022,\n\'e_msgindex_s2c_show_item_upgrade_"
    "effect\020\343S\022\035\n\030e_msgindex_s2c_add_money\020\344S"
    "\022\034\n\027e_msgindex_s2c_add_item\020\345S\022$\n\037e_msgi"
    "ndex_s2c_load_record_info\020\346S\022\'\n\"e_msgind"
    "ex_s2c_operate_record_info\020\347S\022-\n(e_msgin"
    "dex_c2s_patron_saint_mark_upgrade\020\350S\0221\n,"
    "e_msgindex_s2c_patron_saint_mark_upgrade"
    "_end\020\351S\022-\n(e_msgindex_c2s_patron_saint_m"
    "ark_operate\020\352S\0221\n,e_msgindex_s2c_patron_"
    "saint_mark_operate_end\020\353S\022(\n#e_msgindex_"
    "s2c_item_one_key_use_end\020\354S\022&\n!e_msginde"
    "x_s2c_item_show_goto_bag\020\355S\022%\n e_msginde"
    "x_s2c_update_quickly_hp\020\356S\022 \n\033e_msgindex"
    "_s2c_show_fashion\020\357S\022 \n\033e_msgindex_c2s_s"
    "how_fashion\020\360S\022$\n\037e_msgindex_s2c_unlock_"
    "skill_end\020\361S\022 \n\033e_msgindex_c2s_unlock_sk"
    "ill\020\362S\022\036\n\031e_msgindex_c2s_item_forge\020\363S\022\""
    "\n\035e_msgindex_s2c_item_forge_end\020\364S\022$\n\037e_"
    "msgindex_c2s_item_forge_begin\020\365S\022 \n\033e_ms"
    "gindex_c2s_spirit_forge\020\366S\022$\n\037e_msgindex"
    "_s2c_spirit_forge_end\020\367S\022&\n!e_msgindex_c"
    "2s_spirit_forge_begin\020\370S\022\'\n\"e_msgindex_c"
    "2s_tinder_prop_operate\020\371S\022+\n&e_msgindex_"
    "s2c_tinder_prop_operate_end\020\372S\022\'\n\"e_msgi"
    "ndex_s2c_get_meditation_item\020\373S\022\'\n\"e_msg"
    "index_s2c_composit_failed_num\020\374S\022&\n!e_ms"
    "gindex_c2s_wing_feather_skill\020\375S\022*\n%e_ms"
    "gindex_s2c_wing_feather_skill_end\020\376S\022%\n "
    "e_msgindex_c2s_goddess_operation\020\377S\022)\n$e"
    "_msgindex_s2c_goddess_operation_end\020\200T\022\037"
    "\n\032e_msgindex_c2s_item_awaken\020\201T\022#\n\036e_msg"
    "index_s2c_item_awaken_end\020\202T\022)\n$e_msgind"
    "ex_c2s_item_jewel_carve_oper\020\203T\022-\n(e_msg"
    "index_s2c_item_jewel_carve_oper_end\020\204T\022%"
    "\n e_msgindex_s2c_item_upgrade_data\020\205T\022 \n"
    "\033e_msgindex_c2s_item_upgrade\020\206T\022\036\n\031e_msg"
    "index_s2c_aoi_update\020\262T\022\"\n\035e_msgindex_s2"
    "c_aoi_simple_all\020\263T\022\"\n\035e_msgindex_s2c_ao"
    "i_simple_one\020\264T\022\037\n\032e_msgindex_c2s_aoi_ge"
    "t_all\020\265T\022#\n\036e_msgindex_c2s_aoi_get_all_e"
    "nd\020\266T\022\033\n\026e_msgindex_s2c_aoi_out\020\267T\022#\n\036e_"
    "msgindex_c2s_aoi_show_player\020\270T\022!\n\034e_msg"
    "index_s2c_aoi_face_unit\020\271T\022\"\n\035e_msgindex"
    "_s2c_aoi_marry_unit\020\272T\022\"\n\035e_msgindex_c2s"
    "_aoi_simple_pos\020\273T\022&\n!e_msgindex_s2c_aoi"
    "_simple_pos_end\020\274T\022 \n\033e_msgindex_c2s_aoi"
    "_location\020\275T\022 \n\033e_msgindex_c2s_aoi_rotat"
    "ion\020\276T\022 \n\033e_msgindex_s2c_aoi_rotation\020\277T"
    "\022)\n$e_msgindex_s2c_aoi_change_appearance"
    "\020\300T\022(\n#e_mgsindex_s2c_update_can_show_he"
    "ad\020\301T\022$\n\037e_msgindex_c2s_belief_operation"
    "\020\225U\022$\n\037e_msgindex_s2c_belief_operation\020\226"
    "U\022/\n*e_msgindex_s2c_belief_update_charac"
    "ter_all\020\227U\022/\n*e_msgindex_s2c_belief_upda"
    "te_character_one\020\230U\022\037\n\032e_msgindex_s2c_mi"
    "ssion_one\020\371U\022\037\n\032e_msgindex_s2c_mission_a"
    "ll\020\372U\022#\n\036e_msgindex_s2c_mission_operate\020"
    "\373U\022#\n\036e_msgindex_c2s_mission_operate\020\374U\022"
    "*\n%e_msgindex_c2s_mission_alien_kill_npc"
    "\020\375U\022\"\n\035e_msgindex_s2c_mission_finish\020\376U\022"
    "\036\n\031e_msgindex_c2s_reset_test\020\377U\022+\n&e_msg"
    "index_s2c_mission_create_npc_info\020\200V\022,\n\'"
    "e_msgindex_s2c_mission_get_monster_item\020"
    "\201V\022/\n*e_msgindex_s2c_mission_show_chapte"
    "r_finish\020\202V\022$\n\037e_msgindex_c2s_spirit_ope"
    "ration\020\335V\022!\n\034e_msgindex_s2c_spirit_updat"
    "e\020\336V\022\037\n\032e_msgindex_s2c_spirit_tidy\020\337V\022$\n"
    "\037e_msgindex_s2c_spirit_operation\020\340V\0220\n+e"
    "_msgindex_s2c_spirit_update_free_hunt_ti"
    "me\020\341V\022\'\n\"e_msgindex_s2c_spirit_qiyuan_le"
    "vel\020\342V\022%\n e_msgindex_s2c_spirit_jiban_li"
    "st\020\343V\022!\n\034e_msgindex_c2s_exchange_item\020\344V"
    "\022#\n\036e_msgindex_s2c_exchange_report\020\345V\022,\n"
    "\'e_msgindex_s2c_spirit_auto_sell_display"
    "\020\346V\022\037\n\032e_msgindex_c2s_spirit_hunt\020\347V\022#\n\036"
    "e_msgindex_s2c_spirit_hunt_end\020\350V\022&\n!e_m"
    "sgindex_s2c_spirit_fetter_info\020\351V\022)\n$e_m"
    "sgindex_c2s_spirit_fetter_upgrade\020\352V\022)\n$"
    "e_msgindex_s2c_spirit_fetter_upgrade\020\353V\022"
    "\035\n\030e_msgindex_s2c_goods_one\020\301W\022\035\n\030e_msgi"
    "ndex_s2c_goods_all\020\302W\022!\n\034e_msgindex_s2c_"
    "goods_operate\020\303W\022!\n\034e_msgindex_c2s_goods"
    "_operate\020\304W\022 \n\033e_msgindex_s2c_update_sto"
    "re\020\305W\022 \n\033e_msgindex_c2s_update_store\020\306W\022"
    "$\n\037e_msgindex_s2c_server_open_time\020\307W\022%\n"
    " e_msgindex_s2c_element_heart_one\020\245X\022%\n "
    "e_msgindex_s2c_element_heart_all\020\246X\022)\n$e"
    "_msgindex_s2c_element_heart_operate\020\247X\022)"
    "\n$e_msgindex_c2s_element_heart_operate\020\250"
    "X\022(\n#e_msgindex_s2c_element_heart_delete"
    "\020\251X\022&\n!e_msgindex_s2c_element_heart_tidy"
    "\020\252X\022(\n#e_msgindex_s2c_special_name_opera"
    "te\020\211Y\022(\n#e_msgindex_c2s_special_name_ope"
    "rate\020\212Y\022(\n#e_msgindex_s2c_special_name_g"
    "et_all\020\213Y\022(\n#e_msgindex_c2s_special_name"
    "_get_all\020\214Y\022#\n\036e_msgindex_c2s_pokedex_op"
    "erate\020\355Y\022\'\n\"e_msgindex_s2c_pokedex_opera"
    "te_end\020\356Y\0220\n+e_msgindex_s2c_pokedex_upda"
    "te_character_all\020\357Y\0220\n+e_msgindex_s2c_po"
    "kedex_update_character_one\020\360Y\0220\n+e_msgin"
    "dex_s2c_protect_spirit_operation_end\020\362Y\022"
    "#\n\036e_msgindex_s2c_tinder_info_all\020\364Y\022\"\n\035"
    "e_msgindex_c2s_tinder_operate\020\365Y\022)\n$e_ms"
    "gindex_s2c_patron_saint_operated\020\366Y\022-\n(e"
    "_msgindex_c2s_psyche_recovery_operation\020"
    "\367Y\0221\n,e_msgindex_s2c_psyche_recovery_ope"
    "ration_end\020\370Y\022#\n\036e_msgindex_s2c_tinder_i"
    "nfo_one\020\371Y\022&\n!e_msgindex_s2c_tinder_oper"
    "ate_end\020\372Y\022#\n\036e_msgindex_s2c_achievement"
    "_one\020\321Z\022#\n\036e_msgindex_s2c_achievement_al"
    "l\020\322Z\022\'\n\"e_msgindex_s2c_achievement_opera"
    "te\020\323Z\022\'\n\"e_msgindex_c2s_achievement_oper"
    "ate\020\324Z\022&\n!e_msgindex_c2s_achievement_fin"
    "ish\020\325Z\022\037\n\032e_msgindex_s2c_phantom_one\020\356Z\022"
    "\037\n\032e_msgindex_s2c_phantom_all\020\357Z\022#\n\036e_ms"
    "gindex_c2s_phantom_operate\020\360Z\022\'\n\"e_msgin"
    "dex_s2c_phantom_operate_end\020\362Z\022#\n\036e_msgi"
    "ndex_s2c_chat_record_one\020\370Z\022#\n\036e_msginde"
    "x_s2c_chat_record_all\020\371Z\022$\n\037e_msgindex_c"
    "2s_chat_record_oper\020\372Z\022#\n\036e_msgindex_s2c"
    "_chat_record_end\020\373Z\022-\n(e_msgindex_s2c_re"
    "cycle_invited_level_one\020\201[\022$\n\037e_msgindex"
    "_s2c_recycle_data_all\020\202[\022%\n e_msgindex_s"
    "2c_recycle_login_one\020\203[\022 \n\033e_msgindex_c2"
    "s_recycle_oper\020\204[\022$\n\037e_msgindex_s2c_recy"
    "cle_oper_end\020\205[\022$\n\037e_msgindex_s2c_recycl"
    "e_item_one\020\206[\022#\n\036e_msgindex_s2c_recycle_"
    "buy_one\020\207[\022\'\n\"e_msgindex_s2c_recycle_inv"
    "ited_all\020\210[\022\'\n\"e_msgindex_s2c_recycle_in"
    "vited_one\020\211[\022*\n%e_msgindex_c2s_recycle_i"
    "nvited_reward\020\212[\022.\n)e_msgindex_s2c_recyc"
    "le_invited_reward_end\020\213[\022\033\n\026e_msgindex_s"
    "2c_buy_tip\020\214[\022(\n#e_msgindex_s2c_boss_res"
    "ult_rank_end\020\215[\022\"\n\035e_mgsindex_s2c_dragon"
    "trip_all\020\221[\022&\n!e_msgindex_c2s_dragontrip"
    "_operate\020\222[\022*\n%e_msgindex_s2c_dragontrip"
    "_operate_end\020\223[\022&\n!e_msgindex_c2s_mountp"
    "ower_operate\020\224[\022*\n%e_msgindex_s2c_mountp"
    "ower_operate_end\020\225[\022+\n&e_msgindex_s2c_up"
    "date_team_member_info\020\265[\022$\n\037e_msgindex_s"
    "2c_update_team_info\020\266[\022\037\n\032e_msgindex_c2s"
    "_create_team\020\267[\022#\n\036e_msgindex_s2c_create"
    "_team_end\020\270[\022\035\n\030e_msgindex_c2s_join_team"
    "\020\271[\022&\n!e_msgindex_c2s_apply_to_join_team"
    "\020\272[\022\'\n\"e_msgindex_s2c_join_team_apply_en"
    "d\020\273[\022,\n\'e_msgindex_s2c_join_team_applica"
    "nt_info\020\274[\022&\n!e_msgindex_c2s_let_role_jo"
    "in_team\020\275[\022#\n\036e_msgindex_s2c_add_team_me"
    "mber\020\276[\022#\n\036e_msgindex_s2c_del_team_membe"
    "r\020\277[\022\036\n\031e_msgindex_c2s_leave_team\020\300[\022\"\n\035"
    "e_msgindex_s2c_leave_team_end\020\301[\022\031\n\024e_ms"
    "gindex_c2s_ready\020\302[\022\035\n\030e_msgindex_s2c_re"
    "ady_end\020\303[\022\'\n\"e_msgindex_c2s_kickout_tea"
    "m_member\020\304[\022+\n&e_msgindex_s2c_kickout_te"
    "am_member_end\020\305[\022)\n$e_msgindex_c2s_searc"
    "h_team_by_map_id\020\306[\022-\n(e_msgindex_s2c_se"
    "arch_team_by_map_id_end\020\307[\022*\n%e_msgindex"
    "_c2s_ready_to_transfer_team\020\310[\022.\n)e_msgi"
    "ndex_s2c_ready_to_transfer_team_end\020\311[\022*"
    "\n%e_msgindex_c2s_transfer_team_to_scene\020"
    "\312[\022!\n\034e_msgindex_c2s_invite_player\020\313[\022)\n"
    "$e_msgindex_s2c_invite_player_success\020\314["
    "\022%\n e_msgindex_s2c_invite_player_end\020\315[\022"
    "\037\n\032e_msgindex_c2s_set_captain\020\316[\022#\n\036e_ms"
    "gindex_s2c_set_captain_end\020\317[\022,\n\'e_msgin"
    "dex_s2c_set_player_team_aoi_info\020\320[\022.\n)e"
    "_msgindex_s2c_clear_player_team_aoi_info"
    "\020\321[\022/\n*e_msgindex_s2c_update_team_member"
    "_info_one\020\322[\022\036\n\031e_msgindex_s2c_team_erro"
    "r\020\323[\022(\n#e_msgindex_s2c_team_member_pos_i"
    "nfo\020\324[\022!\n\034e_msgindex_s2c_team_pos_info\020\325"
    "[\022/\n*e_msgindex_c2s_get_no_team_legionma"
    "te_list\020\326[\0223\n.e_msgindex_s2c_get_no_team"
    "_legionmate_list_end\020\327[\022%\n e_msgindex_c2"
    "s_get_aim_team_list\020\330[\022)\n$e_msgindex_s2c"
    "_get_aim_team_list_end\020\331[\022#\n\036e_msgindex_"
    "c2s_auto_match_team\020\332[\022\'\n\"e_msgindex_s2c"
    "_auto_match_team_end\020\333[\022)\n$e_msgindex_c2"
    "s_update_team_attribute\020\334[\022-\n(e_msgindex"
    "_s2c_update_team_attribute_end\020\335[\022+\n&e_m"
    "sgindex_c2s_update_team_mem_operate\020\336[\022/"
    "\n*e_msgindex_s2c_update_team_mem_operate"
    "_end\020\337[\022*\n%e_msgindex_s2c_notice_create_"
    "new_team\020\340[\022(\n#e_msgindex_s2c_self_os_fl"
    "ags_update\020\341[\022%\n e_msgindex_c2s_refused_"
    "join_team\020\342[\022)\n$e_msgindex_s2c_refused_j"
    "oin_team_end\020\343[\022(\n#e_msgindex_s2c_update"
    "_team_gs_value\020\344[\022\"\n\035e_msgindex_c2s_mail"
    "_operation\020\231\\\022\037\n\032e_msgindex_s2c_mail_upd"
    "ate\020\232\\\022\035\n\030e_msgindex_c2s_mail_sort\020\233\\\022\"\n"
    "\035e_msgindex_s2c_mail_operation\020\234\\\022&\n!e_m"
    "sgindex_s2c_mail_operation_end\020\235\\\022\"\n\035e_m"
    "sgindex_c2s_mail_send_mail\020\236\\\022%\n e_msgin"
    "dex_s2c_mail_contents_get\020\237\\\0221\n,e_msgind"
    "ex_s2c_mail_delete_mail_by_live_time\020\240\\\022"
    "+\n&e_msgindex_s2c_mail_send_to_all_playe"
    "r\020\241\\\022$\n\037e_msgindex_s2c_mail_item_update\020"
    "\242\\\022*\n%e_msgindex_s2c_mail_delete_these_m"
    "ail\020\243\\\022\034\n\027e_msgindex_c2s_get_rank\020\375\\\022 \n\033"
    "e_msgindex_s2c_get_rank_end\020\376\\\022$\n\037e_msgi"
    "ndex_c2s_get_match_player\020\377\\\022(\n#e_msgind"
    "ex_s2c_get_match_player_end\020\200]\022(\n#e_msgi"
    "ndex_c2s_get_top_three_player\020\201]\022,\n\'e_ms"
    "gindex_s2c_get_top_three_player_end\020\202]\022!"
    "\n\034e_msgindex_c2s_req_challenge\020\203]\022%\n e_m"
    "sgindex_s2c_req_challenge_end\020\204]\022\"\n\035e_ms"
    "gindex_c2s_challenge_over\020\205]\022)\n$e_msgind"
    "ex_c2s_req_get_challenge_log\020\206]\022-\n(e_msg"
    "index_s2c_req_get_challenge_log_end\020\207]\022$"
    "\n\037e_msgindex_c2s_get_arena_reward\020\210]\022(\n#"
    "e_msgindex_s2c_get_arena_reward_end\020\211]\022,"
    "\n\'e_msgindex_c2s_req_mopping_remain_time"
    "s\020\212]\0220\n+e_msgindex_s2c_req_mopping_remai"
    "n_times_end\020\213]\022#\n\036e_msgindex_c2s_ranking"
    "_get_top\020\341]\022\'\n\"e_msgindex_s2c_ranking_ge"
    "t_top_end\020\342]\022#\n\036e_msgindex_c2s_ranking_w"
    "orship\020\343]\022\'\n\"e_msgindex_s2c_ranking_wors"
    "hip_end\020\344]\022\'\n\"e_msgindex_c2s_ranking_get"
    "_my_rank\020\345]\022+\n&e_msgindex_s2c_ranking_ge"
    "t_my_rank_end\020\346]\022.\n)e_msgindex_s2c_ranki"
    "ng_worship_record_one\020\347]\022*\n%e_msgindex_s"
    "2c_ranking_worship_record\020\350]\022*\n%e_msgind"
    "ex_s2c_ranking_operate_result\020\351]\022,\n\'e_ms"
    "gindex_c2s_get_player_ranking_value\020\352]\0220"
    "\n+e_msgindex_s2c_get_player_ranking_valu"
    "e_end\020\353]\022)\n$e_msgindex_s2c_service_rank_"
    "info_one\020\354]\022)\n$e_msgindex_s2c_service_ra"
    "nk_info_all\020\355]\0220\n+e_msgindex_c2s_service"
    "_rank_recevice_reward\020\356]\0221\n,e_msgindex_s"
    "2c_service_rank_reward_state_one\020\357]\0221\n,e"
    "_msgindex_s2c_service_rank_reward_state_"
    "all\020\360]\0221\n,e_msgindex_c2s_service_rank_ge"
    "t_first_player\020\361]\0225\n0e_msgindex_s2c_serv"
    "ice_rank_get_first_player_end\020\362]\022+\n&e_ms"
    "gindex_c2s_ranking_get_my_rank_lua\020\363]\022+\n"
    "&e_msgindex_s2c_ranking_get_top_end_lua\020"
    "\364]\022/\n*e_msgindex_c2s_get_city_war_territ"
    "ory_info\020\223^\0223\n.e_msgindex_s2c_get_city_w"
    "ar_territory_info_end\020\224^\022*\n%e_msgindex_c"
    "2s_get_city_war_rank_info\020\225^\022.\n)e_msgind"
    "ex_s2c_get_city_war_rank_info_end\020\226^\0220\n+"
    "e_msgindex_c2s_set_territory_prior_maint"
    "ain\020\227^\0224\n/e_msgindex_s2c_set_territory_p"
    "rior_maintain_end\020\230^\0220\n+e_msgindex_c2s_i"
    "nvite_player_to_join_legion\020\231^\0224\n/e_msgi"
    "ndex_s2c_invite_player_to_join_legion_en"
    "d\020\232^\022(\n#e_msgindex_c2s_draw_mem_daily_aw"
    "ard\020\233^\022,\n\'e_msgindex_c2s_draw_bonfire_da"
    "ily_award\020\234^\022)\n$e_msgindex_c2s_level_up_"
    "legion_skill\020\235^\022-\n(e_msgindex_s2c_level_"
    "up_legion_skill_end\020\236^\022)\n$e_msgindex_s2c"
    "_invite_player_succeed\020\237^\022)\n$e_msgindex_"
    "s2c_members_info_list_end\020\240^\022.\n)e_msgind"
    "ex_s2c_get_legion_skill_level_end\020\241^\0223\n."
    "e_msgindex_c2s_get_legion_answer_questio"
    "n_info\020\242^\0227\n2e_msgindex_s2c_get_legion_a"
    "nswer_question_info_end\020\243^\022(\n#e_msgindex"
    "_s2c_legion_answer_result\020\244^\0222\n-e_msgind"
    "ex_c2s_get_legion_warehouse_item_info\020\245^"
    "\0226\n1e_msgindex_s2c_get_legion_warehouse_"
    "item_info_end\020\246^\0223\n.e_msgindex_c2s_opera"
    "tion_legion_warehouse_item\020\247^\0227\n2e_msgin"
    "dex_s2c_operation_legion_warehouse_item_"
    "end\020\250^\022,\n\'e_msgindex_c2s_get_legion_ware"
    "house_log\020\251^\0220\n+e_msgindex_s2c_get_legio"
    "n_warehouse_log_end\020\252^\022&\n!e_msgindex_c2s"
    "_change_legion_name\020\253^\022*\n%e_msgindex_s2c"
    "_change_legion_name_end\020\254^\022.\n)e_msgindex"
    "_c2s_confirm_change_legion_name\020\255^\022\'\n\"e_"
    "msgindex_s2c_cross_city_info_all\020\256^\0220\n+e"
    "_msgindex_c2s_join_cross_overload_city_w"
    "ar\020\257^\0220\n+e_msgindex_s2c_send_legion_answ"
    "er_rank_list\020\260^\022/\n*e_msgindex_c2s_get_le"
    "gion_answer_rank_list\020\261^\022%\n e_msgindex_s"
    "2c_legion_answer_end\020\262^\0221\n,e_mgsindex_s2"
    "c_send_legion_answer_box_reward\020\263^\0222\n-e_"
    "msgindex_s2c_city_war_members_info_list_"
    "end\020\264^\0228\n3e_msgindex_s2c_legion_welfare_"
    "members_info_list_end\020\265^\022-\n(e_msgindex_s"
    "2c_update_legion_member_info\020\305^\022&\n!e_msg"
    "index_s2c_update_legion_info\020\306^\022,\n\'e_msg"
    "index_s2c_update_legion_brief_info\020\307^\022!\n"
    "\034e_msgindex_c2s_create_legion\020\310^\022%\n e_ms"
    "gindex_s2c_create_legion_end\020\311^\022*\n%e_msg"
    "index_s2c_update_legion_info_all\020\312^\022*\n%e"
    "_msgindex_s2c_update_legion_info_one\020\313^\022"
    "1\n,e_msgindex_s2c_update_legion_member_i"
    "nfo_all\020\314^\0221\n,e_msgindex_s2c_update_legi"
    "on_member_info_one\020\315^\022#\n\036e_msgindex_c2s_"
    "dissolve_legion\020\316^\022\'\n\"e_msgindex_s2c_dis"
    "solve_legion_end\020\317^\022 \n\033e_msgindex_c2s_le"
    "ave_legion\020\320^\022$\n\037e_msgindex_s2c_leave_le"
    "gion_end\020\321^\022#\n\036e_msgindex_c2s_get_legion"
    "_list\020\322^\022\'\n\"e_msgindex_s2c_get_legion_li"
    "st_end\020\323^\022(\n#e_msgindex_c2s_apply_to_joi"
    "n_legion\020\324^\022,\n\'e_msgindex_s2c_apply_to_j"
    "oin_legion_end\020\325^\0220\n+e_msgindex_s2c_upda"
    "te_legion_applicant_info\020\326^\0222\n-e_msginde"
    "x_c2s_get_legion_applicant_info_list\020\327^\022"
    "6\n1e_msgindex_s2c_get_legion_applicant_i"
    "nfo_list_end\020\330^\022(\n#e_msgindex_c2s_proces"
    "s_legion_apply\020\331^\022,\n\'e_msgindex_s2c_proc"
    "ess_legion_apply_end\020\332^\022*\n%e_msgindex_c2"
    "s_convenient_join_legion\020\333^\022.\n)e_msginde"
    "x_s2c_convenient_join_legion_end\020\334^\022)\n$e"
    "_msgindex_s2c_add_legion_member_end\020\336^\022%"
    "\n e_msgindex_c2s_del_legion_member\020\337^\022)\n"
    "$e_msgindex_s2c_del_legion_member_end\020\340^"
    "\0220\n+e_msgindex_c2s_legion_construction_l"
    "evel_up\020\341^\0224\n/e_msgindex_s2c_legion_cons"
    "truction_level_up_end\020\342^\0220\n+e_msgindex_c"
    "2s_legion_get_construction_buff\020\343^\0224\n/e_"
    "msgindex_s2c_legion_get_construction_buf"
    "f_end\020\344^\022\'\n\"e_msgindex_c2s_legion_donate"
    "_money\020\345^\022&\n!e_msgindex_c2s_legion_donat"
    "e_item\020\346^\022%\n e_msgindex_s2c_legion_donat"
    "e_end\020\347^\022.\n)e_msgindex_c2s_update_legion"
    "_announcement\020\350^\0222\n-e_msgindex_s2c_updat"
    "e_legion_announcement_end\020\351^\022)\n$e_msgind"
    "ex_c2s_get_legion_event_list\020\352^\022-\n(e_msg"
    "index_s2c_get_legion_event_list_end\020\353^\022)"
    "\n$e_msgindex_c2s_kickout_legion_member\020\354"
    "^\022-\n(e_msgindex_s2c_kickout_legion_membe"
    "r_end\020\355^\0223\n.e_msgindex_c2s_appoint_legio"
    "n_member_job_title\020\356^\0227\n2e_msgindex_s2c_"
    "appoint_legion_member_job_title_end\020\357^\022)"
    "\n$e_msgindex_c2s_enter_legion_boss_map\020\360"
    "^\022$\n\037e_msgindex_s2c_kill_legion_boss\020\361^\022"
    "&\n!e_msgindex_s2c_legion_boss_record\020\362^\022"
    "+\n&e_msgindex_s2c_legion_boss_record_lis"
    "t\020\363^\022)\n$e_msgindex_c2s_get_legion_boss_a"
    "ward\020\364^\022-\n(e_msgindex_s2c_get_legion_bos"
    "s_award_end\020\365^\022$\n\037e_msgindex_c2s_get_ban"
    "quet_info\020\366^\022(\n#e_msgindex_s2c_get_banqu"
    "et_info_end\020\367^\022(\n#e_msgindex_c2s_request"
    "_hold_banquet\020\370^\022,\n\'e_msgindex_s2c_reque"
    "st_hold_banquet_end\020\371^\022(\n#e_msgindex_c2s"
    "_take_part_in_banquet\020\372^\022,\n\'e_msgindex_s"
    "2c_take_part_in_banquet_end\020\373^\022%\n e_msgi"
    "ndex_c2s_get_city_war_info\020\374^\022)\n$e_msgin"
    "dex_s2c_get_city_war_info_end\020\375^\022&\n!e_ms"
    "gindex_c2s_apply_city_war_bid\020\376^\022*\n%e_ms"
    "gindex_s2c_apply_city_war_bid_end\020\377^\022&\n!"
    "e_msgindex_c2s_entry_city_war_map\020\200_\022$\n\037"
    "e_msgindex_c2s_city_war_operate\020\201_\022(\n#e_"
    "msgindex_s2c_city_war_operate_end\020\202_\022&\n!"
    "e_msgindex_s2c_city_war_raid_info\020\203_\022.\n)"
    "e_msgindex_s2c_city_war_update_role_scor"
    "e\020\204_\022!\n\034e_msgindex_s2c_city_war_over\020\205_\022"
    "6\n1e_msgindex_c2s_set_auto_accept_new_me"
    "mber_setting\020\206_\022.\n)e_msgindex_s2c_set_pl"
    "ayer_legion_aoi_info\020\207_\0220\n+e_msgindex_s2"
    "c_clear_player_legion_aoi_info\020\210_\0228\n3e_m"
    "sgindex_s2c_set_player_legion_boss_award"
    "_get_log\020\211_\022(\n#e_msgindex_c2s_get_city_m"
    "aster_info\020\212_\022,\n\'e_msgindex_s2c_get_city"
    "_master_info_end\020\213_\022.\n)e_msgindex_c2s_ge"
    "t_occupation_daily_award\020\214_\0222\n-e_msginde"
    "x_s2c_get_occupation_daily_award_end\020\215_\022"
    "#\n\036e_msgindex_c2s_get_legion_rank\020\216_\022\'\n\""
    "e_msgindex_s2c_get_legion_rank_end\020\217_\022 \n"
    "\033e_msgindex_s2c_legion_error\020\220_\022\"\n\035e_msg"
    "index_c2s_create_bonfire\020\221_\022 \n\033e_msginde"
    "x_s2c_bonfire_info\020\222_\022\'\n\"e_msgindex_c2s_"
    "add_fuel_to_bonfire\020\223_\022(\n#e_msgindex_s2c"
    "_member_add_fuel_info\020\224_\022+\n&e_msgindex_c"
    "2s_legion_recruit_in_world\020\225_\022/\n*e_msgin"
    "dex_s2c_legion_recruit_in_world_end\020\226_\022\'"
    "\n\"e_msgindex_c2s_legion_call_operate\020\227_\022"
    "+\n&e_msgindex_s2c_legion_call_operate_en"
    "d\020\230_\022 \n\033e_msgindex_s2c_bonfire_dead\020\231_\022$"
    "\n\037e_msgindex_s2c_suck_blood_value\020\232_\0221\n,"
    "e_msgindex_s2c_update_legion_auction_sel"
    "ling\020\233_\0221\n,e_msgindex_c2s_legion_territo"
    "ry_buff_operate\020\234_\022+\n&e_msgindex_s2c_leg"
    "ion_bonfire_map_info\020\235_\0222\n-e_msgindex_c2"
    "s_goto_next_stage_of_bonfire_map\020\236_\022+\n&e"
    "_msgindex_c2s_transfer_to_bonfire_map\020\237_"
    "\022*\n%e_msgindex_s2c_entry_city_war_map_en"
    "d\020\240_\0225\n0e_msgindex_s2c_notice_new_item_i"
    "n_legion_auction\020\241_\022%\n e_msgindex_c2s_ge"
    "t_bonus_rewards\020\242_\022)\n$e_msgindex_s2c_get"
    "_bonus_rewards_end\020\243_\022%\n e_msgindex_s2c_"
    "legion_bonus_info\020\244_\022)\n$e_msgindex_s2c_l"
    "egion_bonus_info_one\020\245_\022\'\n\"e_msgindex_s2"
    "c_abstention_city_msg\020\246_\022\'\n\"e_msgindex_c"
    "2s_stimulate_bonus_msg\020\247_\022*\n%e_msgindex_"
    "s2c_update_legion_gs_value\020\250_\022\'\n\"e_msgin"
    "dex_c2s_send_globel_message\020\251_\022%\n e_msgi"
    "ndex_c2s_send_chat_message\020\252_\0224\n/e_msgin"
    "dex_c2s_send_chat_message_with_item_info"
    "\020\253_\022*\n%e_msgindex_s2c_receive_globel_mes"
    "sage\020\254_\022(\n#e_msgindex_s2c_receive_chat_m"
    "essage\020\255_\0227\n2e_msgindex_s2c_receive_chat"
    "_message_with_item_info\020\256_\022\037\n\032e_msgindex"
    "_c2s_send_notice\020\257_\022\"\n\035e_msgindex_s2c_re"
    "ceive_notice\020\260_\022\035\n\030e_msgindex_c2s_send_c"
    "hat\020\261_\022 \n\033e_msgindex_s2c_receive_chat\020\262_"
    "\022$\n\037e_msgindex_s2c_send_chat_result\020\263_\022)"
    "\n$e_msgindex_c2s_send_chat_message_new\020\264"
    "_\022$\n\037e_msgindex_s2c_receive_chat_new\020\265_\022"
    "(\n#e_msgindex_c2s_send_recruit_message\020\266"
    "_\022+\n&e_msgindex_s2c_receive_recruit_mess"
    "age\020\267_\022-\n(e_msgindex_s2c_update_recruit_"
    "member_num\020\270_\022\'\n\"e_msgindex_s2c_send_rec"
    "ruit_result\020\271_\022*\n%e_msgindex_s2c_reveive"
    "_legion_recruit\020\272_\022\036\n\031e_msgindex_c2s_sen"
    "d_audio\020\273_\022!\n\034e_msgindex_s2c_receive_aud"
    "io\020\274_\022#\n\036e_msgindex_c2s_send_quick_chat\020"
    "\275_\022&\n!e_msgindex_s2c_receive_quick_chat\020"
    "\276_\022*\n%e_msgindex_c2s_send_notice_with_pa"
    "ram\020\277_\022-\n(e_msgindex_s2c_receive_notice_"
    "with_param\020\300_\022#\n\036e_msgindex_s2c_receive_"
    "top_tip\020\301_\022&\n!e_msgindex_c2s_join_voice_"
    "channel\020\302_\022*\n%e_msgindex_s2c_join_voice_"
    "channel_end\020\303_\022-\n(e_msgindex_s2c_invite_"
    "join_voice_channel\020\304_\0226\n1e_msgindex_s2c_"
    "join_or_leave_voice_channel_notice\020\305_\0223\n"
    ".e_msgindex_s2c_update_three_day_must_do"
    "_remain\020\215`\022.\n)e_msgindex_c2s_find_back_m"
    "ust_do_resource\020\216`\0222\n-e_msgindex_s2c_fin"
    "d_back_must_do_resource_end\020\217`\0222\n-e_msgi"
    "ndex_s2c_update_daily_must_do_count_one\020"
    "\220`\0222\n-e_msgindex_s2c_update_daily_must_d"
    "o_count_all\020\221`\022&\n!e_msgindex_s2c_convert"
    "_update_one\020\361`\022&\n!e_msgindex_s2c_convert"
    "_update_all\020\362`\022$\n\037e_msgindex_c2s_convert"
    "_opereate\020\363`\022\'\n\"e_msgindex_s2c_convert_o"
    "perate_end\020\364`\022 \n\033e_msgindex_c2s_get_vip_"
    "item\020\325a\022$\n\037e_msgindex_s2c_get_vip_item_e"
    "nd\020\326a\022\034\n\027e_msgindex_c2s_recharge\020\327a\022 \n\033e"
    "_msgindex_s2c_recharge_end\020\330a\022(\n#e_msgin"
    "dex_c2s_recharge_widget_type\020\331a\022%\n e_msg"
    "index_s2c_dead_recharge_end\020\332a\022#\n\036e_msgi"
    "ndex_s2c_talent_info_all\020\207b\022#\n\036e_msginde"
    "x_s2c_talent_info_one\020\210b\022#\n\036e_msgindex_c"
    "2s_talent_level_up\020\211b\022\'\n\"e_msgindex_s2c_"
    "talent_level_up_end\020\212b\022 \n\033e_msgindex_c2s"
    "_talent_reset\020\213b\022)\n$e_msgindex_s2c_send_"
    "welfare_info_one\020\271b\022)\n$e_msgindex_s2c_se"
    "nd_welfare_info_all\020\272b\022+\n&e_msgindex_s2c"
    "_send_active_degree_info\020\273b\022\037\n\032e_msginde"
    "x_c2s_get_welfare\020\274b\022#\n\036e_msgindex_s2c_g"
    "et_welfare_end\020\275b\022,\n\'e_msgindex_c2s_get_"
    "welfare_activatecode\020\276b\022(\n#e_msgindex_s2"
    "c_send_random_get_info\020\277b\022(\n#e_msgindex_"
    "s2c_active_degree_finish\020\300b\022\'\n\"e_msginde"
    "x_c2s_get_reward_check_in\020\301b\0223\n.e_msgind"
    "ex_c2s_req_frist_kill_world_boss_prize\020\302"
    "b\022+\n&e_msgindex_c2s_get_first_recharge_t"
    "ime\020\303b\022/\n*e_msgindex_s2c_get_first_recha"
    "rge_time_end\020\304b\022\"\n\035e_msgindex_s2c_cross_"
    "transfer\020\235c\022\"\n\035e_msgindex_c2s_cross_tran"
    "sfer\020\236c\022$\n\037e_msgindex_c2s_cross_cross_in"
    "fo\020\237c\022$\n\037e_msgindex_s2c_cross_cross_info"
    "\020\240c\022!\n\034e_msgindex_c2s_cross_sign_up\020\241c\022!"
    "\n\034e_msgindex_s2c_cross_sign_up\020\242c\022#\n\036e_m"
    "sgindex_s2c_cross_begin_war\020\243c\022\"\n\035e_msgi"
    "ndex_c2s_cross_join_war\020\244c\022\"\n\035e_msgindex"
    "_s2c_cross_join_war\020\245c\022$\n\037e_msgindex_s2c"
    "_cross_war_result\020\246c\022!\n\034e_msgindex_c2s_c"
    "ross_war_log\020\247c\022!\n\034e_msgindex_s2c_cross_"
    "war_log\020\250c\022$\n\037e_msgindex_s2c_cross_game_"
    "state\020\251c\022\030\n\023e_msgindex_s2c_move\020\200d\022\034\n\027e_"
    "msgindex_s2c_rotation\020\201d\022%\n e_msgindex_s"
    "2c_update_world_boss\020\345d\022\'\n\"e_msgindex_c2"
    "s_get_world_boss_rank\020\346d\022\035\n\030e_msgindex_s"
    "2c_kill_boss\020\347d\022\035\n\030e_msgindex_c2s_kill_b"
    "oss\020\350d\022#\n\036e_msgindex_c2s_get_growup_fund"
    "\020\311e\022\'\n\"e_msgindex_s2c_get_growup_fund_en"
    "d\020\312e\022(\n#e_msgindex_c2s_purchase_growup_f"
    "und\020\313e\022,\n\'e_msgindex_s2c_purchase_growup"
    "_fund_end\020\314e\022\'\n\"e_msgindex_c2s_title_equ"
    "ip_operate\020\221g\022(\n#e_msgindex_s2c_title_ti"
    "tle_info_one\020\222g\022\'\n\"e_msgindex_s2c_title_"
    "title_msg_one\020\223g\022+\n&e_msgindex_s2c_title"
    "_own_title_msg_all\020\224g\022\'\n\"e_msgindex_s2c_"
    "title_add_title_end\020\225g\022/\n*e_msgindex_s2c"
    "_title_open_title_system_end\020\226g\022/\n*e_msg"
    "index_c2s_title_set_title_no_need_see\020\227g"
    "\0221\n,e_msgindex_s2c_update_big_player_sta"
    "tue_guid\020\365g\022\033\n\026e_msgindex_c2s_worship\020\366g"
    "\022\037\n\032e_msgindex_s2c_worship_end\020\367g\022$\n\037e_m"
    "sgindex_c2s_send_red_package\020\331h\022(\n#e_msg"
    "index_s2c_send_red_package_end\020\332h\022)\n$e_m"
    "sgindex_s2c_load_role_ws_info_end\020\333h\022+\n&"
    "e_msgindex_s2c_update_role_ws_info_one\020\334"
    "h\022#\n\036e_msgindex_c2s_get_red_package\020\335h\022\'"
    "\n\"e_msgindex_s2c_get_red_package_end\020\336h\022"
    "\'\n\"e_msgindex_s2c_update_red_bag_info\020\337h"
    "\022$\n\037e_msgindex_s2c_del_red_bag_info\020\340h\022("
    "\n#e_msgindex_s2c_update_new_draw_info\020\341h"
    "\022#\n\036e_msgindex_s2c_first_do_record\020\275i\0220\n"
    "+e_msgindex_s2c_update_first_time_do_rec"
    "ords\020\276i\022,\n\'e_msgindex_c2s_add_first_time"
    "_do_record\020\277i\022-\n(e_msgindex_s2c_sync_fir"
    "st_time_do_record\020\300i\022\'\n\"e_msgindex_c2s_r"
    "eq_friend_userinfo\020\241j\022\'\n\"e_msgindex_s2c_"
    "ret_friend_userinfo\020\242j\022\035\n\030e_msgindex_c2s"
    "_addfriend\020\243j\022\035\n\030e_msgindex_s2c_addfrien"
    "d\020\244j\022\"\n\035e_msgindex_s2c_otheraddfriend\020\245j"
    "\022\035\n\030e_msgindex_c2s_delfriend\020\246j\022\035\n\030e_msg"
    "index_s2c_delfriend\020\247j\022(\n#e_msgindex_s2c"
    "_syc_full_friend_list\020\250j\022 \n\033e_msgindex_c"
    "2s_addblacklist\020\251j\022 \n\033e_msgindex_s2c_add"
    "blacklist\020\252j\022 \n\033e_msgindex_c2s_delblackl"
    "ist\020\253j\022 \n\033e_msgindex_s2c_delblacklist\020\254j"
    "\022\'\n\"e_msgindex_s2c_syc_full_black_list\020\255"
    "j\022!\n\034e_msgindex_s2c_syn_loverinfo\020\256j\022\037\n\032"
    "e_msgindex_c2s_req_marrage\020\257j\022\037\n\032e_msgin"
    "dex_s2c_ret_marrage\020\260j\022\037\n\032e_msgindex_c2s"
    "_addhatelist\020\261j\022\037\n\032e_msgindex_s2c_addhat"
    "elist\020\262j\022\037\n\032e_msgindex_c2s_delhatelist\020\263"
    "j\022\037\n\032e_msgindex_s2c_delhatelist\020\264j\022&\n!e_"
    "msgindex_s2c_syc_full_hate_list\020\265j\022+\n&e_"
    "msgindex_s2c_syc_full_other_req_list\020\266j\022"
    "$\n\037e_msgindex_s2c_syc_friend_state\020\267j\022*\n"
    "%e_msgindex_c2s_add_friendliness_value\020\270"
    "j\022*\n%e_msgindex_s2c_ret_friendliness_val"
    "ue\020\271j\022*\n%e_msgindex_c2s_req_syc_relation"
    "_state\020\272j\022&\n!e_msgindex_s2c_ret_relation"
    "_state\020\273j\022(\n#e_msgindex_c2s_req_syc_near"
    "ly_state\020\274j\022(\n#e_msgindex_s2c_ret_syc_ne"
    "arly_state\020\275j\022/\n*e_msgindex_s2c_ret_oper"
    "ate_relation_result\020\276j\022)\n$e_msgindex_c2s"
    "_operate_other_add_req\020\277j\022(\n#e_msgindex_"
    "s2c_marry_operate_result\020\300j\022&\n!e_msginde"
    "x_c2s_reply_marry_choice\020\301j\022#\n\036e_msginde"
    "x_c2s_req_couple_info\020\302j\022#\n\036e_msgindex_s"
    "2c_ret_couple_info\020\303j\022\037\n\032e_msgindex_c2s_"
    "req_divorce\020\304j\022(\n#e_msgindex_c2s_req_mar"
    "ry_get_reward\020\305j\022,\n\'e_msgindex_s2c_send_"
    "marry_effect_notice\020\306j\022,\n\'e_msgindex_c2s"
    "_req_upgrade_wedding_ring\020\307j\022/\n*e_msgind"
    "ex_s2c_upgrade_wedding_ring_result\020\310j\022%\n"
    " e_msgindex_s2c_update_marry_info\020\311j\022)\n$"
    "e_msgindex_c2s_req_get_marry_mission\020\312j\022"
    "1\n,e_msgindex_s2c_confirm_receive_marry_"
    "mission\020\313j\0221\n,e_msgindex_c2s_confirm_rec"
    "eive_marry_mission\020\314j\022(\n#e_msgindex_c2s_"
    "req_bless_one_couple\020\315j\022+\n&e_msgindex_s2"
    "c_bless_one_couple_result\020\316j\022)\n$e_msgind"
    "ex_c2s_get_marry_examination\020\317j\022-\n(e_msg"
    "index_s2c_confirm_marry_examination\020\320j\022-"
    "\n(e_msgindex_c2s_confirm_marry_examinati"
    "on\020\321j\022-\n(e_msgindex_c2s_operate_marry_ex"
    "amination\020\322j\022*\n%e_msgindex_s2c_sync_marr"
    "y_examination\020\323j\022-\n(e_msgindex_s2c_opera"
    "te_marry_examination\020\324j\022%\n e_msgindex_c2"
    "s_req_use_fireworks\020\325j\022\"\n\035e_msgindex_c2s"
    "_req_lucky_info\020\326j\022&\n!e_msgindex_s2c_ret"
    "_lucky_info_vec\020\327j\022*\n%e_mgsindex_s2c_ret"
    "_special_lucky_info\020\330j\022*\n%e_mgsindex_s2c"
    "_sync_marry_heart_value\020\331j\022$\n\037e_mgsindex"
    "_c2s_add_use_power_up\020\332j\022#\n\036e_msgindex_c"
    "2s_auction_operate\020\205k\022\'\n\"e_msgindex_s2c_"
    "auction_operate_end\020\206k\022!\n\034e_msgindex_c2s"
    "_auction_seach\020\207k\022\'\n\"e_msgindex_s2c_upda"
    "te_selling_info\020\210k\022)\n$e_msgindex_s2c_rec"
    "eieve_sell_success\020\211k\022$\n\037e_msgindex_c2s_"
    "req_auction_list\020\212k\022(\n#e_msgindex_s2c_re"
    "q_auction_list_end\020\213k\022$\n\037e_msgindex_c2s_"
    "req_trade_record\020\214k\022(\n#e_msgindex_s2c_re"
    "q_trade_record_end\020\215k\022)\n$e_msgindex_c2s_"
    "req_another_sell_info\020\216k\022-\n(e_msgindex_s"
    "2c_req_another_sell_info_end\020\217k\022%\n e_msg"
    "index_c2s_req_self_bid_list\020\220k\022%\n e_msgi"
    "ndex_s2c_bid_are_overtaken\020\221k\022%\n e_msgin"
    "dex_s2c_auction_sell_flag\020\222k\022-\n(e_mgsind"
    "ex_s2c_update_bid_record_failure\020\223k\022%\n e"
    "_msgindex_s2c_update_bid_notice\020\224k\022)\n$e_"
    "msgindex_s2c_update_bid_notice_red\020\225k\022$\n"
    "\037e_msgindex_s2c_service_goal_one\020\351k\022$\n\037e"
    "_msgindex_s2c_service_goal_all\020\352k\022(\n#e_m"
    "sgindex_c2s_service_goal_operate\020\353k\022,\n\'e"
    "_msgindex_s2c_service_goal_operate_end\020\354"
    "k\022&\n!e_msgindex_s2c_seven_day_goal_one\020\355"
    "k\022&\n!e_msgindex_s2c_seven_day_goal_all\020\356"
    "k\022*\n%e_msgindex_c2s_seven_day_goal_opera"
    "te\020\357k\022.\n)e_msgindex_s2c_seven_day_goal_o"
    "perate_end\020\360k\022!\n\034e_msgindex_c2s_trade_op"
    "erate\020\315l\022%\n e_msgindex_s2c_trade_operate"
    "_end\020\316l\022*\n%e_msgindex_c2s_c_s_interactio"
    "n_invite\020\261m\022*\n%e_msgindex_s2c_s_c_intera"
    "ction_invite\020\262m\0220\n+e_msgindex_c2s_c_s_in"
    "teraction_invite_reply\020\263m\0220\n+e_msgindex_"
    "s2c_s_c_interaction_invite_reply\020\264m\022.\n)e"
    "_msgindex_c2s_c_s_real_start_interaction"
    "\020\265m\022.\n)e_msgindex_s2c_s_c_real_start_int"
    "eraction\020\266m\022(\n#e_msgindex_c2s_c_s_stop_i"
    "nteraction\020\267m\022(\n#e_msgindex_s2c_s_c_stop"
    "_interaction\020\270m\022*\n%e_msgindex_s2c_intera"
    "ction_invite_end\020\271m\022,\n\'e_msgindex_c2s_in"
    "teraction_invite_start\020\272m\022\"\n\035e_msgindex_"
    "c2s_buff_operation\020\225n\022\"\n\035e_msgindex_s2c_"
    "buff_operation\020\226n\022\037\n\032e_msgindex_s2c_buff"
    "_damage\020\227n\022!\n\034e_msgindex_s2c_buff_info_a"
    "ll\020\230n\022#\n\036e_msgindex_c2s_find_other_unit\020"
    "\307n\022,\n\'e_msgindex_s2c_find_other_unit_bas"
    "e_end\020\310n\0220\n+e_msgindex_s2c_find_other_un"
    "it_equiping_one\020\311n\0220\n+e_msgindex_s2c_fin"
    "d_other_unit_equiping_end\020\312n\0222\n-e_msgind"
    "ex_s2c_find_other_unit_buff_equip_end\020\313n"
    "\0224\n/e_msgindex_s2c_find_other_unit_speci"
    "al_name_end\020\314n\0222\n-e_msgindex_s2c_find_ot"
    "her_unit_base_group_end\020\315n\022\'\n\"e_msgindex"
    "_c2s_find_other_unit_lua\020\316n\022.\n)e_msginde"
    "x_c2s_add_damage_buff_in_expraid\020\370n\0222\n-e"
    "_msgindex_s2c_add_damage_buff_in_expraid"
    "_end\020\371n\022\"\n\035e_msgindex_c2s_buy_raid_count"
    "\020\252o\022&\n!e_msgindex_s2c_buy_raid_count_end"
    "\020\253o\022\"\n\035e_msgindex_c2s_cloud_shop_req\020\335o\022"
    "#\n\036e_msgindex_s2c_cloud_shop_resp\020\336o\0220\n+"
    "e_msgindex_s2c_time_limit_activity_templ"
    "ate\020\225p\022\'\n\"e_msgindex_c2s_buy_time_limit_"
    "item\020\226p\022+\n&e_msgindex_s2c_buy_time_limit"
    "_item_end\020\227p\022(\n#e_msgindex_c2s_belief_ru"
    "ne_equip_on\020\300p\022-\n(e_msgindex_c2s_belief_"
    "rune_equip_levelup\020\301p\022/\n*e_msgindex_c2s_"
    "belief_rune_equip_decompose\020\302p\022.\n)e_msgi"
    "ndex_s2c_belief_rune_operate_result\020\303p\0220"
    "\n+e_msgindex_s2c_belief_cloister_point_u"
    "pdate\020\304p\022,\n\'e_msgindex_s2c_reply_map_tar"
    "gger_volume\020\244q\0223\n.e_msgindex_c2s_transfe"
    "r_to_cross_server_pk_map\020\210r\0220\n+e_msginde"
    "x_s2c_cross_server_pk_msg_info_one\020\211r\0220\n"
    "+e_msgindex_s2c_cross_server_pk_msg_info"
    "_all\020\212r\022$\n\037e_msgindex_s2c_cross_pk_map_m"
    "sg\020\213r\022+\n&e_msgindex_s2c_pk_map_island_st"
    "ate_msg\020\214r\022$\n\037e_msgindex_s2c_clear_pk_ms"
    "g_all\020\215r\022 \n\033e_msgindex_s2c_pk_state_end\020"
    "\216r\022\'\n\"e_msgindex_c2s_back_to_self_server"
    "\020\217r\0222\n-e_msgindex_s2c_time_limit_update_"
    "all_behavior\020\354r\0222\n-e_msgindex_s2c_time_l"
    "imit_update_one_behavior\020\355r\022.\n)e_msginde"
    "x_s2c_time_limit_update_sub_rank\020\356r\0221\n,e"
    "_msgindex_s2c_time_limit_update_sub_no_r"
    "ank\020\357r\0222\n-e_msgindex_s2c_time_limit_upda"
    "te_all_open_act\020\360r\022-\n(e_msgindex_c2s_tim"
    "e_limit_get_act_reward\020\361r\022*\n%e_msgindex_"
    "c2s_time_limit_get_my_rank\020\362r\0221\n,e_msgin"
    "dex_s2c_time_limit_update_common_data\020\363r"
    "\022.\n)e_msgindex_c2s_time_limit_get_common"
    "_data\020\364r\022+\n&e_msgindex_c2s_time_limit_ad"
    "d_schedule\020\365r\0225\n0e_msgindex_s2c_time_lim"
    "it_send_diamond_shop_info\020\370r\022/\n*e_msgind"
    "ex_c2s_time_limit_buy_diamond_shop\020\371r\0223\n"
    ".e_msgindex_s2c_time_limit_buy_diamond_s"
    "hop_end\020\372r\022+\n&e_msgindex_s2c_send_star_t"
    "rip_info_all\020\373r\0221\n,e_msgindex_s2c_send_s"
    "tar_trip_goods_info_one\020\374r\0223\n.e_msgindex"
    "_s2c_send_star_trip_mission_info_one\020\375r\022"
    "%\n e_msgindex_c2s_star_trip_operate\020\376r\022)"
    "\n$e_msgindex_s2c_star_trip_operate_end\020\377"
    "r\0223\n.e_msgindex_s2c_cross_server_harry_m"
    "sg_info_all\020\320s\0223\n.e_msgindex_s2c_cross_s"
    "erver_harry_msg_info_one\020\321s\022+\n&e_msginde"
    "x_s2c_role_harry_msg_info_one\020\322s\022+\n&e_ms"
    "gindex_s2c_role_harry_msg_info_all\020\323s\022+\n"
    "&e_msgindex_c2s_give_server_item_to_npc\020"
    "\324s\022)\n$e_msgindex_c2s_transfer_to_harry_m"
    "ap\020\325s\0222\n-e_msgindex_c2s_cross_ladder_req"
    "uest_role_info\020\264t\022/\n*e_msgindex_s2c_cros"
    "s_ladder_send_role_info\020\265t\0220\n+e_msgindex"
    "_c2s_cross_ladder_request_sign_up\020\266t\0220\n+"
    "e_msgindex_s2c_cross_ladder_respond_sign"
    "_up\020\267t\0223\n.e_msgindex_s2c_cross_ladder_se"
    "nd_match_success\020\270t\0228\n3e_msgindex_c2s_cr"
    "oss_ladder_request_buy_join_ticket\020\271t\0228\n"
    "3e_msgindex_s2c_cross_ladder_respond_buy"
    "_join_ticket\020\272t\0226\n1e_msgindex_s2c_cross_"
    "ladder_update_map_game_state\020\273t\0223\n.e_msg"
    "index_c2s_cross_ladder_req_mission_rewar"
    "d\020\274t\0223\n.e_msgindex_s2c_cross_ladder_ret_"
    "mission_reward\020\275t\0224\n/e_msgindex_s2c_cros"
    "s_ladder_send_upgrade_notify\020\276t\0226\n1e_msg"
    "index_c2s_cross_ladder_return_to_source_"
    "zone\020\277t\0229\n4e_msgindex_s2c_world_boss_map"
    "_transfer_with_gate_msg\020\374u\022;\n6e_msgindex"
    "_c2s_transfer_to_cross_server_world_boss"
    "_map\020\375u\022,\n\'e_msgindex_c2s_get_cross_boss"
    "_show_info\020\376u\022,\n\'e_msgindex_s2c_set_cros"
    "s_boss_show_info\020\377u\022.\n)e_msgindex_c2s_ge"
    "t_cross_boss_damage_list\020\200v\022/\n*e_msginde"
    "x_s2c_send_cross_boss_damage_list\020\201v\022,\n\'"
    "e_msgindex_s2c_send_boss_god_begin_time\020"
    "\202v\022%\n e_msgindex_s2c_send_boss_is_dead\020\203"
    "v\022)\n$e_msgindex_c2s_send_get_boss_is_dea"
    "d\020\204v\022&\n!e_msgindex_s2c_send_boss_god_tim"
    "e\020\205v\022%\n e_msgindex_c2s_get_boss_god_time"
    "\020\206v\022.\n)e_msgindex_s2c_send_oracle_trial_"
    "info_all\020\304w\0220\n+e_msgindex_c2s_send_oracl"
    "e_trial_commpingup\020\305w\022/\n*e_msgindex_s2c_"
    "oracle_trial_commpingup_end\020\306w\0222\n-e_msgi"
    "ndex_c2s_get_oracle_trial_customs_award\020"
    "\307w\0227\n2e_msgindex_s2c_send_oracle_trial_c"
    "ustoms_award_end\020\310w\022)\n$e_msgindex_c2s_ge"
    "t_oracle_trial_rank\020\311w\022-\n(e_msgindex_s2c"
    "_get_oracle_trial_rank_end\020\312w\0226\n1e_msgin"
    "dex_s2c_send_oracle_trial_funben_over_in"
    "fo\020\313w\022)\n$e_msgindex_s2c_oracle_trial_tem"
    "plate\020\314w\022+\n&e_msgindex_c2s_join_legion_s"
    "tation_map\020\250x\022*\n%e_msgindex_c2s_add_legi"
    "on_boss_damage\020\251x\022.\n)e_msgindex_s2c_add_"
    "legion_boss_damage_end\020\252x\0220\n+e_msgindex_"
    "s2c_add_legion_damage_big_player\020\253x\022&\n!e"
    "_msgindex_c2s_start_assist_fight\020\361y\022)\n$e"
    "_msgindex_c2s_get_assist_fight_info\020\362y\022*"
    "\n%e_msgindex_s2c_sycn_assist_fight_info\020"
    "\363y\022$\n\037e_msgindex_c2s_req_assist_fight\020\364y"
    "\022\'\n\"e_msgindex_c2s_cancel_assist_fight\020\365"
    "y\022+\n&e_msgindex_s2c_sync_assist_fight_st"
    "ate\020\366y\0223\n.e_msgindex_s2c_assist_fight_en"
    "d_to_show_reward\020\367y\0229\n4e_msgindex_s2c_as"
    "sist_fight_end_to_show_thank_reward\020\370y\022+"
    "\n&e_msgindex_c2s_create_assist_fight_npc"
    "\020\371y\022,\n\'e_msgindex_s2c_send_be_assist_fig"
    "ht_tip\020\372y\022/\n)e_msgindex_s2d_send_server_"
    "info_to_daemon\020\350\373\003\022\"\n\034e_msgindex_d2s_clo"
    "se_process\020\351\373\003\022\035\n\027e_msgindex_d2s_gm_orde"
    "r\020\352\373\003\022\036\n\030e_msgindex_s2d_order_end\020\353\373\003\022\'\n"
    "!e_msgindex_s2d_send_string_to_eye\020\354\373\003\022)"
    "\n$e_msgindex_c2s_get_map_legion_player\020\214"
    "y\022*\n%e_msgindex_s2c_send_map_legion_play"
    "er\020\215y\022\'\n\"e_mgsindex_c2s_invite_legion_da"
    "nce\020\216y\022+\n&e_mgsindex_s2c_invite_legion_d"
    "ance_end\020\217y\022*\n%e_mgsindex_s2c_be_invite_"
    "legion_dance\020\220y\022.\n)e_mgsindex_c2s_be_inv"
    "ite_legion_dance_end\020\221y\022$\n\037e_mgsindex_c2"
    "s_legion_dance_end\020\222y\0222\n-e_mgsindex_s2c_"
    "legion_dance_interaction_begin\020\223y\0220\n+e_m"
    "gsindex_c2s_legion_dance_interaction_end"
    "\020\224y\022+\n&e_mgsindex_s2c_legion_Dance_clear"
    "_data\020\225y\022*\n%e_mgsindex_s2c_legion_add_bo"
    "nfire_end\020\226y\0227\n2e_mgsindex_s2c_legion_pd"
    "ate_legion_member_gs_value\020\324z\022;\n6e_mgsin"
    "dex_s2c_legion_pdate_legion_member_contr"
    "ibution\020\325z\0221\n,e_mgsindex_c2s_get_cumulat"
    "ive_sign_in_reward\020\270{\0225\n0e_mgsindex_s2c_"
    "get_cumulative_sign_in_reward_end\020\271{\022(\n#"
    "e_mgsindex_c2s_retroactive_all_days\020\272{\022,"
    "\n\'e_mgsindex_s2c_retroactive_all_days_en"
    "d\020\273{\022.\n)e_mgsindex_s2c_send_player_check"
    "_kill_num\020\234|\022/\n*e_mgsindex_s2c_refresh_p"
    "layer_pk_king_info\020\235|\022-\n(e_mgsindex_s2c_"
    "refresh_pk_king_map_state\020\236|\022*\n%e_mgsind"
    "ex_s2c_send_pk_king_rank_info\020\237|\022.\n)e_mg"
    "sindex_s2c_send_need_break_line_login\020\240|"
    "\0222\n-e_mgsindex_c2s_send_need_break_line_"
    "login_end\020\241|\022+\n&e_mgsindex_s2c_send_crea"
    "te_pk_end_time\020\242|\0220\n+e_mgsindex_s2c_send"
    "_pk_king_target_list_msg\020\243|\022+\n&e_mgsinde"
    "x_s2c_send_server_act_is_open\020\200}\0223\n.e_mg"
    "sindex_s2c_element_war_send_upgrade_noti"
    "fy\020\344}\022,\n\'e_mgsindex_c2s_element_war_send"
    "_sign_up\020\345}\0220\n+e_mgsindex_s2c_element_wa"
    "r_send_sign_up_end\020\346}\0227\n2e_mgsindex_c2s_"
    "element_war_send_sign_up_team_ready\020\347}\022;"
    "\n6e_mgsindex_s2c_element_war_send_sign_u"
    "p_team_ready_end\020\350}\0222\n-e_mgsindex_c2s_el"
    "ement_war_send_close_sign_up\020\351}\0226\n1e_mgs"
    "index_s2c_element_war_send_close_sign_up"
    "_end\020\352}\022.\n)e_mgsindex_s2c_element_war_se"
    "nd_role_info\020\353}\0222\n-e_msgindex_s2c_elemen"
    "t_war_send_match_success\020\354}\022-\n(e_msginde"
    "x_s2c_element_war_send_map_info\020\355}\0222\n-e_"
    "msgindex_s2c_element_war_send_map_role_i"
    "nfo\020\356}\022(\n#e_msgindex_s2c_element_war_end"
    "_info\020\357}\0223\n.e_msgindex_s2c_element_war_s"
    "end_boss_be_attack\020\360}\0222\n-e_mgsindex_c2s_"
    "element_war_get_mission_reward\020\361}\0226\n1e_m"
    "gsindex_s2c_element_war_get_mission_rewa"
    "rd_end\020\362}\022-\n(e_mgsindex_c2s_element_war_"
    "get_role_info\020\363}\022*\n%e_mgsindex_c2s_eleme"
    "nt_war_buy_ticket\020\364}\022.\n)e_mgsindex_s2c_e"
    "lement_war_buy_ticket_end\020\365}\0224\n/e_mgsind"
    "ex_s2c_element_war_send_create_ready_ui\020"
    "\366}\0220\n+e_mgsindex_s2c_element_war_create_"
    "boss_dead\020\367}\0222\n-e_mgsindex_s2c_element_w"
    "ar_send_map_rank_info\020\370}\022-\n(e_mgsindex_s"
    "2c_send_map_target_show_info\020\371}\022,\n\'e_mgs"
    "index_c2s_get_map_target_show_info\020\372}\022#\n"
    "\036e_msgindex_s2c_skytreasure_all\020\310~\022\'\n\"e_"
    "msgindex_c2s_skytreasure_operate\020\311~\022+\n&e"
    "_msgindex_s2c_skytreasure_operate_end\020\312~"
    "\022\037\n\032e_msgindex_s2c_starark_all\020\313~\022#\n\036e_m"
    "sgindex_c2s_starark_operate\020\314~\022\'\n\"e_msgi"
    "ndex_s2c_starark_operate_end\020\315~\0223\n.e_msg"
    "index_s2c_legion_strategy_world_boss_inf"
    "o\020\316~\022;\n6e_msgindex_c2s_request_legion_st"
    "rategy_world_boss_info\020\317~\0228\n3e_msgindex_"
    "s2c_send_legion_strategy_world_boss_info"
    "\020\320~\022\'\n\"e_msgindex_s2c_all_world_boss_inf"
    "o\020\321~\022.\n)e_msgindex_s2c_world_boss_strate"
    "gy_result\020\322~\022+\n&e_msgindex_c2s_request_w"
    "orld_boss_info\020\323~\0221\n,e_msgindex_s2c_star"
    "ark_five_round_rewad_list\020\324~\022\036\n\031e_msg_dp"
    "2ws_get_game_info\020\237\n\022\037\n\032e_msg_dp2ws_load"
    "_character\020\271\n\022!\n\033e_msg_dp2ws_load_arena_"
    "rank\020\205\201\002\022\036\n\030e_msg_dp2ws_create_robot\020\227\201\002"
    "\022\035\n\027e_msg_dp2ws_load_finish\020\230\201\002\022\'\n!e_msg"
    "_dp2ws_load_all_ranking_info\020\315\202\002\022\'\n!e_ms"
    "g_dp2ws_load_ranking_info_one\020\323\202\002\022\'\n!e_m"
    "sg_dp2ws_get_worship_value_end\020\327\202\002\022,\n&e_"
    "msg_dp2ws_load_all_service_rank_info\020\334\202\002"
    "\022%\n e_msg_dp2ws_load_server_list_end\020\267\n\022"
    "\036\n\031e_msg_dp2ws_gm_set_result\020\264\n\022\036\n\031e_msg"
    "_dp2ws_save_recharge\020\247\n\022\"\n\035e_msg_dp2ws_s"
    "end_recharge_end\020\251\n\022)\n$e_msg_dp2ws_rep_q"
    "uery_server_info_gm\020\273\027\022\037\n\032e_msg_dp2ws_gm"
    "_change_name\020\257\n\022!\n\034e_msg_dp2ws_gm_get_ro"
    "le_info\020\242\n\022$\n\037e_msg_dp2ws_gm_modify_role"
    "_info\020\245\n\022\030\n\022e_msg_s2s_test_msg\020\241\234\001\022\035\n\030e_"
    "msg_ws2dp_gm_open_time\020\253\n\022\037\n\032e_msg_ws2dp"
    "_set_cross_time\020\263\n\022#\n\036e_msg_ws2dp_gm_cha"
    "nge_password\020\254\n\022\037\n\032e_msg_ws2dp_gm_begin_"
    "cross\020\255\n\022!\n\034e_msg_ws2dp_save_server_list"
    "\020\265\n\022!\n\034e_msg_ws2dp_load_server_list\020\266\n\022\037"
    "\n\032e_msg_ws2dp_set_role_right\020\240\n\022\037\n\032e_msg"
    "_ws2dp_gm_change_name\020\256\n\022\035\n\030e_msg_ws2dp_"
    "gm_del_cache\020\260\n\022\034\n\027e_msg_ws2dp_gm_del_ro"
    "le\020\261\n\022\036\n\031e_msg_ws2dp_gm_stop_login\020\262\n\022\037\n"
    "\032e_msg_ws2dp_load_character\020\270\n\022!\n\034e_msg_"
    "ws2dp_gm_get_role_info\020\241\n\022$\n\037e_msg_ws2dp"
    "_gm_modify_role_info\020\244\n\022\'\n\"e_msg_ws2dp_g"
    "m_get_role_items_info\020\252\n\022#\n\036e_msg_ws2dp_"
    "load_relation_info\020\333\n\022\'\n\"e_msg_ws2dp_req"
    "_load_relation_list\020\335\n\022\035\n\030e_msg_ws2dp_ad"
    "d_relation\020\341\n\022\035\n\030e_msg_ws2dp_del_relatio"
    "n\020\343\n\022\037\n\031e_msg_ws2dp_check_id_mail\020\244\200\002\022(\n"
    "\"e_msg_ws2dp_save_arena_rank_change\020\210\201\002\022"
    "/\n)e_msg_ws2dp_save_other_server_mail_re"
    "cord\020\263\200\002\022(\n\"e_msg_ws2dp_load_other_serve"
    "r_mail\020\256\200\002\022\'\n!e_msg_ws2dp_del_other_serv"
    "er_mail\020\262\200\002\022\'\n!e_msg_ws2dp_load_all_rank"
    "ing_info\020\314\202\002\022\'\n!e_msg_ws2dp_save_ranking"
    "_info_one\020\324\202\002\022,\n&e_msg_ws2dp_load_all_se"
    "rvice_rank_info\020\333\202\002\022&\n e_msg_ws2dp_save_"
    "ranking_worship\020\316\202\002\022#\n\035e_msg_ws2dp_get_w"
    "orship_value\020\326\202\002\022\"\n\034e_msg_ws2dp_save_leg"
    "ion_info\020\336\205\002\022)\n#e_msg_ws2dp_save_legion_"
    "member_info\020\346\205\002\0222\n,e_msg_ws2dp_save_legi"
    "on_city_war_member_info\020\347\205\002\022$\n\036e_msg_ws2"
    "dp_delete_legion_info\020\337\205\002\022+\n%e_msg_ws2dp"
    "_delete_legion_member_info\020\340\205\002\0224\n.e_msg_"
    "ws2dp_delete_legion_city_war_member_info"
    "\020\341\205\002\022*\n$e_msg_ws2dp_del_legion_applicant"
    "_one\020\353\205\002\022\'\n!e_msg_ws2dp_save_legion_appl"
    "icant\020\352\205\002\0220\n*e_msg_ws2dp_save_legion_bos"
    "s_award_get_log\020\362\205\002\0224\n.e_msg_ws2dp_load_"
    "all_legion_boss_award_get_log\020\360\205\002\022 \n\032e_m"
    "sg_ws2dp_save_city_info\020\365\205\002\022#\n\035e_msg_ws2"
    "dp_save_war_bid_info\020\370\205\002\022$\n\036e_msg_ws2dp_"
    "clear_war_bid_info\020\371\205\002\022-\n\'e_msg_ws2dp_cl"
    "ear_overlord_legion_stuff\020\372\205\002\022#\n\035e_msg_w"
    "s2dp_save_legion_event\020\375\205\002\022$\n\036e_msg_ws2d"
    "p_clear_legion_event\020\377\205\002\022(\n\"e_msg_ws2dp_"
    "save_legion_bonus_info\020\200\206\002\022)\n#e_msg_ws2d"
    "p_clear_legion_bonus_info\020\203\206\002\022%\n e_msg_w"
    "s2dp_save_server_attr_val\020\237\r\022%\n e_msg_ws"
    "2dp_load_server_attr_val\020\235\r\022&\n e_msg_ws2"
    "dp_load_cross_city_info\020\214\206\002\022&\n e_msg_ws2"
    "dp_save_cross_city_info\020\220\206\002\022\'\n!e_msg_ws2"
    "dp_clear_cross_city_info\020\223\206\002\022\"\n\034e_msg_ws"
    "2dp_save_best_record\020\356\210\002\022&\n e_msg_ws2dp_"
    "load_all_best_record\020\354\210\002\0220\n*e_msg_ws2dp_"
    "save_gain_treasure_record_info\020\240\222\002\022:\n4e_"
    "msg_ws2dp_ws2dp_load_all_gain_treasure_r"
    "ecord_info\020\236\222\002\022+\n%e_msg_ws2dp_save_cross"
    "_server_pk_info\020\330\227\002\0220\n*e_msg_ws2dp_save_"
    "load_cross_server_pk_info\020\331\227\002\0221\n+e_msg_w"
    "s2dp_save_clear_cross_server_pk_info\020\333\227\002"
    "\022.\n(e_msg_ws2dp_save_cross_server_harry_"
    "info\020\240\231\002\0223\n-e_msg_ws2dp_save_load_cross_"
    "server_harry_info\020\241\231\002\022.\n(e_msg_ws2dp_sav"
    "e_send_del_one_server_msg\020\270\231\002\0224\n.e_msg_w"
    "s2dp_save_load_load_harry_player_detail\020"
    "\254\231\002\022\"\n\034e_msg_ws2dp_load_role_pk_top\020\244\207\002\022"
    "#\n\035e_msg_ws2dp_load_role_pk_info\020\246\207\002\022#\n\035"
    "e_msg_ws2dp_save_role_pk_info\020\251\207\002\022,\n&e_m"
    "sg_ws2dp_save_role_pk_honor_refresh\020\252\207\002\022"
    "\"\n\034e_msg_ws2dp_load_role_pk_log\020\253\207\002\022!\n\033e"
    "_msg_ws2dp_save_mail_event\020\352\201\002\022\037\n\031e_msg_"
    "ws2dp_save_red_pack\020\367\201\002\022\037\n\031e_msg_ws2dp_l"
    "oad_red_pack\020\370\201\002\022(\n\"e_msg_ws2dp_load_red"
    "_pack_receiver\020\371\201\002\022%\n\037e_msg_ws2dp_add_re"
    "d_pack_to_sql\020\372\201\002\022.\n(e_msg_ws2dp_add_red"
    "_pack_receiver_to_sql\020\373\201\002\022%\n\037e_msg_ws2dp"
    "_del_red_pack_by_sql\020\374\201\002\022&\n e_msg_ws2dp_"
    "save_mail_event_item\020\353\201\002\022!\n\033e_msg_ws2dp_"
    "load_mail_event\020\354\201\002\022&\n e_msg_ws2dp_load_"
    "mail_event_item\020\355\201\002\022/\n)e_msg_ws2dp_save_"
    "new_globel_mail_had_info\020\361\201\002\022!\n\033e_msg_ws"
    "2dp_save_world_boss\020\210\210\002\022!\n\033e_msg_ws2dp_l"
    "oad_world_boss\020\211\210\002\022%\n\037e_msg_ws2dp_del_dr"
    "aw_info_to_db\020\305\215\002\022%\n\037e_msg_ws2dp_add_dra"
    "w_info_to_db\020\304\215\002\022#\n\035e_msg_ws2dp_load_inf"
    "o_from_db\020\306\215\002\022!\n\033e_msg_ws2dp_save_big_pl"
    "ayer\020\320\211\002\022!\n\033e_msg_ws2dp_load_big_player\020"
    "\321\211\002\022(\n\"e_msg_ws2dp_load_big_player_detai"
    "l\020\322\211\002\022%\n\037e_msg_ws2dp_add_auction_into_db"
    "\020\215\217\002\022)\n#e_msg_ws2dp_auction_find_buy_tar"
    "get\020\221\217\002\022%\n\037e_msg_ws2dp_auction_cancel_se"
    "ll\020\232\217\002\022)\n#e_msg_ws2dp_auction_find_bid_t"
    "arget\020\245\217\002\022\035\n\027e_msg_ws2dp_bid_success\020\252\217\002"
    "\022(\n\"e_msg_ws2dp_auction_clear_old_item\020\254"
    "\217\002\022(\n\"e_msg_ws2dp_auction_add_share_list"
    "\020\256\217\002\022-\n\'e_msg_ws2dp_auction_add_purchase"
    "_record\020\226\217\002\022(\n\"e_msg_ws2dp_auction_req_s"
    "hare_list\020\257\217\002\022.\n(e_msg_ws2dp_auction_che"
    "ck_legion_selling\020\262\217\002\022(\n\"e_msg_ws2dp_auc"
    "tion_del_bid_record\020\265\217\002\022.\n(e_msg_ws2dp_a"
    "uction_clear_old_bid_record\020\266\217\002\022#\n\035e_msg"
    "_ws2dp_auction_show_sell\020\271\217\002\022\"\n\034e_msg_ws"
    "2dp_auction_time_out\020\273\217\002\022!\n\033e_msg_ws2dp_"
    "save_marry_info\020\324\220\002\022!\n\033e_msg_ws2dp_load_"
    "marry_info\020\326\220\002\022+\n%e_msg_ws2dp_marry_get_"
    "last_login_time\020\335\220\002\022.\n(e_msg_ws2dp_load_"
    "marry_info_cross_server\020\344\220\002\022.\n(e_msg_ws2"
    "dp_load_cloud_shop_players_info\020\344\223\002\022.\n(e"
    "_msg_ws2dp_save_cloud_shop_players_info\020"
    "\346\223\002\022.\n(e_msg_ws2dp_clear_cloud_shop_play"
    "er_info\020\347\223\002\022\"\n\035e_msg_ws2dp_check_player_"
    "name\020\351\n\022#\n\036e_msg_ws2dp_change_player_nam"
    "e\020\353\n\022(\n\"e_msg_ws2dp_save_chat_with_offli"
    "ne\020\236\204\002\022(\n\"e_msg_ws2dp_load_chat_with_off"
    "line\020\237\204\002\022-\n\'e_msg_ws2dp_eliminate_chat_w"
    "ith_offline\020\241\204\002\022*\n$e_msg_ws2dp_auction_c"
    "heck_world_sell\020\267\217\002\022(\n\"e_msg_ws2dp_updat"
    "e_role_time_limit\020\326\224\002\022(\n\"e_msg_ws2dp_del"
    "ete_time_limit_temp\020\327\224\002\022/\n)e_msg_ws2dp_d"
    "elete_time_limit_branch_temp\020\330\224\002\022.\n(e_ms"
    "g_ws2dp_refresh_role_time_limit_guid\020\331\224\002"
    "\022+\n&e_msgindex_s2c_refresh_lucky_card_in"
    "fo\020\254\177\022&\n!e_msgindex_s2c_refresh_lucky_ca"
    "rd\020\255\177\022&\n!e_msgindex_c2s_lucky_card_opera"
    "te\020\256\177\022*\n%e_msgindex_s2c_lucky_card_opera"
    "te_end\020\257\177\0224\n.e_msgindex_s2c_send_new_ser"
    "ver_treasure_finish\020\220\200\001\022-\n\'e_msgindex_c2"
    "s_transfer_attack_city_map\020\364\200\001\0225\n/e_msgi"
    "ndex_s2c_send_attack_city_map_legion_inf"
    "o\020\365\200\001\022)\n#e_msgindex_c2s_get_attack_city_"
    "info\020\366\200\001\022.\n(e_msgindex_c2s_get_attack_ci"
    "ty_rank_list\020\367\200\001\0222\n,e_msgindex_c2s_get_a"
    "ttack_city_map_rank_list\020\370\200\001\022(\n\"e_msgind"
    "ex_c2s_attack_city_operate\020\371\200\001\022,\n&e_msgi"
    "ndex_s2c_attack_city_operate_end\020\372\200\001\022)\n#"
    "e_msgindex_s2c_attack_city_npc_list\020\373\200\001\022"
    ")\n#e_msgindex_s2c_attack_city_camp_cut\020\374"
    "\200\001\022)\n#e_msgindex_c2s_transfer_to_bron_po"
    "s\020\375\200\001\022,\n&e_msgindex_s2c_attack_city_legi"
    "on_info\020\376\200\001\022)\n#e_msgindex_s2c_attack_cit"
    "y_end_info\020\377\200\001\0221\n+e_msgindex_s2c_attack_"
    "city_legion_rank_info\020\200\201\001\022/\n)e_msgindex_"
    "s2c_attack_city_legion_map_end\020\201\201\001\022\'\n!e_"
    "msgindex_c2s_attack_legion_call\020\202\201\001\022)\n#e"
    "_msgindex_s2c_attack_transfer_info\020\203\201\001\022-"
    "\n\'e_msgindex_c2s_end_attack_transfer_inf"
    "o\020\204\201\001\0226\n0e_msgindex_s2c_attack_city_npc_"
    "state_change_info\020\205\201\001\022-\n\'e_msgindex_c2s_"
    "time_feed_back_operation\020\210\201\001\0221\n+e_msgind"
    "ex_s2c_time_feed_back_operation_end\020\211\201\001\022"
    "-\n\'e_msgindex_s2c_send_time_feed_back_in"
    "fo\020\212\201\001\022.\n(e_msgindex_c2s_time_limit_gift"
    "_operation\020\222\201\001\0222\n,e_msgindex_s2c_time_li"
    "mit_gift_operation_end\020\223\201\001\022+\n%e_msgindex"
    "_s2c_update_time_limit_gift\020\224\201\001\022/\n)e_msg"
    "index_s2c_initiative_time_limit_gift\020\225\201\001"
    "\0220\n*e_msgindex_s2c_limit_time_notice_inf"
    "o_list\020\234\201\001\022)\n#e_msgindex_c2s_send_subscr"
    "ibe_daily\020\246\201\001\022-\n\'e_msgindex_s2c_send_sub"
    "scribe_daily_end\020\247\201\001\022.\n(e_msgindex_s2c_s"
    "end_subscribe_daily_info\020\250\201\001\022\'\n!e_msgind"
    "ex_s2c_send_offline_award\020\330\201\001\022&\n e_msgin"
    "dex_c2s_get_offline_award\020\331\201\001\022%\n\037e_msgin"
    "dex_c2s_get_online_award\020\332\201\001\022#\n\035e_msgind"
    "ex_c2s_kill_award_npc\020\274\202\001\022#\n\035e_msgindex_"
    "s2c_kill_award_npc\020\275\202\001\022)\n#e_msgindex_c2s"
    "_upgrade_search_level\020\276\202\001\022-\n\'e_msgindex_"
    "s2c_upgrade_search_level_end\020\277\202\001\022\"\n\034e_ms"
    "gindex_c2s_get_npc_award\020\300\202\001\022&\n e_msgind"
    "ex_c2s_get_npc_award_end\020\301\202\001\022&\n e_msgind"
    "ex_c2s_open_treasuer_pic\020\302\202\001\022\'\n!e_msgind"
    "ex_c2s_get_treasuer_award\020\303\202\001\022\'\n!e_msgin"
    "dex_s2c_get_treasuer_award\020\304\202\001\022#\n\035e_msgi"
    "ndex_s2c_map_settlement\020\305\202\001\022!\n\033e_msginde"
    "x_c2s_map_anim_end\020\306\202\001\022!\n\033e_msgindex_s2c"
    "_map_anim_end\020\307\202\001\022&\n e_msgindex_c2s_refr"
    "ush_award_npc\020\310\202\001\022%\n\037e_msgindex_c2s_sear"
    "ch_award_npc\020\311\202\001\022)\n#e_msgindex_s2c_searc"
    "h_award_npc_end\020\312\202\001\022\"\n\034e_msgindex_s2c_fl"
    "ip_box_info\020\313\202\001\022\"\n\034e_msgindex_c2s_flip_b"
    "ox_open\020\314\202\001\022&\n e_msgindex_s2c_flip_box_o"
    "pen_end\020\315\202\001\022\037\n\031e_msgindex_c2s_mop_up_map"
    "\020\316\202\001\022&\n e_msgindex_s2c_finger_guess_info"
    "\020\317\202\001\022%\n\037e_msgindex_c2s_finger_guess_end\020"
    "\320\202\001\022%\n\037e_msgindex_s2c_finger_guess_end\020\321"
    "\202\001\022)\n#e_msgindex_s2c_smashing_bottle_inf"
    "o\020\322\202\001\022(\n\"e_msgindex_c2s_smashing_bottle_"
    "end\020\323\202\001\022(\n\"e_msgindex_s2c_smashing_bottl"
    "e_end\020\324\202\001\022&\n e_msgindex_s2c_activity_inf"
    "o_all\020\240\203\001\022&\n e_msgindex_s2c_activity_inf"
    "o_one\020\241\203\001\022&\n e_msgindex_s2c_activity_inf"
    "o_del\020\242\203\001\022!\n\033e_msgindex_c2s_get_activity"
    "\020\243\203\001\022&\n e_msgindex_s2c_wheel_plate_begin"
    "\020\244\203\001\022$\n\036e_msgindex_c2s_wheel_plate_end\020\245"
    "\203\001\022$\n\036e_msgindex_s2c_wheel_plate_end\020\246\203\001", 52760);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "net.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_net_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_net_2eproto {
  StaticDescriptorInitializer_net_2eproto() {
    protobuf_AddDesc_net_2eproto();
  }
} static_descriptor_initializer_net_2eproto_;
const ::google::protobuf::EnumDescriptor* proto_header_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proto_header_descriptor_;
}
bool proto_header_IsValid(int value) {
  switch(value) {
    case 1311:
    case 1312:
    case 1313:
    case 1314:
    case 1316:
    case 1317:
    case 1319:
    case 1321:
    case 1322:
    case 1323:
    case 1324:
    case 1325:
    case 1326:
    case 1327:
    case 1328:
    case 1329:
    case 1330:
    case 1331:
    case 1332:
    case 1333:
    case 1334:
    case 1335:
    case 1336:
    case 1337:
    case 1371:
    case 1373:
    case 1377:
    case 1379:
    case 1385:
    case 1387:
    case 1693:
    case 1695:
    case 3003:
    case 10000:
    case 10001:
    case 10002:
    case 10003:
    case 10004:
    case 10005:
    case 10006:
    case 10007:
    case 10008:
    case 10100:
    case 10101:
    case 10102:
    case 10200:
    case 10201:
    case 10202:
    case 10203:
    case 10204:
    case 10205:
    case 10206:
    case 10207:
    case 10208:
    case 10209:
    case 10210:
    case 10211:
    case 10212:
    case 10213:
    case 10301:
    case 10302:
    case 10303:
    case 10304:
    case 10305:
    case 10306:
    case 10307:
    case 10308:
    case 10309:
    case 10310:
    case 10311:
    case 10312:
    case 10313:
    case 10314:
    case 10315:
    case 10316:
    case 10317:
    case 10318:
    case 10319:
    case 10320:
    case 10321:
    case 10322:
    case 10323:
    case 10324:
    case 10325:
    case 10328:
    case 10329:
    case 10330:
    case 10331:
    case 10332:
    case 10333:
    case 10334:
    case 10335:
    case 10336:
    case 10337:
    case 10338:
    case 10339:
    case 10340:
    case 10341:
    case 10342:
    case 10343:
    case 10344:
    case 10345:
    case 10346:
    case 10347:
    case 10348:
    case 10349:
    case 10350:
    case 10351:
    case 10352:
    case 10353:
    case 10354:
    case 10355:
    case 10356:
    case 10357:
    case 10358:
    case 10359:
    case 10360:
    case 10361:
    case 10362:
    case 10363:
    case 10364:
    case 10365:
    case 10366:
    case 10367:
    case 10368:
    case 10369:
    case 10370:
    case 10371:
    case 10372:
    case 10373:
    case 10374:
    case 10375:
    case 10376:
    case 10377:
    case 10378:
    case 10379:
    case 10380:
    case 10381:
    case 10382:
    case 10383:
    case 10384:
    case 10407:
    case 10408:
    case 10409:
    case 10410:
    case 10411:
    case 10412:
    case 10413:
    case 10414:
    case 10415:
    case 10416:
    case 10417:
    case 10418:
    case 10419:
    case 10420:
    case 10421:
    case 10422:
    case 10423:
    case 10424:
    case 10425:
    case 10426:
    case 10427:
    case 10428:
    case 10429:
    case 10430:
    case 10431:
    case 10432:
    case 10433:
    case 10434:
    case 10435:
    case 10436:
    case 10437:
    case 10438:
    case 10439:
    case 10440:
    case 10441:
    case 10442:
    case 10443:
    case 10444:
    case 10445:
    case 10446:
    case 10447:
    case 10448:
    case 10449:
    case 10450:
    case 10451:
    case 10452:
    case 10453:
    case 10454:
    case 10455:
    case 10456:
    case 10457:
    case 10458:
    case 10459:
    case 10460:
    case 10461:
    case 10462:
    case 10463:
    case 10464:
    case 10465:
    case 10466:
    case 10467:
    case 10468:
    case 10469:
    case 10470:
    case 10471:
    case 10472:
    case 10473:
    case 10474:
    case 10475:
    case 10476:
    case 10477:
    case 10478:
    case 10479:
    case 10480:
    case 10481:
    case 10482:
    case 10483:
    case 10484:
    case 10485:
    case 10486:
    case 10487:
    case 10488:
    case 10489:
    case 10490:
    case 10491:
    case 10492:
    case 10493:
    case 10494:
    case 10495:
    case 10496:
    case 10497:
    case 10498:
    case 10499:
    case 10500:
    case 10501:
    case 10502:
    case 10503:
    case 10504:
    case 10505:
    case 10506:
    case 10507:
    case 10508:
    case 10509:
    case 10510:
    case 10511:
    case 10512:
    case 10513:
    case 10514:
    case 10515:
    case 10516:
    case 10517:
    case 10518:
    case 10519:
    case 10520:
    case 10521:
    case 10522:
    case 10523:
    case 10524:
    case 10525:
    case 10526:
    case 10527:
    case 10528:
    case 10529:
    case 10530:
    case 10531:
    case 10532:
    case 10533:
    case 10534:
    case 10535:
    case 10536:
    case 10537:
    case 10538:
    case 10539:
    case 10540:
    case 10541:
    case 10550:
    case 10551:
    case 10552:
    case 10553:
    case 10554:
    case 10555:
    case 10556:
    case 10557:
    case 10558:
    case 10559:
    case 10560:
    case 10561:
    case 10562:
    case 10563:
    case 10564:
    case 10565:
    case 10566:
    case 10567:
    case 10568:
    case 10601:
    case 10602:
    case 10603:
    case 10604:
    case 10607:
    case 10608:
    case 10609:
    case 10610:
    case 10611:
    case 10612:
    case 10613:
    case 10614:
    case 10615:
    case 10616:
    case 10617:
    case 10618:
    case 10619:
    case 10620:
    case 10621:
    case 10622:
    case 10623:
    case 10701:
    case 10702:
    case 10703:
    case 10704:
    case 10705:
    case 10706:
    case 10707:
    case 10708:
    case 10709:
    case 10710:
    case 10711:
    case 10712:
    case 10713:
    case 10714:
    case 10715:
    case 10716:
    case 10717:
    case 10718:
    case 10719:
    case 10720:
    case 10721:
    case 10722:
    case 10723:
    case 10724:
    case 10725:
    case 10726:
    case 10727:
    case 10728:
    case 10729:
    case 10730:
    case 10731:
    case 10732:
    case 10733:
    case 10734:
    case 10735:
    case 10736:
    case 10737:
    case 10738:
    case 10739:
    case 10740:
    case 10741:
    case 10742:
    case 10743:
    case 10744:
    case 10745:
    case 10746:
    case 10747:
    case 10748:
    case 10749:
    case 10750:
    case 10751:
    case 10752:
    case 10753:
    case 10754:
    case 10755:
    case 10756:
    case 10757:
    case 10758:
    case 10802:
    case 10803:
    case 10804:
    case 10805:
    case 10806:
    case 10807:
    case 10808:
    case 10809:
    case 10810:
    case 10811:
    case 10812:
    case 10813:
    case 10814:
    case 10815:
    case 10816:
    case 10817:
    case 10901:
    case 10902:
    case 10903:
    case 10904:
    case 11001:
    case 11002:
    case 11003:
    case 11004:
    case 11005:
    case 11006:
    case 11007:
    case 11008:
    case 11009:
    case 11010:
    case 11101:
    case 11102:
    case 11103:
    case 11104:
    case 11105:
    case 11106:
    case 11107:
    case 11108:
    case 11109:
    case 11110:
    case 11111:
    case 11112:
    case 11113:
    case 11114:
    case 11115:
    case 11201:
    case 11202:
    case 11203:
    case 11204:
    case 11205:
    case 11206:
    case 11207:
    case 11301:
    case 11302:
    case 11303:
    case 11304:
    case 11305:
    case 11306:
    case 11401:
    case 11402:
    case 11403:
    case 11404:
    case 11501:
    case 11502:
    case 11503:
    case 11504:
    case 11506:
    case 11508:
    case 11509:
    case 11510:
    case 11511:
    case 11512:
    case 11513:
    case 11514:
    case 11601:
    case 11602:
    case 11603:
    case 11604:
    case 11605:
    case 11630:
    case 11631:
    case 11632:
    case 11634:
    case 11640:
    case 11641:
    case 11642:
    case 11643:
    case 11649:
    case 11650:
    case 11651:
    case 11652:
    case 11653:
    case 11654:
    case 11655:
    case 11656:
    case 11657:
    case 11658:
    case 11659:
    case 11660:
    case 11661:
    case 11665:
    case 11666:
    case 11667:
    case 11668:
    case 11669:
    case 11701:
    case 11702:
    case 11703:
    case 11704:
    case 11705:
    case 11706:
    case 11707:
    case 11708:
    case 11709:
    case 11710:
    case 11711:
    case 11712:
    case 11713:
    case 11714:
    case 11715:
    case 11716:
    case 11717:
    case 11718:
    case 11719:
    case 11720:
    case 11721:
    case 11722:
    case 11723:
    case 11724:
    case 11725:
    case 11726:
    case 11727:
    case 11728:
    case 11729:
    case 11730:
    case 11731:
    case 11732:
    case 11733:
    case 11734:
    case 11735:
    case 11736:
    case 11737:
    case 11738:
    case 11739:
    case 11740:
    case 11741:
    case 11742:
    case 11743:
    case 11744:
    case 11745:
    case 11746:
    case 11747:
    case 11748:
    case 11801:
    case 11802:
    case 11803:
    case 11804:
    case 11805:
    case 11806:
    case 11807:
    case 11808:
    case 11809:
    case 11810:
    case 11811:
    case 11901:
    case 11902:
    case 11903:
    case 11904:
    case 11905:
    case 11906:
    case 11907:
    case 11908:
    case 11909:
    case 11910:
    case 11911:
    case 11912:
    case 11913:
    case 11914:
    case 11915:
    case 12001:
    case 12002:
    case 12003:
    case 12004:
    case 12005:
    case 12006:
    case 12007:
    case 12008:
    case 12009:
    case 12010:
    case 12011:
    case 12012:
    case 12013:
    case 12014:
    case 12015:
    case 12016:
    case 12017:
    case 12018:
    case 12019:
    case 12020:
    case 12051:
    case 12052:
    case 12053:
    case 12054:
    case 12055:
    case 12056:
    case 12057:
    case 12058:
    case 12059:
    case 12060:
    case 12061:
    case 12062:
    case 12063:
    case 12064:
    case 12065:
    case 12066:
    case 12067:
    case 12068:
    case 12069:
    case 12070:
    case 12071:
    case 12072:
    case 12073:
    case 12074:
    case 12075:
    case 12076:
    case 12077:
    case 12078:
    case 12079:
    case 12080:
    case 12081:
    case 12082:
    case 12083:
    case 12084:
    case 12085:
    case 12101:
    case 12102:
    case 12103:
    case 12104:
    case 12105:
    case 12106:
    case 12107:
    case 12108:
    case 12109:
    case 12110:
    case 12111:
    case 12112:
    case 12113:
    case 12114:
    case 12115:
    case 12116:
    case 12117:
    case 12118:
    case 12119:
    case 12120:
    case 12121:
    case 12122:
    case 12123:
    case 12124:
    case 12126:
    case 12127:
    case 12128:
    case 12129:
    case 12130:
    case 12131:
    case 12132:
    case 12133:
    case 12134:
    case 12135:
    case 12136:
    case 12137:
    case 12138:
    case 12139:
    case 12140:
    case 12141:
    case 12142:
    case 12143:
    case 12144:
    case 12145:
    case 12146:
    case 12147:
    case 12148:
    case 12149:
    case 12150:
    case 12151:
    case 12152:
    case 12153:
    case 12154:
    case 12155:
    case 12156:
    case 12157:
    case 12158:
    case 12159:
    case 12160:
    case 12161:
    case 12162:
    case 12163:
    case 12164:
    case 12165:
    case 12166:
    case 12167:
    case 12168:
    case 12169:
    case 12170:
    case 12171:
    case 12172:
    case 12173:
    case 12174:
    case 12175:
    case 12176:
    case 12177:
    case 12178:
    case 12179:
    case 12180:
    case 12181:
    case 12182:
    case 12183:
    case 12184:
    case 12185:
    case 12186:
    case 12187:
    case 12188:
    case 12189:
    case 12190:
    case 12191:
    case 12192:
    case 12193:
    case 12194:
    case 12195:
    case 12196:
    case 12197:
    case 12198:
    case 12199:
    case 12200:
    case 12201:
    case 12202:
    case 12203:
    case 12204:
    case 12205:
    case 12206:
    case 12207:
    case 12208:
    case 12209:
    case 12210:
    case 12211:
    case 12212:
    case 12213:
    case 12214:
    case 12215:
    case 12216:
    case 12217:
    case 12218:
    case 12219:
    case 12220:
    case 12221:
    case 12222:
    case 12223:
    case 12224:
    case 12225:
    case 12226:
    case 12227:
    case 12228:
    case 12229:
    case 12301:
    case 12302:
    case 12303:
    case 12304:
    case 12305:
    case 12401:
    case 12402:
    case 12403:
    case 12404:
    case 12501:
    case 12502:
    case 12503:
    case 12504:
    case 12505:
    case 12506:
    case 12551:
    case 12552:
    case 12553:
    case 12554:
    case 12555:
    case 12601:
    case 12602:
    case 12603:
    case 12604:
    case 12605:
    case 12606:
    case 12607:
    case 12608:
    case 12609:
    case 12610:
    case 12611:
    case 12612:
    case 12701:
    case 12702:
    case 12703:
    case 12704:
    case 12705:
    case 12706:
    case 12707:
    case 12708:
    case 12709:
    case 12710:
    case 12711:
    case 12712:
    case 12713:
    case 12800:
    case 12801:
    case 12901:
    case 12902:
    case 12903:
    case 12904:
    case 13001:
    case 13002:
    case 13003:
    case 13004:
    case 13201:
    case 13202:
    case 13203:
    case 13204:
    case 13205:
    case 13206:
    case 13207:
    case 13301:
    case 13302:
    case 13303:
    case 13401:
    case 13402:
    case 13403:
    case 13404:
    case 13405:
    case 13406:
    case 13407:
    case 13408:
    case 13409:
    case 13501:
    case 13502:
    case 13503:
    case 13504:
    case 13601:
    case 13602:
    case 13603:
    case 13604:
    case 13605:
    case 13606:
    case 13607:
    case 13608:
    case 13609:
    case 13610:
    case 13611:
    case 13612:
    case 13613:
    case 13614:
    case 13615:
    case 13616:
    case 13617:
    case 13618:
    case 13619:
    case 13620:
    case 13621:
    case 13622:
    case 13623:
    case 13624:
    case 13625:
    case 13626:
    case 13627:
    case 13628:
    case 13629:
    case 13630:
    case 13631:
    case 13632:
    case 13633:
    case 13634:
    case 13635:
    case 13636:
    case 13637:
    case 13638:
    case 13639:
    case 13640:
    case 13641:
    case 13642:
    case 13643:
    case 13644:
    case 13645:
    case 13646:
    case 13647:
    case 13648:
    case 13649:
    case 13650:
    case 13651:
    case 13652:
    case 13653:
    case 13654:
    case 13655:
    case 13656:
    case 13657:
    case 13658:
    case 13701:
    case 13702:
    case 13703:
    case 13704:
    case 13705:
    case 13706:
    case 13707:
    case 13708:
    case 13709:
    case 13710:
    case 13711:
    case 13712:
    case 13713:
    case 13714:
    case 13715:
    case 13716:
    case 13717:
    case 13801:
    case 13802:
    case 13803:
    case 13804:
    case 13805:
    case 13806:
    case 13807:
    case 13808:
    case 13901:
    case 13902:
    case 14001:
    case 14002:
    case 14003:
    case 14004:
    case 14005:
    case 14006:
    case 14007:
    case 14008:
    case 14009:
    case 14010:
    case 14101:
    case 14102:
    case 14103:
    case 14104:
    case 14151:
    case 14152:
    case 14153:
    case 14154:
    case 14155:
    case 14156:
    case 14157:
    case 14158:
    case 14200:
    case 14201:
    case 14250:
    case 14251:
    case 14301:
    case 14302:
    case 14357:
    case 14358:
    case 14359:
    case 14400:
    case 14401:
    case 14402:
    case 14403:
    case 14404:
    case 14500:
    case 14600:
    case 14601:
    case 14602:
    case 14603:
    case 14604:
    case 14605:
    case 14606:
    case 14607:
    case 14700:
    case 14701:
    case 14702:
    case 14703:
    case 14704:
    case 14705:
    case 14706:
    case 14707:
    case 14708:
    case 14709:
    case 14712:
    case 14713:
    case 14714:
    case 14715:
    case 14716:
    case 14717:
    case 14718:
    case 14719:
    case 14800:
    case 14801:
    case 14802:
    case 14803:
    case 14804:
    case 14805:
    case 14900:
    case 14901:
    case 14902:
    case 14903:
    case 14904:
    case 14905:
    case 14906:
    case 14907:
    case 14908:
    case 14909:
    case 14910:
    case 14911:
    case 15100:
    case 15101:
    case 15102:
    case 15103:
    case 15104:
    case 15105:
    case 15106:
    case 15107:
    case 15108:
    case 15109:
    case 15110:
    case 15300:
    case 15301:
    case 15302:
    case 15303:
    case 15304:
    case 15305:
    case 15306:
    case 15307:
    case 15308:
    case 15400:
    case 15401:
    case 15402:
    case 15403:
    case 15500:
    case 15501:
    case 15502:
    case 15503:
    case 15504:
    case 15505:
    case 15506:
    case 15507:
    case 15508:
    case 15509:
    case 15510:
    case 15601:
    case 15602:
    case 15603:
    case 15604:
    case 15605:
    case 15606:
    case 15607:
    case 15608:
    case 15609:
    case 15610:
    case 15700:
    case 15701:
    case 15800:
    case 15801:
    case 15802:
    case 15803:
    case 15900:
    case 15901:
    case 15902:
    case 15903:
    case 15904:
    case 15905:
    case 15906:
    case 15907:
    case 16000:
    case 16100:
    case 16101:
    case 16102:
    case 16103:
    case 16104:
    case 16105:
    case 16106:
    case 16107:
    case 16108:
    case 16109:
    case 16110:
    case 16111:
    case 16112:
    case 16113:
    case 16114:
    case 16115:
    case 16116:
    case 16117:
    case 16118:
    case 16119:
    case 16120:
    case 16121:
    case 16122:
    case 16200:
    case 16201:
    case 16202:
    case 16203:
    case 16204:
    case 16205:
    case 16206:
    case 16207:
    case 16208:
    case 16209:
    case 16210:
    case 16211:
    case 16212:
    case 16300:
    case 16301:
    case 16302:
    case 16303:
    case 16400:
    case 16500:
    case 16501:
    case 16502:
    case 16503:
    case 16504:
    case 16505:
    case 16506:
    case 16507:
    case 16508:
    case 16509:
    case 16510:
    case 16511:
    case 16512:
    case 16513:
    case 16514:
    case 16515:
    case 16516:
    case 16517:
    case 16520:
    case 16521:
    case 16522:
    case 16530:
    case 16531:
    case 16532:
    case 16533:
    case 16540:
    case 16550:
    case 16551:
    case 16552:
    case 16600:
    case 16601:
    case 16602:
    case 16700:
    case 16701:
    case 16702:
    case 16703:
    case 16704:
    case 16705:
    case 16706:
    case 16707:
    case 16708:
    case 16709:
    case 16710:
    case 16711:
    case 16712:
    case 16713:
    case 16714:
    case 16715:
    case 16716:
    case 16717:
    case 16718:
    case 16719:
    case 16720:
    case 16721:
    case 16722:
    case 16723:
    case 16724:
    case 16800:
    case 16801:
    case 16802:
    case 16803:
    case 16804:
    case 16805:
    case 16806:
    case 20001:
    case 32804:
    case 32814:
    case 32818:
    case 32819:
    case 32901:
    case 32904:
    case 32919:
    case 32920:
    case 33002:
    case 33003:
    case 33004:
    case 33005:
    case 33009:
    case 33015:
    case 33016:
    case 33017:
    case 33018:
    case 33019:
    case 33020:
    case 33100:
    case 33101:
    case 33102:
    case 33107:
    case 33108:
    case 33110:
    case 33111:
    case 33115:
    case 33116:
    case 33310:
    case 33311:
    case 33313:
    case 33502:
    case 33503:
    case 33504:
    case 33505:
    case 33510:
    case 33511:
    case 33514:
    case 33515:
    case 33520:
    case 33522:
    case 33525:
    case 33528:
    case 33529:
    case 33530:
    case 33533:
    case 33535:
    case 33536:
    case 33539:
    case 33548:
    case 33552:
    case 33555:
    case 33700:
    case 33702:
    case 33705:
    case 33706:
    case 33707:
    case 33800:
    case 33801:
    case 33900:
    case 33902:
    case 34000:
    case 34001:
    case 34002:
    case 34500:
    case 34501:
    case 34502:
    case 34701:
    case 34705:
    case 34710:
    case 34714:
    case 34725:
    case 34730:
    case 34732:
    case 34734:
    case 34735:
    case 34738:
    case 34741:
    case 34742:
    case 34743:
    case 34745:
    case 34747:
    case 34900:
    case 34902:
    case 34909:
    case 34916:
    case 35102:
    case 35104:
    case 35300:
    case 35302:
    case 35303:
    case 35414:
    case 35415:
    case 35416:
    case 35417:
    case 35800:
    case 35801:
    case 35803:
    case 36000:
    case 36001:
    case 36012:
    case 36024:
    case 65000:
    case 65001:
    case 65002:
    case 65003:
    case 65004:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace faith

// @@protoc_insertion_point(global_scope)
