// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phantom.proto
// Protobuf C++ Version: 5.29.3

#include "phantom.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace faith {

inline constexpr phantom_proto_phantom_operate_end::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : phantom_id_{0},
        oper_type_{0},
        result_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR phantom_proto_phantom_operate_end::phantom_proto_phantom_operate_end(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct phantom_proto_phantom_operate_endDefaultTypeInternal {
  PROTOBUF_CONSTEXPR phantom_proto_phantom_operate_endDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~phantom_proto_phantom_operate_endDefaultTypeInternal() {}
  union {
    phantom_proto_phantom_operate_end _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 phantom_proto_phantom_operate_endDefaultTypeInternal _phantom_proto_phantom_operate_end_default_instance_;

inline constexpr phantom_proto_phantom_operate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : phantom_id_{0},
        oper_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR phantom_proto_phantom_operate::phantom_proto_phantom_operate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct phantom_proto_phantom_operateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR phantom_proto_phantom_operateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~phantom_proto_phantom_operateDefaultTypeInternal() {}
  union {
    phantom_proto_phantom_operate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 phantom_proto_phantom_operateDefaultTypeInternal _phantom_proto_phantom_operate_default_instance_;

inline constexpr phantom_proto_phantom_one::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : phantom_info_{},
        _phantom_info_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR phantom_proto_phantom_one::phantom_proto_phantom_one(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct phantom_proto_phantom_oneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR phantom_proto_phantom_oneDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~phantom_proto_phantom_oneDefaultTypeInternal() {}
  union {
    phantom_proto_phantom_one _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 phantom_proto_phantom_oneDefaultTypeInternal _phantom_proto_phantom_one_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR phantom_proto::phantom_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct phantom_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR phantom_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~phantom_protoDefaultTypeInternal() {}
  union {
    phantom_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 phantom_protoDefaultTypeInternal _phantom_proto_default_instance_;

inline constexpr phantom_proto_phantom_all::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : role_guid_{},
        _role_guid_cached_byte_size_{0},
        phantom_array_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR phantom_proto_phantom_all::phantom_proto_phantom_all(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct phantom_proto_phantom_allDefaultTypeInternal {
  PROTOBUF_CONSTEXPR phantom_proto_phantom_allDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~phantom_proto_phantom_allDefaultTypeInternal() {}
  union {
    phantom_proto_phantom_all _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 phantom_proto_phantom_allDefaultTypeInternal _phantom_proto_phantom_all_default_instance_;
}  // namespace faith
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_phantom_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_phantom_2eproto = nullptr;
const ::uint32_t
    TableStruct_phantom_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_one, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_one, _impl_.phantom_info_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_all, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_all, _impl_.role_guid_),
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_all, _impl_.phantom_array_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate, _impl_.phantom_id_),
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate, _impl_.oper_type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate_end, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate_end, _impl_.phantom_id_),
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate_end, _impl_.oper_type_),
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto_phantom_operate_end, _impl_.result_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::faith::phantom_proto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::faith::phantom_proto_phantom_one)},
        {9, -1, -1, sizeof(::faith::phantom_proto_phantom_all)},
        {19, -1, -1, sizeof(::faith::phantom_proto_phantom_operate)},
        {29, -1, -1, sizeof(::faith::phantom_proto_phantom_operate_end)},
        {40, -1, -1, sizeof(::faith::phantom_proto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::faith::_phantom_proto_phantom_one_default_instance_._instance,
    &::faith::_phantom_proto_phantom_all_default_instance_._instance,
    &::faith::_phantom_proto_phantom_operate_default_instance_._instance,
    &::faith::_phantom_proto_phantom_operate_end_default_instance_._instance,
    &::faith::_phantom_proto_default_instance_._instance,
};
const char descriptor_table_protodef_phantom_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rphantom.proto\022\005faith\"\227\002\n\rphantom_proto"
    "\032#\n\013phantom_one\022\024\n\014phantom_info\030\001 \003(\005\032Y\n"
    "\013phantom_all\022\021\n\trole_guid\030\001 \003(\005\0227\n\rphant"
    "om_array\030\002 \003(\0132 .faith.phantom_proto.pha"
    "ntom_one\0328\n\017phantom_operate\022\022\n\nphantom_i"
    "d\030\001 \001(\005\022\021\n\toper_type\030\002 \001(\005\032L\n\023phantom_op"
    "erate_end\022\022\n\nphantom_id\030\001 \001(\005\022\021\n\toper_ty"
    "pe\030\002 \001(\005\022\016\n\006result\030\003 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_phantom_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_phantom_2eproto = {
    false,
    false,
    312,
    descriptor_table_protodef_phantom_2eproto,
    "phantom.proto",
    &descriptor_table_phantom_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_phantom_2eproto::offsets,
    file_level_enum_descriptors_phantom_2eproto,
    file_level_service_descriptors_phantom_2eproto,
};
namespace faith {
// ===================================================================

class phantom_proto_phantom_one::_Internal {
 public:
};

phantom_proto_phantom_one::phantom_proto_phantom_one(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.phantom_proto.phantom_one)
}
inline PROTOBUF_NDEBUG_INLINE phantom_proto_phantom_one::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::faith::phantom_proto_phantom_one& from_msg)
      : phantom_info_{visibility, arena, from.phantom_info_},
        _phantom_info_cached_byte_size_{0},
        _cached_size_{0} {}

phantom_proto_phantom_one::phantom_proto_phantom_one(
    ::google::protobuf::Arena* arena,
    const phantom_proto_phantom_one& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  phantom_proto_phantom_one* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:faith.phantom_proto.phantom_one)
}
inline PROTOBUF_NDEBUG_INLINE phantom_proto_phantom_one::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : phantom_info_{visibility, arena},
        _phantom_info_cached_byte_size_{0},
        _cached_size_{0} {}

inline void phantom_proto_phantom_one::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
phantom_proto_phantom_one::~phantom_proto_phantom_one() {
  // @@protoc_insertion_point(destructor:faith.phantom_proto.phantom_one)
  SharedDtor(*this);
}
inline void phantom_proto_phantom_one::SharedDtor(MessageLite& self) {
  phantom_proto_phantom_one& this_ = static_cast<phantom_proto_phantom_one&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* phantom_proto_phantom_one::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) phantom_proto_phantom_one(arena);
}
constexpr auto phantom_proto_phantom_one::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_one, _impl_.phantom_info_) +
          decltype(phantom_proto_phantom_one::_impl_.phantom_info_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(phantom_proto_phantom_one), alignof(phantom_proto_phantom_one), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&phantom_proto_phantom_one::PlacementNew_,
                                 sizeof(phantom_proto_phantom_one),
                                 alignof(phantom_proto_phantom_one));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull phantom_proto_phantom_one::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_phantom_proto_phantom_one_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &phantom_proto_phantom_one::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<phantom_proto_phantom_one>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &phantom_proto_phantom_one::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<phantom_proto_phantom_one>(), &phantom_proto_phantom_one::ByteSizeLong,
            &phantom_proto_phantom_one::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_one, _impl_._cached_size_),
        false,
    },
    &phantom_proto_phantom_one::kDescriptorMethods,
    &descriptor_table_phantom_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* phantom_proto_phantom_one::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> phantom_proto_phantom_one::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::phantom_proto_phantom_one>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int32 phantom_info = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_one, _impl_.phantom_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 phantom_info = 1;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_one, _impl_.phantom_info_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void phantom_proto_phantom_one::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.phantom_proto.phantom_one)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.phantom_info_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* phantom_proto_phantom_one::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const phantom_proto_phantom_one& this_ = static_cast<const phantom_proto_phantom_one&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* phantom_proto_phantom_one::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const phantom_proto_phantom_one& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.phantom_proto.phantom_one)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated int32 phantom_info = 1;
          {
            int byte_size = this_._impl_._phantom_info_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  1, this_._internal_phantom_info(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.phantom_proto.phantom_one)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t phantom_proto_phantom_one::ByteSizeLong(const MessageLite& base) {
          const phantom_proto_phantom_one& this_ = static_cast<const phantom_proto_phantom_one&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t phantom_proto_phantom_one::ByteSizeLong() const {
          const phantom_proto_phantom_one& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.phantom_proto.phantom_one)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 phantom_info = 1;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_phantom_info(), 1,
                      this_._impl_._phantom_info_cached_byte_size_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void phantom_proto_phantom_one::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<phantom_proto_phantom_one*>(&to_msg);
  auto& from = static_cast<const phantom_proto_phantom_one&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.phantom_proto.phantom_one)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_phantom_info()->MergeFrom(from._internal_phantom_info());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void phantom_proto_phantom_one::CopyFrom(const phantom_proto_phantom_one& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.phantom_proto.phantom_one)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void phantom_proto_phantom_one::InternalSwap(phantom_proto_phantom_one* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.phantom_info_.InternalSwap(&other->_impl_.phantom_info_);
}

::google::protobuf::Metadata phantom_proto_phantom_one::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class phantom_proto_phantom_all::_Internal {
 public:
};

phantom_proto_phantom_all::phantom_proto_phantom_all(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.phantom_proto.phantom_all)
}
inline PROTOBUF_NDEBUG_INLINE phantom_proto_phantom_all::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::faith::phantom_proto_phantom_all& from_msg)
      : role_guid_{visibility, arena, from.role_guid_},
        _role_guid_cached_byte_size_{0},
        phantom_array_{visibility, arena, from.phantom_array_},
        _cached_size_{0} {}

phantom_proto_phantom_all::phantom_proto_phantom_all(
    ::google::protobuf::Arena* arena,
    const phantom_proto_phantom_all& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  phantom_proto_phantom_all* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:faith.phantom_proto.phantom_all)
}
inline PROTOBUF_NDEBUG_INLINE phantom_proto_phantom_all::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : role_guid_{visibility, arena},
        _role_guid_cached_byte_size_{0},
        phantom_array_{visibility, arena},
        _cached_size_{0} {}

inline void phantom_proto_phantom_all::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
phantom_proto_phantom_all::~phantom_proto_phantom_all() {
  // @@protoc_insertion_point(destructor:faith.phantom_proto.phantom_all)
  SharedDtor(*this);
}
inline void phantom_proto_phantom_all::SharedDtor(MessageLite& self) {
  phantom_proto_phantom_all& this_ = static_cast<phantom_proto_phantom_all&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* phantom_proto_phantom_all::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) phantom_proto_phantom_all(arena);
}
constexpr auto phantom_proto_phantom_all::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_.role_guid_) +
          decltype(phantom_proto_phantom_all::_impl_.role_guid_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_.phantom_array_) +
          decltype(phantom_proto_phantom_all::_impl_.phantom_array_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(phantom_proto_phantom_all), alignof(phantom_proto_phantom_all), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&phantom_proto_phantom_all::PlacementNew_,
                                 sizeof(phantom_proto_phantom_all),
                                 alignof(phantom_proto_phantom_all));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull phantom_proto_phantom_all::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_phantom_proto_phantom_all_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &phantom_proto_phantom_all::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<phantom_proto_phantom_all>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &phantom_proto_phantom_all::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<phantom_proto_phantom_all>(), &phantom_proto_phantom_all::ByteSizeLong,
            &phantom_proto_phantom_all::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_._cached_size_),
        false,
    },
    &phantom_proto_phantom_all::kDescriptorMethods,
    &descriptor_table_phantom_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* phantom_proto_phantom_all::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> phantom_proto_phantom_all::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::phantom_proto_phantom_all>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .faith.phantom_proto.phantom_one phantom_array = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_.phantom_array_)}},
    // repeated int32 role_guid = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_.role_guid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int32 role_guid = 1;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_.role_guid_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated .faith.phantom_proto.phantom_one phantom_array = 2;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_all, _impl_.phantom_array_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::faith::phantom_proto_phantom_one>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void phantom_proto_phantom_all::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.phantom_proto.phantom_all)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.role_guid_.Clear();
  _impl_.phantom_array_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* phantom_proto_phantom_all::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const phantom_proto_phantom_all& this_ = static_cast<const phantom_proto_phantom_all&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* phantom_proto_phantom_all::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const phantom_proto_phantom_all& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.phantom_proto.phantom_all)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated int32 role_guid = 1;
          {
            int byte_size = this_._impl_._role_guid_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  1, this_._internal_role_guid(), byte_size, target);
            }
          }

          // repeated .faith.phantom_proto.phantom_one phantom_array = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_phantom_array_size());
               i < n; i++) {
            const auto& repfield = this_._internal_phantom_array().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.phantom_proto.phantom_all)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t phantom_proto_phantom_all::ByteSizeLong(const MessageLite& base) {
          const phantom_proto_phantom_all& this_ = static_cast<const phantom_proto_phantom_all&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t phantom_proto_phantom_all::ByteSizeLong() const {
          const phantom_proto_phantom_all& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.phantom_proto.phantom_all)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 role_guid = 1;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_role_guid(), 1,
                      this_._impl_._role_guid_cached_byte_size_);
            }
            // repeated .faith.phantom_proto.phantom_one phantom_array = 2;
            {
              total_size += 1UL * this_._internal_phantom_array_size();
              for (const auto& msg : this_._internal_phantom_array()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void phantom_proto_phantom_all::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<phantom_proto_phantom_all*>(&to_msg);
  auto& from = static_cast<const phantom_proto_phantom_all&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.phantom_proto.phantom_all)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_role_guid()->MergeFrom(from._internal_role_guid());
  _this->_internal_mutable_phantom_array()->MergeFrom(
      from._internal_phantom_array());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void phantom_proto_phantom_all::CopyFrom(const phantom_proto_phantom_all& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.phantom_proto.phantom_all)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void phantom_proto_phantom_all::InternalSwap(phantom_proto_phantom_all* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.role_guid_.InternalSwap(&other->_impl_.role_guid_);
  _impl_.phantom_array_.InternalSwap(&other->_impl_.phantom_array_);
}

::google::protobuf::Metadata phantom_proto_phantom_all::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class phantom_proto_phantom_operate::_Internal {
 public:
};

phantom_proto_phantom_operate::phantom_proto_phantom_operate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.phantom_proto.phantom_operate)
}
phantom_proto_phantom_operate::phantom_proto_phantom_operate(
    ::google::protobuf::Arena* arena, const phantom_proto_phantom_operate& from)
    : phantom_proto_phantom_operate(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE phantom_proto_phantom_operate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void phantom_proto_phantom_operate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, phantom_id_),
           0,
           offsetof(Impl_, oper_type_) -
               offsetof(Impl_, phantom_id_) +
               sizeof(Impl_::oper_type_));
}
phantom_proto_phantom_operate::~phantom_proto_phantom_operate() {
  // @@protoc_insertion_point(destructor:faith.phantom_proto.phantom_operate)
  SharedDtor(*this);
}
inline void phantom_proto_phantom_operate::SharedDtor(MessageLite& self) {
  phantom_proto_phantom_operate& this_ = static_cast<phantom_proto_phantom_operate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* phantom_proto_phantom_operate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) phantom_proto_phantom_operate(arena);
}
constexpr auto phantom_proto_phantom_operate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(phantom_proto_phantom_operate),
                                            alignof(phantom_proto_phantom_operate));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull phantom_proto_phantom_operate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_phantom_proto_phantom_operate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &phantom_proto_phantom_operate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<phantom_proto_phantom_operate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &phantom_proto_phantom_operate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<phantom_proto_phantom_operate>(), &phantom_proto_phantom_operate::ByteSizeLong,
            &phantom_proto_phantom_operate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_._cached_size_),
        false,
    },
    &phantom_proto_phantom_operate::kDescriptorMethods,
    &descriptor_table_phantom_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* phantom_proto_phantom_operate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> phantom_proto_phantom_operate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::phantom_proto_phantom_operate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 oper_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(phantom_proto_phantom_operate, _impl_.oper_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_.oper_type_)}},
    // int32 phantom_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(phantom_proto_phantom_operate, _impl_.phantom_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_.phantom_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 phantom_id = 1;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_.phantom_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 oper_type = 2;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_.oper_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void phantom_proto_phantom_operate::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.phantom_proto.phantom_operate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.phantom_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.oper_type_) -
      reinterpret_cast<char*>(&_impl_.phantom_id_)) + sizeof(_impl_.oper_type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* phantom_proto_phantom_operate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const phantom_proto_phantom_operate& this_ = static_cast<const phantom_proto_phantom_operate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* phantom_proto_phantom_operate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const phantom_proto_phantom_operate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.phantom_proto.phantom_operate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 phantom_id = 1;
          if (this_._internal_phantom_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_phantom_id(), target);
          }

          // int32 oper_type = 2;
          if (this_._internal_oper_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_oper_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.phantom_proto.phantom_operate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t phantom_proto_phantom_operate::ByteSizeLong(const MessageLite& base) {
          const phantom_proto_phantom_operate& this_ = static_cast<const phantom_proto_phantom_operate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t phantom_proto_phantom_operate::ByteSizeLong() const {
          const phantom_proto_phantom_operate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.phantom_proto.phantom_operate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 phantom_id = 1;
            if (this_._internal_phantom_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_phantom_id());
            }
            // int32 oper_type = 2;
            if (this_._internal_oper_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_oper_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void phantom_proto_phantom_operate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<phantom_proto_phantom_operate*>(&to_msg);
  auto& from = static_cast<const phantom_proto_phantom_operate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.phantom_proto.phantom_operate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_phantom_id() != 0) {
    _this->_impl_.phantom_id_ = from._impl_.phantom_id_;
  }
  if (from._internal_oper_type() != 0) {
    _this->_impl_.oper_type_ = from._impl_.oper_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void phantom_proto_phantom_operate::CopyFrom(const phantom_proto_phantom_operate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.phantom_proto.phantom_operate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void phantom_proto_phantom_operate::InternalSwap(phantom_proto_phantom_operate* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_.oper_type_)
      + sizeof(phantom_proto_phantom_operate::_impl_.oper_type_)
      - PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate, _impl_.phantom_id_)>(
          reinterpret_cast<char*>(&_impl_.phantom_id_),
          reinterpret_cast<char*>(&other->_impl_.phantom_id_));
}

::google::protobuf::Metadata phantom_proto_phantom_operate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class phantom_proto_phantom_operate_end::_Internal {
 public:
};

phantom_proto_phantom_operate_end::phantom_proto_phantom_operate_end(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:faith.phantom_proto.phantom_operate_end)
}
phantom_proto_phantom_operate_end::phantom_proto_phantom_operate_end(
    ::google::protobuf::Arena* arena, const phantom_proto_phantom_operate_end& from)
    : phantom_proto_phantom_operate_end(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE phantom_proto_phantom_operate_end::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void phantom_proto_phantom_operate_end::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, phantom_id_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, phantom_id_) +
               sizeof(Impl_::result_));
}
phantom_proto_phantom_operate_end::~phantom_proto_phantom_operate_end() {
  // @@protoc_insertion_point(destructor:faith.phantom_proto.phantom_operate_end)
  SharedDtor(*this);
}
inline void phantom_proto_phantom_operate_end::SharedDtor(MessageLite& self) {
  phantom_proto_phantom_operate_end& this_ = static_cast<phantom_proto_phantom_operate_end&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* phantom_proto_phantom_operate_end::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) phantom_proto_phantom_operate_end(arena);
}
constexpr auto phantom_proto_phantom_operate_end::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(phantom_proto_phantom_operate_end),
                                            alignof(phantom_proto_phantom_operate_end));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull phantom_proto_phantom_operate_end::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_phantom_proto_phantom_operate_end_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &phantom_proto_phantom_operate_end::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<phantom_proto_phantom_operate_end>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &phantom_proto_phantom_operate_end::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<phantom_proto_phantom_operate_end>(), &phantom_proto_phantom_operate_end::ByteSizeLong,
            &phantom_proto_phantom_operate_end::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_._cached_size_),
        false,
    },
    &phantom_proto_phantom_operate_end::kDescriptorMethods,
    &descriptor_table_phantom_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* phantom_proto_phantom_operate_end::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> phantom_proto_phantom_operate_end::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::phantom_proto_phantom_operate_end>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 phantom_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(phantom_proto_phantom_operate_end, _impl_.phantom_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.phantom_id_)}},
    // int32 oper_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(phantom_proto_phantom_operate_end, _impl_.oper_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.oper_type_)}},
    // int32 result = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(phantom_proto_phantom_operate_end, _impl_.result_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 phantom_id = 1;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.phantom_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 oper_type = 2;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.oper_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 result = 3;
    {PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void phantom_proto_phantom_operate_end::Clear() {
// @@protoc_insertion_point(message_clear_start:faith.phantom_proto.phantom_operate_end)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.phantom_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.result_) -
      reinterpret_cast<char*>(&_impl_.phantom_id_)) + sizeof(_impl_.result_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* phantom_proto_phantom_operate_end::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const phantom_proto_phantom_operate_end& this_ = static_cast<const phantom_proto_phantom_operate_end&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* phantom_proto_phantom_operate_end::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const phantom_proto_phantom_operate_end& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:faith.phantom_proto.phantom_operate_end)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 phantom_id = 1;
          if (this_._internal_phantom_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_phantom_id(), target);
          }

          // int32 oper_type = 2;
          if (this_._internal_oper_type() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_oper_type(), target);
          }

          // int32 result = 3;
          if (this_._internal_result() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:faith.phantom_proto.phantom_operate_end)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t phantom_proto_phantom_operate_end::ByteSizeLong(const MessageLite& base) {
          const phantom_proto_phantom_operate_end& this_ = static_cast<const phantom_proto_phantom_operate_end&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t phantom_proto_phantom_operate_end::ByteSizeLong() const {
          const phantom_proto_phantom_operate_end& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:faith.phantom_proto.phantom_operate_end)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 phantom_id = 1;
            if (this_._internal_phantom_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_phantom_id());
            }
            // int32 oper_type = 2;
            if (this_._internal_oper_type() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_oper_type());
            }
            // int32 result = 3;
            if (this_._internal_result() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void phantom_proto_phantom_operate_end::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<phantom_proto_phantom_operate_end*>(&to_msg);
  auto& from = static_cast<const phantom_proto_phantom_operate_end&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:faith.phantom_proto.phantom_operate_end)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_phantom_id() != 0) {
    _this->_impl_.phantom_id_ = from._impl_.phantom_id_;
  }
  if (from._internal_oper_type() != 0) {
    _this->_impl_.oper_type_ = from._impl_.oper_type_;
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void phantom_proto_phantom_operate_end::CopyFrom(const phantom_proto_phantom_operate_end& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:faith.phantom_proto.phantom_operate_end)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void phantom_proto_phantom_operate_end::InternalSwap(phantom_proto_phantom_operate_end* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.result_)
      + sizeof(phantom_proto_phantom_operate_end::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(phantom_proto_phantom_operate_end, _impl_.phantom_id_)>(
          reinterpret_cast<char*>(&_impl_.phantom_id_),
          reinterpret_cast<char*>(&other->_impl_.phantom_id_));
}

::google::protobuf::Metadata phantom_proto_phantom_operate_end::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class phantom_proto::_Internal {
 public:
};

phantom_proto::phantom_proto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:faith.phantom_proto)
}
phantom_proto::phantom_proto(
    ::google::protobuf::Arena* arena,
    const phantom_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  phantom_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:faith.phantom_proto)
}

inline void* phantom_proto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) phantom_proto(arena);
}
constexpr auto phantom_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(phantom_proto),
                                            alignof(phantom_proto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull phantom_proto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_phantom_proto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &phantom_proto::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<phantom_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &phantom_proto::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<phantom_proto>(), &phantom_proto::ByteSizeLong,
            &phantom_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(phantom_proto, _impl_._cached_size_),
        false,
    },
    &phantom_proto::kDescriptorMethods,
    &descriptor_table_phantom_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* phantom_proto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> phantom_proto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::faith::phantom_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata phantom_proto::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace faith
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_phantom_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
