// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: title.proto
// Protobuf C++ Version: 5.29.3

#ifndef title_2eproto_2epb_2eh
#define title_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_title_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_title_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_title_2eproto;
namespace faith {
class title_proto;
struct title_protoDefaultTypeInternal;
extern title_protoDefaultTypeInternal _title_proto_default_instance_;
class title_proto_own_title_msg_all;
struct title_proto_own_title_msg_allDefaultTypeInternal;
extern title_proto_own_title_msg_allDefaultTypeInternal _title_proto_own_title_msg_all_default_instance_;
class title_proto_title_add_title_end;
struct title_proto_title_add_title_endDefaultTypeInternal;
extern title_proto_title_add_title_endDefaultTypeInternal _title_proto_title_add_title_end_default_instance_;
class title_proto_title_equip_operate;
struct title_proto_title_equip_operateDefaultTypeInternal;
extern title_proto_title_equip_operateDefaultTypeInternal _title_proto_title_equip_operate_default_instance_;
class title_proto_title_info_one;
struct title_proto_title_info_oneDefaultTypeInternal;
extern title_proto_title_info_oneDefaultTypeInternal _title_proto_title_info_one_default_instance_;
class title_proto_title_open_title_system_end;
struct title_proto_title_open_title_system_endDefaultTypeInternal;
extern title_proto_title_open_title_system_endDefaultTypeInternal _title_proto_title_open_title_system_end_default_instance_;
class title_proto_title_set_title_no_need_see;
struct title_proto_title_set_title_no_need_seeDefaultTypeInternal;
extern title_proto_title_set_title_no_need_seeDefaultTypeInternal _title_proto_title_set_title_no_need_see_default_instance_;
}  // namespace faith
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace faith {

// ===================================================================


// -------------------------------------------------------------------

class title_proto_title_set_title_no_need_see final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:faith.title_proto.title_set_title_no_need_see) */ {
 public:
  inline title_proto_title_set_title_no_need_see() : title_proto_title_set_title_no_need_see(nullptr) {}
  ~title_proto_title_set_title_no_need_see() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto_title_set_title_no_need_see* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto_title_set_title_no_need_see));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto_title_set_title_no_need_see(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto_title_set_title_no_need_see(const title_proto_title_set_title_no_need_see& from) : title_proto_title_set_title_no_need_see(nullptr, from) {}
  inline title_proto_title_set_title_no_need_see(title_proto_title_set_title_no_need_see&& from) noexcept
      : title_proto_title_set_title_no_need_see(nullptr, std::move(from)) {}
  inline title_proto_title_set_title_no_need_see& operator=(const title_proto_title_set_title_no_need_see& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto_title_set_title_no_need_see& operator=(title_proto_title_set_title_no_need_see&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto_title_set_title_no_need_see& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto_title_set_title_no_need_see* internal_default_instance() {
    return reinterpret_cast<const title_proto_title_set_title_no_need_see*>(
        &_title_proto_title_set_title_no_need_see_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(title_proto_title_set_title_no_need_see& a, title_proto_title_set_title_no_need_see& b) { a.Swap(&b); }
  inline void Swap(title_proto_title_set_title_no_need_see* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto_title_set_title_no_need_see* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto_title_set_title_no_need_see* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<title_proto_title_set_title_no_need_see>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const title_proto_title_set_title_no_need_see& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const title_proto_title_set_title_no_need_see& from) { title_proto_title_set_title_no_need_see::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(title_proto_title_set_title_no_need_see* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto.title_set_title_no_need_see"; }

 protected:
  explicit title_proto_title_set_title_no_need_see(::google::protobuf::Arena* arena);
  title_proto_title_set_title_no_need_see(::google::protobuf::Arena* arena, const title_proto_title_set_title_no_need_see& from);
  title_proto_title_set_title_no_need_see(::google::protobuf::Arena* arena, title_proto_title_set_title_no_need_see&& from) noexcept
      : title_proto_title_set_title_no_need_see(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUnitGuidFieldNumber = 1,
  };
  // repeated int32 unit_guid = 1;
  int unit_guid_size() const;
  private:
  int _internal_unit_guid_size() const;

  public:
  void clear_unit_guid() ;
  ::int32_t unit_guid(int index) const;
  void set_unit_guid(int index, ::int32_t value);
  void add_unit_guid(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_unit_guid();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_unit_guid();

  public:
  // @@protoc_insertion_point(class_scope:faith.title_proto.title_set_title_no_need_see)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto_title_set_title_no_need_see& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> unit_guid_;
    ::google::protobuf::internal::CachedSize _unit_guid_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_title_2eproto;
};
// -------------------------------------------------------------------

class title_proto_title_open_title_system_end final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:faith.title_proto.title_open_title_system_end) */ {
 public:
  inline title_proto_title_open_title_system_end() : title_proto_title_open_title_system_end(nullptr) {}
  ~title_proto_title_open_title_system_end() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto_title_open_title_system_end* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto_title_open_title_system_end));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto_title_open_title_system_end(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto_title_open_title_system_end(const title_proto_title_open_title_system_end& from) : title_proto_title_open_title_system_end(nullptr, from) {}
  inline title_proto_title_open_title_system_end(title_proto_title_open_title_system_end&& from) noexcept
      : title_proto_title_open_title_system_end(nullptr, std::move(from)) {}
  inline title_proto_title_open_title_system_end& operator=(const title_proto_title_open_title_system_end& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto_title_open_title_system_end& operator=(title_proto_title_open_title_system_end&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto_title_open_title_system_end& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto_title_open_title_system_end* internal_default_instance() {
    return reinterpret_cast<const title_proto_title_open_title_system_end*>(
        &_title_proto_title_open_title_system_end_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(title_proto_title_open_title_system_end& a, title_proto_title_open_title_system_end& b) { a.Swap(&b); }
  inline void Swap(title_proto_title_open_title_system_end* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto_title_open_title_system_end* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto_title_open_title_system_end* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<title_proto_title_open_title_system_end>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const title_proto_title_open_title_system_end& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const title_proto_title_open_title_system_end& from) { title_proto_title_open_title_system_end::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(title_proto_title_open_title_system_end* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto.title_open_title_system_end"; }

 protected:
  explicit title_proto_title_open_title_system_end(::google::protobuf::Arena* arena);
  title_proto_title_open_title_system_end(::google::protobuf::Arena* arena, const title_proto_title_open_title_system_end& from);
  title_proto_title_open_title_system_end(::google::protobuf::Arena* arena, title_proto_title_open_title_system_end&& from) noexcept
      : title_proto_title_open_title_system_end(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUnitGuidFieldNumber = 1,
  };
  // repeated int32 unit_guid = 1;
  int unit_guid_size() const;
  private:
  int _internal_unit_guid_size() const;

  public:
  void clear_unit_guid() ;
  ::int32_t unit_guid(int index) const;
  void set_unit_guid(int index, ::int32_t value);
  void add_unit_guid(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_unit_guid();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_unit_guid();

  public:
  // @@protoc_insertion_point(class_scope:faith.title_proto.title_open_title_system_end)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto_title_open_title_system_end& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> unit_guid_;
    ::google::protobuf::internal::CachedSize _unit_guid_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_title_2eproto;
};
// -------------------------------------------------------------------

class title_proto_title_info_one final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:faith.title_proto.title_info_one) */ {
 public:
  inline title_proto_title_info_one() : title_proto_title_info_one(nullptr) {}
  ~title_proto_title_info_one() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto_title_info_one* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto_title_info_one));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto_title_info_one(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto_title_info_one(const title_proto_title_info_one& from) : title_proto_title_info_one(nullptr, from) {}
  inline title_proto_title_info_one(title_proto_title_info_one&& from) noexcept
      : title_proto_title_info_one(nullptr, std::move(from)) {}
  inline title_proto_title_info_one& operator=(const title_proto_title_info_one& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto_title_info_one& operator=(title_proto_title_info_one&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto_title_info_one& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto_title_info_one* internal_default_instance() {
    return reinterpret_cast<const title_proto_title_info_one*>(
        &_title_proto_title_info_one_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(title_proto_title_info_one& a, title_proto_title_info_one& b) { a.Swap(&b); }
  inline void Swap(title_proto_title_info_one* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto_title_info_one* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto_title_info_one* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<title_proto_title_info_one>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const title_proto_title_info_one& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const title_proto_title_info_one& from) { title_proto_title_info_one::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(title_proto_title_info_one* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto.title_info_one"; }

 protected:
  explicit title_proto_title_info_one(::google::protobuf::Arena* arena);
  title_proto_title_info_one(::google::protobuf::Arena* arena, const title_proto_title_info_one& from);
  title_proto_title_info_one(::google::protobuf::Arena* arena, title_proto_title_info_one&& from) noexcept
      : title_proto_title_info_one(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTitleDataFieldNumber = 1,
  };
  // repeated int32 title_data = 1;
  int title_data_size() const;
  private:
  int _internal_title_data_size() const;

  public:
  void clear_title_data() ;
  ::int32_t title_data(int index) const;
  void set_title_data(int index, ::int32_t value);
  void add_title_data(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& title_data() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_title_data();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_title_data() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_title_data();

  public:
  // @@protoc_insertion_point(class_scope:faith.title_proto.title_info_one)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto_title_info_one& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> title_data_;
    ::google::protobuf::internal::CachedSize _title_data_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_title_2eproto;
};
// -------------------------------------------------------------------

class title_proto_title_equip_operate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:faith.title_proto.title_equip_operate) */ {
 public:
  inline title_proto_title_equip_operate() : title_proto_title_equip_operate(nullptr) {}
  ~title_proto_title_equip_operate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto_title_equip_operate* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto_title_equip_operate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto_title_equip_operate(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto_title_equip_operate(const title_proto_title_equip_operate& from) : title_proto_title_equip_operate(nullptr, from) {}
  inline title_proto_title_equip_operate(title_proto_title_equip_operate&& from) noexcept
      : title_proto_title_equip_operate(nullptr, std::move(from)) {}
  inline title_proto_title_equip_operate& operator=(const title_proto_title_equip_operate& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto_title_equip_operate& operator=(title_proto_title_equip_operate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto_title_equip_operate& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto_title_equip_operate* internal_default_instance() {
    return reinterpret_cast<const title_proto_title_equip_operate*>(
        &_title_proto_title_equip_operate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(title_proto_title_equip_operate& a, title_proto_title_equip_operate& b) { a.Swap(&b); }
  inline void Swap(title_proto_title_equip_operate* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto_title_equip_operate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto_title_equip_operate* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<title_proto_title_equip_operate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const title_proto_title_equip_operate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const title_proto_title_equip_operate& from) { title_proto_title_equip_operate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(title_proto_title_equip_operate* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto.title_equip_operate"; }

 protected:
  explicit title_proto_title_equip_operate(::google::protobuf::Arena* arena);
  title_proto_title_equip_operate(::google::protobuf::Arena* arena, const title_proto_title_equip_operate& from);
  title_proto_title_equip_operate(::google::protobuf::Arena* arena, title_proto_title_equip_operate&& from) noexcept
      : title_proto_title_equip_operate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUnitGuidFieldNumber = 1,
    kTemplateIdFieldNumber = 2,
    kOperateTypeFieldNumber = 3,
  };
  // repeated int32 unit_guid = 1;
  int unit_guid_size() const;
  private:
  int _internal_unit_guid_size() const;

  public:
  void clear_unit_guid() ;
  ::int32_t unit_guid(int index) const;
  void set_unit_guid(int index, ::int32_t value);
  void add_unit_guid(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_unit_guid();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_unit_guid();

  public:
  // int32 template_id = 2;
  void clear_template_id() ;
  ::int32_t template_id() const;
  void set_template_id(::int32_t value);

  private:
  ::int32_t _internal_template_id() const;
  void _internal_set_template_id(::int32_t value);

  public:
  // int32 operate_type = 3;
  void clear_operate_type() ;
  ::int32_t operate_type() const;
  void set_operate_type(::int32_t value);

  private:
  ::int32_t _internal_operate_type() const;
  void _internal_set_operate_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:faith.title_proto.title_equip_operate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto_title_equip_operate& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> unit_guid_;
    ::google::protobuf::internal::CachedSize _unit_guid_cached_byte_size_;
    ::int32_t template_id_;
    ::int32_t operate_type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_title_2eproto;
};
// -------------------------------------------------------------------

class title_proto_title_add_title_end final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:faith.title_proto.title_add_title_end) */ {
 public:
  inline title_proto_title_add_title_end() : title_proto_title_add_title_end(nullptr) {}
  ~title_proto_title_add_title_end() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto_title_add_title_end* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto_title_add_title_end));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto_title_add_title_end(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto_title_add_title_end(const title_proto_title_add_title_end& from) : title_proto_title_add_title_end(nullptr, from) {}
  inline title_proto_title_add_title_end(title_proto_title_add_title_end&& from) noexcept
      : title_proto_title_add_title_end(nullptr, std::move(from)) {}
  inline title_proto_title_add_title_end& operator=(const title_proto_title_add_title_end& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto_title_add_title_end& operator=(title_proto_title_add_title_end&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto_title_add_title_end& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto_title_add_title_end* internal_default_instance() {
    return reinterpret_cast<const title_proto_title_add_title_end*>(
        &_title_proto_title_add_title_end_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(title_proto_title_add_title_end& a, title_proto_title_add_title_end& b) { a.Swap(&b); }
  inline void Swap(title_proto_title_add_title_end* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto_title_add_title_end* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto_title_add_title_end* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<title_proto_title_add_title_end>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const title_proto_title_add_title_end& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const title_proto_title_add_title_end& from) { title_proto_title_add_title_end::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(title_proto_title_add_title_end* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto.title_add_title_end"; }

 protected:
  explicit title_proto_title_add_title_end(::google::protobuf::Arena* arena);
  title_proto_title_add_title_end(::google::protobuf::Arena* arena, const title_proto_title_add_title_end& from);
  title_proto_title_add_title_end(::google::protobuf::Arena* arena, title_proto_title_add_title_end&& from) noexcept
      : title_proto_title_add_title_end(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUnitGuidFieldNumber = 1,
    kTemplateIdFieldNumber = 2,
    kResultFieldNumber = 3,
  };
  // repeated int32 unit_guid = 1;
  int unit_guid_size() const;
  private:
  int _internal_unit_guid_size() const;

  public:
  void clear_unit_guid() ;
  ::int32_t unit_guid(int index) const;
  void set_unit_guid(int index, ::int32_t value);
  void add_unit_guid(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_unit_guid();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_unit_guid() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_unit_guid();

  public:
  // int32 template_id = 2;
  void clear_template_id() ;
  ::int32_t template_id() const;
  void set_template_id(::int32_t value);

  private:
  ::int32_t _internal_template_id() const;
  void _internal_set_template_id(::int32_t value);

  public:
  // int32 result = 3;
  void clear_result() ;
  ::int32_t result() const;
  void set_result(::int32_t value);

  private:
  ::int32_t _internal_result() const;
  void _internal_set_result(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:faith.title_proto.title_add_title_end)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto_title_add_title_end& from_msg);
    ::google::protobuf::RepeatedField<::int32_t> unit_guid_;
    ::google::protobuf::internal::CachedSize _unit_guid_cached_byte_size_;
    ::int32_t template_id_;
    ::int32_t result_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_title_2eproto;
};
// -------------------------------------------------------------------

class title_proto final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:faith.title_proto) */ {
 public:
  inline title_proto() : title_proto(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto(const title_proto& from) : title_proto(nullptr, from) {}
  inline title_proto(title_proto&& from) noexcept
      : title_proto(nullptr, std::move(from)) {}
  inline title_proto& operator=(const title_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto& operator=(title_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto* internal_default_instance() {
    return reinterpret_cast<const title_proto*>(
        &_title_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(title_proto& a, title_proto& b) { a.Swap(&b); }
  inline void Swap(title_proto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<title_proto>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const title_proto& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const title_proto& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto"; }

 protected:
  explicit title_proto(::google::protobuf::Arena* arena);
  title_proto(::google::protobuf::Arena* arena, const title_proto& from);
  title_proto(::google::protobuf::Arena* arena, title_proto&& from) noexcept
      : title_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using title_equip_operate = title_proto_title_equip_operate;
  using title_info_one = title_proto_title_info_one;
  using own_title_msg_all = title_proto_own_title_msg_all;
  using title_add_title_end = title_proto_title_add_title_end;
  using title_open_title_system_end = title_proto_title_open_title_system_end;
  using title_set_title_no_need_see = title_proto_title_set_title_no_need_see;

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:faith.title_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_title_2eproto;
};
// -------------------------------------------------------------------

class title_proto_own_title_msg_all final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:faith.title_proto.own_title_msg_all) */ {
 public:
  inline title_proto_own_title_msg_all() : title_proto_own_title_msg_all(nullptr) {}
  ~title_proto_own_title_msg_all() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(title_proto_own_title_msg_all* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(title_proto_own_title_msg_all));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR title_proto_own_title_msg_all(
      ::google::protobuf::internal::ConstantInitialized);

  inline title_proto_own_title_msg_all(const title_proto_own_title_msg_all& from) : title_proto_own_title_msg_all(nullptr, from) {}
  inline title_proto_own_title_msg_all(title_proto_own_title_msg_all&& from) noexcept
      : title_proto_own_title_msg_all(nullptr, std::move(from)) {}
  inline title_proto_own_title_msg_all& operator=(const title_proto_own_title_msg_all& from) {
    CopyFrom(from);
    return *this;
  }
  inline title_proto_own_title_msg_all& operator=(title_proto_own_title_msg_all&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const title_proto_own_title_msg_all& default_instance() {
    return *internal_default_instance();
  }
  static inline const title_proto_own_title_msg_all* internal_default_instance() {
    return reinterpret_cast<const title_proto_own_title_msg_all*>(
        &_title_proto_own_title_msg_all_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(title_proto_own_title_msg_all& a, title_proto_own_title_msg_all& b) { a.Swap(&b); }
  inline void Swap(title_proto_own_title_msg_all* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(title_proto_own_title_msg_all* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  title_proto_own_title_msg_all* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<title_proto_own_title_msg_all>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const title_proto_own_title_msg_all& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const title_proto_own_title_msg_all& from) { title_proto_own_title_msg_all::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(title_proto_own_title_msg_all* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "faith.title_proto.own_title_msg_all"; }

 protected:
  explicit title_proto_own_title_msg_all(::google::protobuf::Arena* arena);
  title_proto_own_title_msg_all(::google::protobuf::Arena* arena, const title_proto_own_title_msg_all& from);
  title_proto_own_title_msg_all(::google::protobuf::Arena* arena, title_proto_own_title_msg_all&& from) noexcept
      : title_proto_own_title_msg_all(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTitleInfoArrFieldNumber = 1,
  };
  // repeated .faith.title_proto.title_info_one title_info_arr = 1;
  int title_info_arr_size() const;
  private:
  int _internal_title_info_arr_size() const;

  public:
  void clear_title_info_arr() ;
  ::faith::title_proto_title_info_one* mutable_title_info_arr(int index);
  ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>* mutable_title_info_arr();

  private:
  const ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>& _internal_title_info_arr() const;
  ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>* _internal_mutable_title_info_arr();
  public:
  const ::faith::title_proto_title_info_one& title_info_arr(int index) const;
  ::faith::title_proto_title_info_one* add_title_info_arr();
  const ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>& title_info_arr() const;
  // @@protoc_insertion_point(class_scope:faith.title_proto.own_title_msg_all)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const title_proto_own_title_msg_all& from_msg);
    ::google::protobuf::RepeatedPtrField< ::faith::title_proto_title_info_one > title_info_arr_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_title_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// title_proto_title_equip_operate

// repeated int32 unit_guid = 1;
inline int title_proto_title_equip_operate::_internal_unit_guid_size() const {
  return _internal_unit_guid().size();
}
inline int title_proto_title_equip_operate::unit_guid_size() const {
  return _internal_unit_guid_size();
}
inline void title_proto_title_equip_operate::clear_unit_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unit_guid_.Clear();
}
inline ::int32_t title_proto_title_equip_operate::unit_guid(int index) const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_equip_operate.unit_guid)
  return _internal_unit_guid().Get(index);
}
inline void title_proto_title_equip_operate::set_unit_guid(int index, ::int32_t value) {
  _internal_mutable_unit_guid()->Set(index, value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_equip_operate.unit_guid)
}
inline void title_proto_title_equip_operate::add_unit_guid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_unit_guid()->Add(value);
  // @@protoc_insertion_point(field_add:faith.title_proto.title_equip_operate.unit_guid)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& title_proto_title_equip_operate::unit_guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:faith.title_proto.title_equip_operate.unit_guid)
  return _internal_unit_guid();
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_equip_operate::mutable_unit_guid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:faith.title_proto.title_equip_operate.unit_guid)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_unit_guid();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
title_proto_title_equip_operate::_internal_unit_guid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unit_guid_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_equip_operate::_internal_mutable_unit_guid() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.unit_guid_;
}

// int32 template_id = 2;
inline void title_proto_title_equip_operate::clear_template_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.template_id_ = 0;
}
inline ::int32_t title_proto_title_equip_operate::template_id() const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_equip_operate.template_id)
  return _internal_template_id();
}
inline void title_proto_title_equip_operate::set_template_id(::int32_t value) {
  _internal_set_template_id(value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_equip_operate.template_id)
}
inline ::int32_t title_proto_title_equip_operate::_internal_template_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.template_id_;
}
inline void title_proto_title_equip_operate::_internal_set_template_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.template_id_ = value;
}

// int32 operate_type = 3;
inline void title_proto_title_equip_operate::clear_operate_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.operate_type_ = 0;
}
inline ::int32_t title_proto_title_equip_operate::operate_type() const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_equip_operate.operate_type)
  return _internal_operate_type();
}
inline void title_proto_title_equip_operate::set_operate_type(::int32_t value) {
  _internal_set_operate_type(value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_equip_operate.operate_type)
}
inline ::int32_t title_proto_title_equip_operate::_internal_operate_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.operate_type_;
}
inline void title_proto_title_equip_operate::_internal_set_operate_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.operate_type_ = value;
}

// -------------------------------------------------------------------

// title_proto_title_info_one

// repeated int32 title_data = 1;
inline int title_proto_title_info_one::_internal_title_data_size() const {
  return _internal_title_data().size();
}
inline int title_proto_title_info_one::title_data_size() const {
  return _internal_title_data_size();
}
inline void title_proto_title_info_one::clear_title_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_data_.Clear();
}
inline ::int32_t title_proto_title_info_one::title_data(int index) const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_info_one.title_data)
  return _internal_title_data().Get(index);
}
inline void title_proto_title_info_one::set_title_data(int index, ::int32_t value) {
  _internal_mutable_title_data()->Set(index, value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_info_one.title_data)
}
inline void title_proto_title_info_one::add_title_data(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_title_data()->Add(value);
  // @@protoc_insertion_point(field_add:faith.title_proto.title_info_one.title_data)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& title_proto_title_info_one::title_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:faith.title_proto.title_info_one.title_data)
  return _internal_title_data();
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_info_one::mutable_title_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:faith.title_proto.title_info_one.title_data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_title_data();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
title_proto_title_info_one::_internal_title_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_data_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_info_one::_internal_mutable_title_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.title_data_;
}

// -------------------------------------------------------------------

// title_proto_own_title_msg_all

// repeated .faith.title_proto.title_info_one title_info_arr = 1;
inline int title_proto_own_title_msg_all::_internal_title_info_arr_size() const {
  return _internal_title_info_arr().size();
}
inline int title_proto_own_title_msg_all::title_info_arr_size() const {
  return _internal_title_info_arr_size();
}
inline void title_proto_own_title_msg_all::clear_title_info_arr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_info_arr_.Clear();
}
inline ::faith::title_proto_title_info_one* title_proto_own_title_msg_all::mutable_title_info_arr(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:faith.title_proto.own_title_msg_all.title_info_arr)
  return _internal_mutable_title_info_arr()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>* title_proto_own_title_msg_all::mutable_title_info_arr()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:faith.title_proto.own_title_msg_all.title_info_arr)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_title_info_arr();
}
inline const ::faith::title_proto_title_info_one& title_proto_own_title_msg_all::title_info_arr(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:faith.title_proto.own_title_msg_all.title_info_arr)
  return _internal_title_info_arr().Get(index);
}
inline ::faith::title_proto_title_info_one* title_proto_own_title_msg_all::add_title_info_arr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::faith::title_proto_title_info_one* _add = _internal_mutable_title_info_arr()->Add();
  // @@protoc_insertion_point(field_add:faith.title_proto.own_title_msg_all.title_info_arr)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>& title_proto_own_title_msg_all::title_info_arr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:faith.title_proto.own_title_msg_all.title_info_arr)
  return _internal_title_info_arr();
}
inline const ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>&
title_proto_own_title_msg_all::_internal_title_info_arr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_info_arr_;
}
inline ::google::protobuf::RepeatedPtrField<::faith::title_proto_title_info_one>*
title_proto_own_title_msg_all::_internal_mutable_title_info_arr() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.title_info_arr_;
}

// -------------------------------------------------------------------

// title_proto_title_add_title_end

// repeated int32 unit_guid = 1;
inline int title_proto_title_add_title_end::_internal_unit_guid_size() const {
  return _internal_unit_guid().size();
}
inline int title_proto_title_add_title_end::unit_guid_size() const {
  return _internal_unit_guid_size();
}
inline void title_proto_title_add_title_end::clear_unit_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unit_guid_.Clear();
}
inline ::int32_t title_proto_title_add_title_end::unit_guid(int index) const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_add_title_end.unit_guid)
  return _internal_unit_guid().Get(index);
}
inline void title_proto_title_add_title_end::set_unit_guid(int index, ::int32_t value) {
  _internal_mutable_unit_guid()->Set(index, value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_add_title_end.unit_guid)
}
inline void title_proto_title_add_title_end::add_unit_guid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_unit_guid()->Add(value);
  // @@protoc_insertion_point(field_add:faith.title_proto.title_add_title_end.unit_guid)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& title_proto_title_add_title_end::unit_guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:faith.title_proto.title_add_title_end.unit_guid)
  return _internal_unit_guid();
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_add_title_end::mutable_unit_guid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:faith.title_proto.title_add_title_end.unit_guid)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_unit_guid();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
title_proto_title_add_title_end::_internal_unit_guid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unit_guid_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_add_title_end::_internal_mutable_unit_guid() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.unit_guid_;
}

// int32 template_id = 2;
inline void title_proto_title_add_title_end::clear_template_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.template_id_ = 0;
}
inline ::int32_t title_proto_title_add_title_end::template_id() const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_add_title_end.template_id)
  return _internal_template_id();
}
inline void title_proto_title_add_title_end::set_template_id(::int32_t value) {
  _internal_set_template_id(value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_add_title_end.template_id)
}
inline ::int32_t title_proto_title_add_title_end::_internal_template_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.template_id_;
}
inline void title_proto_title_add_title_end::_internal_set_template_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.template_id_ = value;
}

// int32 result = 3;
inline void title_proto_title_add_title_end::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
}
inline ::int32_t title_proto_title_add_title_end::result() const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_add_title_end.result)
  return _internal_result();
}
inline void title_proto_title_add_title_end::set_result(::int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_add_title_end.result)
}
inline ::int32_t title_proto_title_add_title_end::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void title_proto_title_add_title_end::_internal_set_result(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

// -------------------------------------------------------------------

// title_proto_title_open_title_system_end

// repeated int32 unit_guid = 1;
inline int title_proto_title_open_title_system_end::_internal_unit_guid_size() const {
  return _internal_unit_guid().size();
}
inline int title_proto_title_open_title_system_end::unit_guid_size() const {
  return _internal_unit_guid_size();
}
inline void title_proto_title_open_title_system_end::clear_unit_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unit_guid_.Clear();
}
inline ::int32_t title_proto_title_open_title_system_end::unit_guid(int index) const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_open_title_system_end.unit_guid)
  return _internal_unit_guid().Get(index);
}
inline void title_proto_title_open_title_system_end::set_unit_guid(int index, ::int32_t value) {
  _internal_mutable_unit_guid()->Set(index, value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_open_title_system_end.unit_guid)
}
inline void title_proto_title_open_title_system_end::add_unit_guid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_unit_guid()->Add(value);
  // @@protoc_insertion_point(field_add:faith.title_proto.title_open_title_system_end.unit_guid)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& title_proto_title_open_title_system_end::unit_guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:faith.title_proto.title_open_title_system_end.unit_guid)
  return _internal_unit_guid();
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_open_title_system_end::mutable_unit_guid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:faith.title_proto.title_open_title_system_end.unit_guid)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_unit_guid();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
title_proto_title_open_title_system_end::_internal_unit_guid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unit_guid_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_open_title_system_end::_internal_mutable_unit_guid() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.unit_guid_;
}

// -------------------------------------------------------------------

// title_proto_title_set_title_no_need_see

// repeated int32 unit_guid = 1;
inline int title_proto_title_set_title_no_need_see::_internal_unit_guid_size() const {
  return _internal_unit_guid().size();
}
inline int title_proto_title_set_title_no_need_see::unit_guid_size() const {
  return _internal_unit_guid_size();
}
inline void title_proto_title_set_title_no_need_see::clear_unit_guid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.unit_guid_.Clear();
}
inline ::int32_t title_proto_title_set_title_no_need_see::unit_guid(int index) const {
  // @@protoc_insertion_point(field_get:faith.title_proto.title_set_title_no_need_see.unit_guid)
  return _internal_unit_guid().Get(index);
}
inline void title_proto_title_set_title_no_need_see::set_unit_guid(int index, ::int32_t value) {
  _internal_mutable_unit_guid()->Set(index, value);
  // @@protoc_insertion_point(field_set:faith.title_proto.title_set_title_no_need_see.unit_guid)
}
inline void title_proto_title_set_title_no_need_see::add_unit_guid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_unit_guid()->Add(value);
  // @@protoc_insertion_point(field_add:faith.title_proto.title_set_title_no_need_see.unit_guid)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& title_proto_title_set_title_no_need_see::unit_guid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:faith.title_proto.title_set_title_no_need_see.unit_guid)
  return _internal_unit_guid();
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_set_title_no_need_see::mutable_unit_guid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:faith.title_proto.title_set_title_no_need_see.unit_guid)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_unit_guid();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
title_proto_title_set_title_no_need_see::_internal_unit_guid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.unit_guid_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* title_proto_title_set_title_no_need_see::_internal_mutable_unit_guid() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.unit_guid_;
}

// -------------------------------------------------------------------

// title_proto

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace faith


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // title_2eproto_2epb_2eh
