// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type_def.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "type_def.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace faith {

namespace {

const ::google::protobuf::Descriptor* proto_guid_64_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proto_guid_64_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_type_5fdef_2eproto() {
  protobuf_AddDesc_type_5fdef_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "type_def.proto");
  GOOGLE_CHECK(file != NULL);
  proto_guid_64_descriptor_ = file->message_type(0);
  static const int proto_guid_64_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proto_guid_64, child_a_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proto_guid_64, child_b_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proto_guid_64, child_c_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proto_guid_64, child_d_),
  };
  proto_guid_64_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proto_guid_64_descriptor_,
      proto_guid_64::default_instance_,
      proto_guid_64_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proto_guid_64, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proto_guid_64, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proto_guid_64));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_type_5fdef_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proto_guid_64_descriptor_, &proto_guid_64::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_type_5fdef_2eproto() {
  delete proto_guid_64::default_instance_;
  delete proto_guid_64_reflection_;
}

void protobuf_AddDesc_type_5fdef_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016type_def.proto\022\005faith\"T\n\016proto_guid_12"
    "8\022\017\n\007Child_A\030\001 \001(\r\022\017\n\007Child_B\030\002 \001(\r\022\017\n\007C"
    "hild_C\030\003 \001(\r\022\017\n\007Child_D\030\004 \001(\r", 109);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "type_def.proto", &protobuf_RegisterTypes);
  proto_guid_64::default_instance_ = new proto_guid_64();
  proto_guid_64::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_type_5fdef_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_type_5fdef_2eproto {
  StaticDescriptorInitializer_type_5fdef_2eproto() {
    protobuf_AddDesc_type_5fdef_2eproto();
  }
} static_descriptor_initializer_type_5fdef_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int proto_guid_64::kChildAFieldNumber;
const int proto_guid_64::kChildBFieldNumber;
const int proto_guid_64::kChildCFieldNumber;
const int proto_guid_64::kChildDFieldNumber;
#endif  // !_MSC_VER

proto_guid_64::proto_guid_64()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proto_guid_64::InitAsDefaultInstance() {
}

proto_guid_64::proto_guid_64(const proto_guid_64& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proto_guid_64::SharedCtor() {
  _cached_size_ = 0;
  child_a_ = 0u;
  child_b_ = 0u;
  child_c_ = 0u;
  child_d_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proto_guid_64::~proto_guid_64() {
  SharedDtor();
}

void proto_guid_64::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proto_guid_64::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proto_guid_64::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proto_guid_64_descriptor_;
}

const proto_guid_64& proto_guid_64::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_type_5fdef_2eproto();
  return *default_instance_;
}

proto_guid_64* proto_guid_64::default_instance_ = NULL;

proto_guid_64* proto_guid_64::New() const {
  return new proto_guid_64;
}

void proto_guid_64::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    child_a_ = 0u;
    child_b_ = 0u;
    child_c_ = 0u;
    child_d_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proto_guid_64::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 Child_A = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &child_a_)));
          set_has_child_a();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_Child_B;
        break;
      }

      // optional uint32 Child_B = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Child_B:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &child_b_)));
          set_has_child_b();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_Child_C;
        break;
      }

      // optional uint32 Child_C = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Child_C:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &child_c_)));
          set_has_child_c();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_Child_D;
        break;
      }

      // optional uint32 Child_D = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Child_D:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &child_d_)));
          set_has_child_d();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proto_guid_64::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint32 Child_A = 1;
  if (has_child_a()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->child_a(), output);
  }

  // optional uint32 Child_B = 2;
  if (has_child_b()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->child_b(), output);
  }

  // optional uint32 Child_C = 3;
  if (has_child_c()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->child_c(), output);
  }

  // optional uint32 Child_D = 4;
  if (has_child_d()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->child_d(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proto_guid_64::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint32 Child_A = 1;
  if (has_child_a()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->child_a(), target);
  }

  // optional uint32 Child_B = 2;
  if (has_child_b()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->child_b(), target);
  }

  // optional uint32 Child_C = 3;
  if (has_child_c()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->child_c(), target);
  }

  // optional uint32 Child_D = 4;
  if (has_child_d()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->child_d(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proto_guid_64::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 Child_A = 1;
    if (has_child_a()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->child_a());
    }

    // optional uint32 Child_B = 2;
    if (has_child_b()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->child_b());
    }

    // optional uint32 Child_C = 3;
    if (has_child_c()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->child_c());
    }

    // optional uint32 Child_D = 4;
    if (has_child_d()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->child_d());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proto_guid_64::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proto_guid_64* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proto_guid_64*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proto_guid_64::MergeFrom(const proto_guid_64& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_child_a()) {
      set_child_a(from.child_a());
    }
    if (from.has_child_b()) {
      set_child_b(from.child_b());
    }
    if (from.has_child_c()) {
      set_child_c(from.child_c());
    }
    if (from.has_child_d()) {
      set_child_d(from.child_d());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proto_guid_64::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proto_guid_64::CopyFrom(const proto_guid_64& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proto_guid_64::IsInitialized() const {

  return true;
}

void proto_guid_64::Swap(proto_guid_64* other) {
  if (other != this) {
    std::swap(child_a_, other->child_a_);
    std::swap(child_b_, other->child_b_);
    std::swap(child_c_, other->child_c_);
    std::swap(child_d_, other->child_d_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proto_guid_64::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proto_guid_64_descriptor_;
  metadata.reflection = proto_guid_64_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace faith

// @@protoc_insertion_point(global_scope)
