syntax = "proto2";
package hld;

message achievement_proto
{

	message achievement_one
	{
		repeated int32 achievement_info		= 1;
	}
	message achievement_all
	{
		repeated int32	role_guid				= 1;
		repeated achievement_one achievement_array		= 2;
	}
	message achievement_operate
	{
		optional int32 achievement_id			= 1;
		optional int32 operation_type				= 2;
	}
	message achievement_operate_end
	{
		repeated achievement_one achievement_array		= 1;
		optional int32 operation_type				= 2;
		optional int32 operation_end_state			= 3;
	}
	
	message achievement_finish
	{
		optional int32 achievement_id		= 1;
		optional int32 achievement_state	= 2;
	}
	
	message achievement_all_finish
	{
		optional int32 achievement_reward	= 1;
	}
}