syntax = "proto3";
package faith;

message arena_proto
{
	message get_arena_rank
	{
		repeated int32 role_guid				= 1;
	}
	
	message get_arena_rank_end
	{
		repeated int32 role_guid				= 1;
		int32 arena_rank				= 2;
	}
	
	message	arena_player_info
	{
		repeated int32	role_guid				= 1;
		string role_name				= 2;
		string gs_value				= 3;
		int32  role_template_id		= 4;
		int32  robot_template_id		= 5;
		int32	arena_ranking			= 6;
		int32	military_rank			= 7;	
	}
	
	message get_match_player
	{
		repeated int32 role_guid				= 1;
	}
	
	message get_match_player_end
	{
		repeated arena_player_info match_playrs = 1;
	}
	
	message get_top_three_player
	{
		//啥都不用传
	}
	
	message get_top_three_player_end
	{
		repeated int32 role_guid				= 1;
	}
	
	message req_challenge
	{
		repeated int32 role_guid				= 1;
		repeated int32 target_guid				= 2;
		bool  is_cost_money			= 3;
		int32 target_cur_pos			= 4;
		int32 self_cur_pos			= 5;
	}
	
	message req_challenge_end
	{
		repeated int32 role_guid				= 1;
		repeated int32 target_guid				= 2;
		int32 req_end					= 3;
		int32 new_pos					= 4;
	}
	
	message challenge_over
	{
		repeated int32 role_guid				= 1;
		int32 role_rank				= 2;
		repeated int32 target_guid				= 3;
		int32 target_rank				= 4;
		int32 result					= 5;
	}
	
	message challenge_log
	{
		int64 role_guid				= 1;
		string role_name				= 2;
		int32 role_rank				= 3;
		int64 target_guid				= 4;
		string target_name				= 5;
		int32 target_rank				= 6;
		int32 initiative 				= 7;
		int32 result 					= 8;
		int32 date						= 9;
	}
	message req_get_challenge_log
	{
		repeated int32 role_guid				= 1;
	}
	
	message get_arena_reward
	{
		//什么参数都不用传
	}
	
	message get_arena_reward_end
	{
		int32 reward_template_id		= 1;
		int32 get_result				= 2;
	}
	
	message req_get_challenge_log_end
	{
		int64			role_guid			= 1;
		repeated challenge_log	my_challenge_logs	= 2;
		bool			is_need_clear		= 3;
	}
	
	message req_mopping_remain_times
	{
		
	}
	
	message req_mopping_remain_times_end
	{
		int32			mopping_result	= 1;
		repeated int32			mopping_reward	= 2;
	}
	
	
}

