syntax = "proto2";
package hld;

message convert_proto
{
	message convert_info_all
	{
		repeated	int32	convert_times		= 1;
		repeated	int32	convert_max_times	= 2;
	}

	message convert_info_one
	{
		optional	int32	convert_type	= 1;
		optional	int32	convert_times	= 2;
	}

	message convert_operate
	{
		optional	int32	convert_type	= 1;
		optional	int32	convert_num	= 2;
	}

	message convert_operate_end
	{
		optional	int32	opereate_result	= 1;
		optional	int32	convert_type	= 2;
		optional	int32	convert_num		= 3;
		repeated	int32	convert_reward	= 4;
		optional    int32   is_tip          = 5;
		optional    string  str_exp         = 6;
	}
}
	