syntax = "proto3";
package faith;

message convert_proto
{
	message convert_info_all
	{
		repeated	int32	convert_times		= 1;
		repeated	int32	convert_max_times	= 2;
	}

	message convert_info_one
	{
		int32	convert_type	= 1;
		int32	convert_times	= 2;
	}

	message convert_operate
	{
		int32	convert_type	= 1;
		int32	convert_num	= 2;
	}

	message convert_operate_end
	{
		int32	opereate_result	= 1;
		int32	convert_type	= 2;
		int32	convert_num		= 3;
		repeated	int32	convert_reward	= 4;
		int32   is_tip          = 5;
		string  str_exp         = 6;
	}
}
	

