syntax = "proto3";
package faith;

message cross_ladder
{
	message request_role_info
	{
	}
	
	message send_role_info
	{
		int32	cross_result		= 1;
		repeated int32  data_array			= 2;
		bool	is_online			= 3;
		int32	last_season_ranking = 4;
	}

	message request_sign_up
	{
		bool	is_join				= 1;
	}

	message respond_sign_up
	{
		int32	sign_up_result		= 1;
	}

	message send_match_success
	{
		string opponent_name		    = 1;
		int32	opponent_server_id	    = 2;
		int32	opponent_template_id    = 3;
		int32  opponent_ladder_score   = 4;
		int32  opponent_total_join_num = 5;
		int32  opponent_total_win_num  = 6;
		int32  opponent_last_win_num   = 7;
		string opponent_server_name    = 8;
	}

	message request_buy_join_ticket
	{
		int32	num					= 1;                   
	}

	message respond_buy_join_ticket
	{
		int32	result				= 1;
		int32	ticket_num			= 2;
		int32	can_buy_num			= 3;
	}

	message map_member_info
	{
		string role_name			= 1;
		int32	score				= 2;
	}

	message update_map_game_state
	{
		int32 game_state			= 1;
		int32 state_end_time		= 2;
		int32 cur_turn				= 3;
		int32 winner_guid_A		= 4;
		int32 winner_guid_B		= 5;
		repeated map_member_info member_vec = 6;
	}

	message req_mission_reward
	{
		int32 index				= 1;
	}

	message ret_mission_reward
	{
		int32 index				= 1;
		int32 result				= 2;
	}
	message get_role_competition
	{
	}
	message sync_role_competition
	{
		int32 is_buy = 1;
		int32 season = 2;
		int32 buy_manual_type = 3;
		int32 competition_begin_time = 4;
		int32 competition_end_time = 5;
		int32 level = 6;
		int32 cur_exp = 7;
		repeated int32 normal_reward = 8;
		repeated int32 special_reward = 9;
		int32 cur_state = 10;
		int32 world_level = 11;
	}
	message get_competition_lv_reward
	{
		int32 manual_id = 1;
		int32 manual_type = 2;
	}
	message get_competition_lv_reward_end
	{
		repeated int32 manual_id_list = 1;
		repeated int32 manual_type_list = 2;
		int32 get_type = 3;
	}
	message get_competition_lv_reward_all
	{
	}
	message buy_competition_lv
	{
		int32 level = 1;
	}
	message buy_competition_lv_end
	{
		int32 level = 1;
		int32 cur_exp = 2;
	}
	
	message buy_speical_manual
	{	
		int32 manual_type = 1;
	}
	message buy_speical_manual_end
	{
		int32 is_buy = 1;
		int32 manual_type = 2;
	}

	message send_upgrade_notify
	{
		int32 upgrade_id			= 1;
	}

	message return_to_source_zone
	{
	}
}

