syntax = "proto3";
package faith;
import "login.proto";

message cross_proto
{
	message cross_transfer
	{
		int32			server_id		= 1;
		repeated uint32			token			= 2;
		uint64			role_guid		= 3;
		string			out_ip			= 4;
		string			out_port		= 5;
	}

	message cross_transfer_to_server
	{
		repeated uint32			token			= 1;
		string			account			= 2;
		uint64			role_guid		= 3;
		uint64			map_guid		= 4;
		uint32			war_index		= 5;
		int32			server_id		= 6;
		login_proto.login	login_info		= 7;
	}

	message cross_role_info
	{
		uint64			role_guid		= 1;
		string			role_name		= 2;
		repeated int32			data_array		= 3;		
	}
	
	message cross_info
    {
		int32			cross_type		= 1;
	}	
	message cross_info_end
    {
		int32				cross_result	= 1;
		repeated cross_role_info	role_info_ary	= 2;
	}
	message sign_up
    {
		int32			sign_type		= 1;
		bool			is_join			= 2;
	}	
	message sign_up_end
    {
		int32			sign_type		= 1;
		int32			sign_end		= 2;
	}	
	message begin_war
    {
		uint64			map_guid		= 1;
		int32			war_index		= 2;
		int32			template_id		= 3;
	}
	message join_war
    {
		bool			join_type		= 1;
	}	
	message join_war_end
    {
		int32			join_end		= 1;
	}
	message war_state_end
    {
		int32			war_state		= 1;
		int32			state_time		= 2;
	}
	message war_result
    {
		int32			ladder_score		= 1;
		int32			cross_honor			= 2;
		int32			war_result			= 3;
	}
	message role_pk_log
	{
	}
	message role_pk_log_end
	{
		string			target_name_1		= 1;
		string			target_name_2		= 2;
		string			target_name_3		= 3;
		int32			ladder_score		= 4;
		int32			cross_honor			= 5;
		int32			win_result			= 6;
		
	}
	message role_pk_log_array
	{
		repeated role_pk_log_end	pk_log_array		= 1;
	}
	
	message bossisland_info_all
	{
		int32			cur_server_id		=1;
	}
	
}

