syntax = "proto3";
package faith;
import "db.proto";

message cs2dp_proto
{

    message save_role_starark
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   db_proto.role_starark_db db_data = 4;
	}
	message role_recycle_db
	{
	    int32 e_start_time_1 = 1;
		int32 e_login_state_2 = 2;
		int32 e_prop_state_3 = 3;
		int64 inviter_guid = 4;
		int32 invited_state = 5;
	}
	message save_role_recycle
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_recycle_db db_data = 4;
	}
	
	message role_recycle_task_row
	{
	   repeated int32 data_ary = 1;
	}
	message role_recycle_task_db
	{
	   int32 row_count = 1;
	   repeated role_recycle_task_row row_data = 2;
	}
    message save_role_recycle_task
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_recycle_task_db db_data = 4;
	}
	
	message role_dragontrip_db
	{
	   repeated int32 data_ary = 1;
	}
	
	message save_role_dragontrip
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_dragontrip_db db_data = 4;
	}
	
	message role_phantom_row
	{
	   repeated int32 data_ary = 1;
	}
	message role_phantom_db
	{
	   int32 row_count = 1;
	   repeated role_phantom_row row_data = 2;
	}
    message save_role_phantom
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_phantom_db db_data = 4;
	} 
	message role_chat_record_row
	{
	   int32  pos = 1;
	   string record = 2;
	}
	message role_chat_record_db
	{
	   int32 row_count = 1;
	   repeated role_chat_record_row row_data = 2;
	}
    message save_role_chat_record
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_chat_record_db db_data = 4;
	} 
    message role_oracle_trial_row
	{
	   int64  role_guid = 1;
	   int32  tier_num = 2;
	   int32  customs_state = 3;											
	   int32  reward_stat = 4;
	}
	message role_oracle_trial_db
	{
	   int32 row_count = 1;
	   repeated role_oracle_trial_row row_data = 2;
	}
    message save_role_oracle_trial
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_oracle_trial_db db_data = 4;
	} 
	message role_person_information_db
	{
	   int64 role_guid = 1;
	   int32 infor_state = 2;
	   int32 reward_state = 3;
	   string	gender = 4;
	   string  personalized_signature = 5;
	   int32	birthday_year = 6;
	   int32	birthday_mouth = 7;
	   int32	birthday_day = 8;
	   string	city = 9;
	   string	hometown = 10;
	   string	online_state = 11;
	   repeated	int32	tags = 12;
	}

	message save_role_person_information
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_person_information_db db_data = 4;
	} 
	
	message role_competition_db
	{	
	   int64   role_guid = 1;
	   int32	 is_buy = 2;
	   int32	 buy_manual_type = 3;
	   int32	 point_add_percent = 4;
	   int32	 season = 5;
	   int32	 competition_begin_time = 6;
	   int32	 competition_end_time = 7;
	   int32	 level = 8;
	   int64	 cur_exp = 9;	
	   int32	 need_reset = 10;
	   int64   assist_fight_guid = 11;
	   repeated	 int32   reward_state = 12;
	   int32	 have_type = 13;
	}
	message save_role_competition
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_competition_db db_data = 4;
	} 
	message role_legion_skill_row
	{
	   repeated int32 data_ary  = 1;

	}
	message role_legion_skill_db
	{
	   int32 row_count = 1;
	   repeated role_legion_skill_row row_data = 2;
	}
    message save_role_legion_skill
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_legion_skill_db db_data = 4;
	} 
	
	message role_skytreasure_db
    {
	   int32 skytreasure_layer_num = 1;        
	   int32 skytreasure_pos = 2;               
	   int32 skytreasure_pos_in_array = 3;    	
    }	
	message save_role_skytreasure 
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_skytreasure_db db_data = 4;
	}
	
	message role_harry_record_db 
	{
	   repeated int32 data_ary = 1;
	}
	message save_role_harry_record
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_harry_record_db db_data = 4;
	}
	
	message role_seven_day_goal_row
	{
	   repeated int32 data_ary = 1;
	}
	
	message role_seven_day_goal_db
	{
	   int32 row_count = 1;
	   repeated role_seven_day_goal_row row_data = 2;
	}
	message save_role_seven_day_goal
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_seven_day_goal_db db_data = 4;
	}
	
	message role_passive_skill_row
	{
	   repeated int32 data_ary = 1;
	}
	message role_passive_skill_db
	{
	   int32 row_count = 1;
	   repeated role_passive_skill_row row_data = 2;
	}
	message save_role_passive_skill
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_passive_skill_db db_data = 4;
	}
	
	message role_boss_island_db
	{
	   repeated int32 data_ary = 1;
	}
	
	message save_role_boss_island
	{  
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_boss_island_db db_data = 4;
	}
	
	message role_time_limit_activity_row
	{
	   repeated int32 data_ary  = 1;
	   repeated int32 activity_schedule = 2;
	   string schedule_str = 3;
	   int64 reward_flag = 4;
	}
	message role_time_limit_activity_db
	{
	   int32 row_count = 1;
	   repeated role_time_limit_activity_row row_data = 2;
	}

	message save_role_time_limit_activity
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   bool  is_self_server = 4;
	   role_time_limit_activity_db db_data = 5;
	
	}
	
	message role_gain_treasure_db
	{
	   repeated int32 data_ary = 1;
	}
	message save_role_gain_treasure
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_gain_treasure_db db_data = 4;
	}
	
	message role_logic_db
	{
	   repeated int32 data_ary = 1;
	}	
	message save_role_logic
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_logic_db  db_data = 4;
	}
	
	message role_service_rank_reward_row
	{
	   int32 rank_type = 1;
	   int32 reward_state = 2;
	}
	
	message role_service_rank_reward_db
	{
	   int32 row_count = 1;
	   repeated role_service_rank_reward_row row_data = 2;
	}
	message save_role_service_rank_reward
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_service_rank_reward_db db_data = 4;
	}
	message role_highest_record_db 
	{
	   repeated int64 data_ary = 1;
	}

	message save_role_highest_record
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_highest_record_db db_data = 4;
	}
	
	
	message role_daily_must_do_count_db
	{
	  repeated int32 data_ary = 1;
	}
	message save_role_daily_must_do_count
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_daily_must_do_count_db db_data = 4;
	}
	
	message role_talent_row
	{
	  repeated int32 data_ary = 1;
	}
	message role_talent_db
	{
	   int32 row_count = 1;
	   repeated role_talent_row row_data = 2;  
	}
	message save_role_talent
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_talent_db db_data = 4;   
	}
	
	message role_title_row
	{
	  repeated int32 data_ary = 1;
	}
	message role_title_db
	{
	   int32 row_count = 1;
	   repeated role_title_row row_data = 2;  
	}
	
	message save_role_title
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_title_db db_data = 4;   
	}
	
	
	message role_active_degree_db
	{
	  repeated int32 data_ary = 1;
	}
	
	message save_role_active_degree
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_active_degree_db db_data = 4;   
	}
	
	message role_welfare_db
	{
	  repeated int32 data_ary = 1;
	}
	
	message save_role_welfare
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_welfare_db db_data = 4;   
	}
	
	message role_convert_db
	{
	
	   repeated int32 data_ary = 1;
	}
	
	message save_role_convert
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_convert_db db_data = 4;  
	}
	
	
	message role_yesterday_must_do_remain_row
	{
	   int64		role_guid = 1;
	   int32		role_exp_level_yesterday = 2;
	   int32		save_date = 3;
	   int32		role_vip_level_yesterday = 4;
	   int32       distance_today_day_count = 5;
	   int32       role_arena_rank = 6;
	   repeated int32       data_ary = 7;
	}
	
	message role_yesterday_must_do_remain_db
	{
	   int32 row_count = 1;

	   repeated role_yesterday_must_do_remain_row row_data = 2;
	}
	message save_role_yesterday_must_do_remain
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_yesterday_must_do_remain_db db_data = 4; 
	}
	
	message role_worship_row 
	{
	   	int32		ranking_index = 1;
		int64      target_guid = 2;
	}
	message role_worship_db
	{
	  int32 row_count = 1;
	  repeated role_worship_row row_data = 2;
	}
	message save_role_worship
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_worship_db db_data =4; 
	}
	
	message role_tinder_db
	{
	   repeated int32 data_ary = 1;
	}
	
	message save_role_tinder
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_tinder_db db_data =4;
	}
	
	message role_pokedex_row
	{
	   repeated int32 data_ary = 1;
	   repeated int32 collect_num = 2;
	}
	message role_pokedex_db
	{  
	  int32 row_count = 1;
	  repeated role_pokedex_row row_data = 2;
	}
	message save_role_pokedex
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_pokedex_db db_data =4;
	}
	
	message role_achievement_row
	{
	   repeated int32 data_ary = 1;
	}
	
	message role_achievement_db
	{
	  int32 row_count = 1;
	  repeated role_achievement_row row_data = 2; 
	}
	
	message save_role_achievement
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_achievement_db db_data =4;
	}
	
	
	message role_special_name_db
	{
	   repeated int32 data_ary = 1;
	}
		
	message save_role_special_name
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_special_name_db db_data =4;
	}
	
	message role_service_goal_row
	{
	  repeated int32 data_ary = 1;
	}
	message role_service_goal_db
	{
	  int32 row_count = 1;
	  repeated role_service_goal_row row_data = 2; 
	}
	
	message save_role_service_goal
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_service_goal_db db_data =4;
	}
	
    message role_map_record_row
	{
	  repeated int32 data_ary = 1;
	}
	
	message role_map_record_db
	{
	  int32 row_count = 1;
	  repeated role_map_record_row row_data = 2; 
	}
	
	message save_role_map_record
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;
	   role_map_record_db db_data =4;
	}
	
	
	message role_goods_row
	{
	  repeated int32 data_ary = 1;
	}
	
	message role_goods_db
	{
	  int32 row_count = 1;
	  repeated role_goods_row row_data = 2; 
	}
	
	
	message save_role_goods
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_goods_db db_data =4;
	}
	
	message role_mission_row
	{
	  repeated int32 data_ary = 1;
	}
	
	message role_mission_db
	{
	  int32 row_count = 1;
	  repeated role_mission_row row_data = 2; 
	}
	
	message save_role_mission
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_mission_db db_data =4;
	}
	
	
	message role_belief_row
	{
	  repeated int32 data_ary = 1;
	}
	
	message role_belief_db
	{
	  int32 row_count = 1;
	  repeated role_belief_row row_data = 2; 
	}
	
	message save_role_belief
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_belief_db db_data =4;
	}
	message role_money_db
	{
	   repeated int64 cur_data_ary = 1;
	   repeated int64 all_data_ary = 2;
	   repeated int64 cost_data_ary = 3;
	
	}
	message save_role_money
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_money_db db_data =4;
	}
	message role_time_db
	{
	   repeated int64 data_ary = 1;
	}
	message save_role_time
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_time_db db_data =4;
	}

	message role_info_db
	{
	   int64  role_guid = 1;
	   string account = 2;
	   string role_name = 3;
	   string role_appearance = 4;
	   string role_first_kill_ary = 5;
	   int64  map_guid = 6;
	   repeated int64  data_i64_ary = 7;
	   repeated int32  data_ary = 8;
	}
	message save_role_info
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_info_db db_data =4;
	}
	
	message role_att_db
	{
	   repeated int64 data_ary = 1;
	   repeated float attack_att = 2;
	
	}
	message save_role_att
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 save_type_ex = 3;   
	   role_att_db db_data =4;
	}
	
	message save_recycle_invited
	{
	   int64 role_guid = 1;
	   int64 target_guid = 2;
	}
	
	
	message role_guide_db
	{
	  int32 guide_trigger_id = 1;
	  int32 state = 2;
	}
	
	
	message save_role_guide
	{
	  int64 role_guid = 1;
	  int32 unit_array_index = 2;
	  int32 save_type_ex = 3;  
	  role_guide_db db_data = 4; 
	}
	
	message save_role_db_data
	{
	  int64 role_guid = 1;
	  int32 unit_array_index = 2;
	  int32 save_type_ex = 3;
	  bytes db_data = 4;
	}
}

