syntax = "proto2";
package hld;
import "st.proto";

message cs2ws_proto
{
   
    message send_red_package
	{
	  optional	 int64	 sender_guid = 1;
	  optional	 int32	 red_package_template_id = 2;
	  optional	 string	 send_text = 3;
	  optional	 string	 sender_name = 4;
	};
	
	message  get_red_package
	{
	   optional	int64	 role_guid = 1;
	   optional	int64	 red_package_guid = 2;
	   optional	string	 role_name = 3;
	};
	
	message req_get_arena_rank 
	{
	  optional int64 role_guid = 1;
	};
	
	message req_challenge_msg 
	{
	  optional	int64 role_guid = 1;
	  optional  int64 target_guid = 2;
	  optional  int32 cost_money_type = 3;
	  optional  int32 cost_money_num = 4;
	  optional  int32 target_cur_pos = 5;
	  optional  int32 self_cur_pos = 6;
	};
	
	message req_choose_list 
	{
	  optional  int64 role_guid = 1;
	  optional  int32 cur_pos = 2;
	};
	
	
	message first_three 
	{
	  optional  int64 role_guid = 1;
	};
	
	message chellenge_over 
	{
		optional int64   role_guid = 1;
		optional int64   target_guid = 2;
		optional st_proto.st_player_arena_rank   role_info = 3;
		optional int32   chellenge_result = 4;
		optional int32   target_rank = 5;
	};
	
	message arena_sync_gs_value 
	{
		optional int64   role_guid = 1;
		optional int32   cur_pos = 2;
		optional int64   gs_value = 3;
	};
	
	message auction_add_item_into_db 
	{
	    optional st_proto.st_unit_info	role_info = 1;
		optional st_proto.st_auction_info	auction_info = 2;
		optional int64				old_item_guid = 3;
		optional st_proto.st_login_fixed_data	third_info = 4;
	
	};
	
	message set_best_record 
	{
	   optional	int32 map_template_id = 1;
	   optional	st_proto.st_single_map_record record = 2;
	};



}