syntax = "proto3";
package faith;
import "st.proto";

message cs2ws_proto
{
   
    message send_red_package
	{
	  int64	 sender_guid = 1;
	  int32	 red_package_template_id = 2;
	  string	 send_text = 3;
	  string	 sender_name = 4;
	};
	
	message  get_red_package
	{
	   int64	 role_guid = 1;
	   int64	 red_package_guid = 2;
	   string	 role_name = 3;
	};
	
	message req_get_arena_rank 
	{
	  int64 role_guid = 1;
	};
	
	message req_challenge_msg 
	{
	  int64 role_guid = 1;
	  int64 target_guid = 2;
	  int32 cost_money_type = 3;
	  int32 cost_money_num = 4;
	  int32 target_cur_pos = 5;
	  int32 self_cur_pos = 6;
	};
	
	message req_choose_list 
	{
	  int64 role_guid = 1;
	  int32 cur_pos = 2;
	};
	
	
	message first_three 
	{
	  int64 role_guid = 1;
	};
	
	message chellenge_over 
	{
		int64   role_guid = 1;
		int64   target_guid = 2;
		st_proto.st_player_arena_rank   role_info = 3;
		int32   chellenge_result = 4;
		int32   target_rank = 5;
	};
	
	message arena_sync_gs_value 
	{
		int64   role_guid = 1;
		int32   cur_pos = 2;
		int64   gs_value = 3;
	};
	
	message auction_add_item_into_db 
	{
	    st_proto.st_unit_info	role_info = 1;
		st_proto.st_auction_info	auction_info = 2;
		int64				old_item_guid = 3;
		st_proto.st_login_fixed_data	third_info = 4;
	
	};
	
	message set_best_record 
	{
	   int32 map_template_id = 1;
	   st_proto.st_single_map_record record = 2;
	};



}

