syntax = "proto3";
package faith;

message db_proto
{
	message role_starark_db
	{
	   repeated int32  data_ary = 1;
	   string body = 2;
	}
    message role_proc_recycle_invited_row
    {
	   int64  role_guid = 1;
	   int32  level = 2;
	   int32  head_id= 3;
	   int32  class_type =4;
	   string invited_name = 5;	
    }
    message role_proc_recycle_invited_db
    {
	   int32 row_count = 1;
	   repeated role_proc_recycle_invited_row row_data = 2;
    }

    message role_event_db
    {
	   repeated int64  data_ary = 1;
    }
	
	message item_info_db
	{
	   int64 item_guid = 1;
	   repeated int32 data_ary = 2;
	   string param_str = 3;
	}

    message auction_row
    {
	   int64  seller_guid = 1;
	   string seller_name = 2;
	   int64  buyer_guid = 3;
	   string buyer_name = 4;
	   int32  trade_type = 5;
	   int32  seller_vip_level = 6;
	   int32  auction_type = 7;
	   int32  auction_sub_type = 8;
	   int32  item_color = 9;
	   int32  quality_level = 10;
	   int32  class_limit = 11;
	   string item_name = 12;
	   int64  sell_time = 13;
	   int64  deal_time = 14;
	   int32  sell_money_type = 15;
       int64  sell_total_money = 16;
	   int64  sell_single_money =17;
	   int64  cur_bid_money = 18;
	   int32  is_show = 19;
	   int32  add_time = 20;
	   int32  is_sky_order = 21;
	   int64  show_guid = 22;
	   item_info_db item_info = 23;
    }
    message auction_db
    {
	    int32 row_count = 1;
		repeated auction_row row_data = 2;
    }
	
	message role_first_time_do_row
	{
	   int32 do_type = 1;
	}

    message role_first_time_do_db
    {
	    int32 row_count = 1;
		repeated role_first_time_do_row row_data = 2;
    }

    message load_role_guide_row
    {
	    int32 guide_trigger_id = 1;
		int32 state = 2;
    }
    message load_role_guide_db
    {
	    int32 row_count = 1;
		repeated load_role_guide_row row_data = 2;
    }

    message role_mail_row
    {
	    int64  mail_guid = 1;
		repeated int32  data_ary = 2;
		string text_contents = 3;
		string sender_name = 4;
		string mail_title =5;
    }

    message role_mail_db
    {
	    int32 row_count = 1;
		repeated role_mail_row row_data = 2;
    }
	
    message role_mail_item_db
    {
	    int32 row_count = 1;
		repeated item_info_db row_data = 2;
    }	
 
}

