syntax = "proto3";
package faith;
import "db.proto";

message dp2cs_proto
{
    message load_role_starark
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   db_proto.role_starark_db db_data = 4;
	}
	
	message load_role_skytreasure
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   int32 row_count = 3;
	   bytes db_data = 4;
	}
	
    message load_role_recycle
    {
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   
	   bytes db_data = 3;
    }
	
	message load_role_recycle_task
    {
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   bytes db_data = 3;
    }
	
	
	
	message load_role_db_data
	{
	   int64 role_guid = 1;
	   int32 unit_array_index = 2;
	   bytes db_data = 3;
	}
	
}

