syntax = "proto3";
package faith;
import "st.proto";

message dp2s_proto
{
	message test_dp2s_test_msg
	{
		int32 role_guid				= 1;
	}
	
	message dp2ws_get_game_info
	{
		int32 server_id				= 1;
		int32 begin_time				= 2;
		repeated int32 server_info_arr			= 3;
		repeated int32 gm_commond_arr			= 4;	
	}
	
	message s_unit_info
	{
		int64 role_guid				= 1;
		string account				= 2;
		string role_name			= 3;
		string role_appearance			= 4;	
		string role_first_kill_npc_id_arr	= 5;
		int64 map_guid				= 6;
		repeated int64 data_i64_ary				= 7;
		repeated int32 data_ary				= 8;
	}
	
	message dp2ws_load_character
	{
		s_unit_info role_info				= 1;
		repeated int32 ws_data_ary					= 2;
		int32 is_login					= 3;
		int32 is_send_chat				= 4;
		int32 worship_value			= 5;	
		int32 eresult					= 6;		
	}
	
	message s_arena_rank
	{
		int32 rank_pos				= 1;
		int64 role_guid				= 2;
		string role_name			= 3;
		int64 gs_value			= 4;	
		int32 role_template_id	= 5;
		int32 robot_template_id				= 6;
		int32 military_rank_level				= 7;
		int32 vip_level				= 8;
		string game_channel			= 9;
	}
	
	message s_arena_rank_all
	{
		int32 row_count = 1;
		repeated s_arena_rank load_data					= 2;	
	}
	
	message dp2ws_load_arena_rank
	{
		int32 start_index				= 1;
		s_arena_rank_all load_data_all	= 2;	
	}
	
	message dp2ws_create_robot
	{
		int32 is_create				= 1;
	}
	
	message dp2ws_arena_load_finish
	{
		int32 is_finish				= 1;
	}
	
	message s_ranking_player_info
	{
		int64 role_guid				= 1;	
		string role_name				= 2;	
		int64 ranking_type				= 3;
		int64 ranking_value				= 4;
		int64 save_time				= 5;
		int64 supporting_guid				= 6;
		string supporting_name				= 7;
		int32 vip_level				= 8;
		int32 peak				= 9;
		int32 server_id				= 10;	
		string game_channel				= 11;
		int64 standby_parameter				= 12;		
	}
	
	message s_ranking_top_info
	{
		repeated s_ranking_player_info data_ary				= 1;
		int32 data_num			= 2;
	}
	
	message dp2ws_load_all_ranking_info
	{
		int32 ranking_type			= 1;
		s_ranking_top_info data_info			= 2;		
	}
	
	message dp2ws_load_one_ranking_info
	{
		int64 sender_guid			= 1;
		int32 ranking_type			= 2;
		int32 worship_add_value			= 3;
		int32 worship_type			= 4;
		int32 end_result			= 5;	
		s_ranking_player_info data_info	= 6;		
	}
	
	message dp2ws_get_worship_value_end
	{
		int64 sender			= 1;
		s_ranking_player_info target			= 2;
		bool is_load			= 3;
	}
	
	message s_service_rank_player_info
	{
		int64 role_guid			= 1;
		int32 rank_type			= 2;
		int32 role_num			= 3;
	}
	
	message s_service_rank_info
	{
		repeated s_service_rank_player_info data_ary			= 1;
		int32 data_num				= 2;
	}
	
	message dp2ws_load_all_service_rank_info
	{
		s_service_rank_info all_data			= 1;
	}
	
	message dp2ws_load_last_server_list
	{
		int32 server_id			= 1;
		string last_server_list			= 2;
	}
	
	message dp2ws_gm_set_result
	{
		int32 listen_port			= 1;
		int64 handle_index			= 2;
		int32 result_code			= 3;
		string result_msg			= 4;
	}
	
	message dp2ws_save_recharge
	{
		string order_id			= 1;
		int64 role_guid			= 2;
		int32 game_goods_id			= 3;
		float pay_price			= 4;
		int32 success			= 5;
		int32 order_num			= 6;
		int32 payment_type			= 7;
		int32 direct_diamond			= 8;
		int64 client_uid			= 9;
		string order_token			= 10;
	}
	
	message dp2ws_send_recharge_end_result
	{
		int32 result_type			= 1;
		int64 order_num			= 2;
		int32 payment_type			= 3;
		int32 goods_id			= 4;
		int32 direct_diamond			= 5;
		int64 role_guid			= 6;
		string order_id			= 7;
	}
	
	message dp2ws_query_server_info_gm
	{
		int32 acc_num			= 1;
		int32 role_num			= 2;
	}
	
	message dp2ws_gm_change_account
	{
		int32 change_res			= 1;
		int32 listen_port			= 2;
		int64 handle_index			= 3;
	}
	
	message dp2ws_gm_get_role_info_arr
	{
		repeated s_unit_info role_info			= 1;	
		int32 data_num	= 2;
	}
	
	message dp2ws_gm_get_role_info
	{
		int32 listen_port			= 1;
		int64 handle_index			= 2;
		dp2ws_gm_get_role_info_arr role_info_arr = 3;
		int32 check_type 			= 4;
	}
	
	message dp2ws_gm_modify_role_info
	{
		int64 role_guid			= 1;
		int32 listen_port			= 2;
		int64 handle_index			= 3;
	}
	
	message s_red_package_base
	{
		int64		    red_package_guid = 1;
		int32			red_package_template_id = 2;
		int64			sender_guid = 3;
		int64			create_time = 4;
		string			sender_name = 5;
		string			text = 6;
		int32			sender_vip_level = 7;
		int32			remain_times = 8;
		int32			remain_money_num = 9;
	}; 
	
	
	message load_red_package_end 
	{
		int32	   data_num           = 1;
	    repeated s_red_package_base	          red_package_list = 2;

	};
	
	
	message s_red_package_receiver
	{
		int64	red_package_guid  = 1;
		int64	receiver_guid  = 2;
		string	role_name = 3;
		int32	money_num = 4;
	}

	message load_red_package_receiver_end 
	{
		int32		data_num  = 1;
		repeated  s_red_package_receiver	receiver_list = 2;
		
	};
	
	message aution_time_out_end 
	{
		int32		data_num = 1;
		repeated st_proto.st_auction_info	data_info = 2;
	
	};
	
	message auction_req_share_list_end 
	{
		int64		    buyer_guid = 1;
	    int32		    money_type = 2;
		int32			money_value = 3;
        int32			item_template_id = 4;
		int32			data_num = 5;
		repeated st_proto.st_auction_share_info	data_info = 6;
	
	};
	
	message auction_clear_old_item_end 
	{
		int32			data_num = 1;
		repeated st_proto.st_auction_info	data_info = 2;
	
	};
	
	message auction_find_bid_target_end 
	{
		int64	role_guid = 1;
		int64	item_guid = 2;
		int32	price_money_type = 3;
		int32	price_money_value = 4;
		st_proto.st_auction_info	auction_info = 5;
	};
	
	message auction_sell_end 
	{
		int32	    operate_result = 1;
		st_proto.st_auction_info		info = 2;
		st_proto.st_unit_info			role_info = 3;
		bool				is_add_to_log = 4;
		st_proto.st_login_fixed_data	third_info = 5;

	};
	
	message auction_cancel_sell 
	{
		int64		role_guid = 1;
		st_proto.st_auction_info	auction_info = 2;

	};
	
	message auction_find_buy_target_end 
	{
		int64   role_guid = 1;
		int64   item_guid = 2;
		st_proto.st_auction_info auction_info = 3;
	};
	
	message auction_show_sell_end 
	{
		int32 result = 1;
		st_proto.st_auction_info data_info = 2;

	};
	
	message load_all_gain_treasure_record_info 
	{
		int32		data_num = 1;
		repeated  st_proto.st_gain_treasure_record_info_one_db	record_infos = 2;
	};
	
	message load_all_best_record 
	{
		int32		db_record_num = 1;
		repeated st_proto.st_db_best_record		db_record_list = 2;
	}; 
	
	message load_big_player_end
	{
		repeated  st_proto.st_big_player_db		data_info = 1;
		
	};
	
	
	
	
	
}

