syntax = "proto3";
package faith;

message dragontrip_proto
{

	message dragontrip_all
	{
	    repeated int32  data_ary           = 1;
		repeated int32  reward_ary         = 2;
		repeated int32  params             = 3;
	}
	
	message dragontrip_operate
	{
		int32 oper_type			= 1;
		int32 oper_param           = 2;
	}
	
	message dragontrip_operate_end
	{
		int32 oper_type           = 1;
		int32 result	           = 2;
		int32 roll_num            = 3;
		int32 item_id             = 4;
		int32 item_num            = 5;
		repeated dragontrip_item_info item_list		   = 6;
	}
	
	message dragontrip_item_info
	{
		int32 item_id             = 1;
		int32 item_num            = 2;
		int32 end_pos             = 3;
	}
	
}

