syntax = "proto2";
package hld;
 
enum e_error_code
{
	e_error_code_success								= 1;//成功		
	e_error_code_success_create_account					= 2;//成功-创建账号
	e_error_code_success_queue_login					= 3;//成功进入排队
	e_error_code_success_queue_complete					= 4;//排队排到了
	
//通用错误
	e_error_code_no_param								= 1001;//参数错误
	e_error_code_fast									= 1002;//操作过快
	e_error_code_no_template							= 1003;//模板找不到
	e_error_code_template_param							= 1004;//模板参数配置错误
	e_error_code_no_money								= 1005;//货币不足
	e_error_code_no_item								= 1006;//物品不足
	e_error_code_db_error								= 1007;//db错误	
	e_error_code_repeated								= 1008;//重复操作
	e_error_code_dead									= 1009;//死亡状态下无法操作
	e_error_code_no_component							= 1010;//没有组件
	e_error_code_state_error							= 1011;//当前状态不允许操作
	e_error_code_no_data								= 1012;//查找的数据不存在
	
//登录错误
	e_error_code_login_password_error					=1000000;//密码错误
	e_error_code_login_repeat_request					=1000001;//重复请求
	e_error_code_login_invalid_bi						=1000002;//SDK封号
	e_error_code_login_invalid_token					=1000003;//token无效
	e_error_code_login_invalid_account					=1000004;//账号无效
	e_error_code_login_server_internal					=1000005;//服务器错误
	e_error_code_login_aleady_logined					=1000006;//已登录
	e_error_code_login_captcha_error					=1000007;//秘钥错误
	e_error_code_login_login_queue_full					=1000008;//排队人数已满
	e_error_code_login_account_disable					=1000009;//账号不可用
	e_error_code_login_invalid_reconnect_account		=1000010;//重连无效
	e_error_code_login_gate_login						=1000011;//跨服Gate登录失败
	e_error_code_login_begin_time						=1000012;//服务器没到开服时间
	e_error_code_login_ban								=1000013;//游戏服务器封号
	e_error_code_login_login_full						=1000014;//登陆人数满
	e_error_code_login_online_time_limit				=1000015;//防沉迷在线时间限制
	e_error_code_login_online_duration_over				=1000016;//防沉迷在线时长超时
	
//进入游戏
	e_error_code_enter_server_internal_error			=1001000;//防沉迷在线时长超时
	e_error_code_enter_area_not_exist					=1001001;//进入的区域不存在
	e_error_code_enter_no_allow							=1001002;//限制登录
	e_error_code_enter_error_server_id					=1001003;//进入到错误的服务器
	e_error_code_enter_only_create						=1001004;//只能创建，不能进入
	
//进入地图
	e_error_code_map_max_players						=1002000;// 副本人数已满
	e_error_code_map_map_not_found						=1002001;// 地图没有找到
	e_error_code_map_too_many_instances					=1002002;// 短时间内进入副本次数太多
	e_error_code_map_in_combat							=1002003;// 你处于战斗状态不能进入新的场
	e_error_code_map_low_exp_level						=1002004;// 你的人物等级太低
	e_error_code_map_low_force							=1002005;// 所需势力声望不满
	e_error_code_map_no_item							=1002006;// 所需物品不存在
	e_error_code_map_no_buff							=1002007;// 所需buff不存在
	e_error_code_map_no_rewarded_quest					=1002008;// 所需任务没有完成
	e_error_code_map_in_stall							=1002009;// 摆摊状态不让传
	e_error_code_map_dead								=1002010;// 死亡状态不让传
	e_error_code_map_tran_delete_all_buff				=1002011;// 传送删除buff
	e_error_code_map_no_job								=1002012;// 职业不对
	e_error_code_map_sex_not_right						=1002013;// 性别不对
	e_error_code_map_ip_limit							=1002014;// ip限制
	e_error_code_map_instance_full						=1002015;// 副本数量达到上限
	e_error_code_map_enter_times_hot					=1002016;// 单位时间内进入太多次
	e_error_code_map_finish_times_hot					=1002017;// 单位时间内完成太多次
	e_error_code_map_not_in_team						=1002018;// 不在队伍中，不能进入
	e_error_code_map_db_operationing					=1002019;// 数据正在操作，不能切换地
	e_error_code_map_flying								=1002020;// 正在飞行，不能地
	e_error_code_map_mt									=1002021;// 你的转生
	e_error_code_map_enter_scene						=1002022;// 进入场景失败，重制坐标，请重新登录
	e_error_code_map_init_map_err						=1002023;//初始化地图失败
	e_error_code_map_enter_map_cd						=1002024;// 进入地图cd中
	e_error_code_map_pk_king_not_begin					=1002025;// PK之王活动还没有开始
	e_error_code_map_pk_king_no_eligibility				=1002026;// 没有PK之王决赛的参赛资格
	e_error_code_map_broken_sky_not_begin				=1002027;// 破碎虚空活动还没开始
	e_error_code_map_broken_sky_game_over				=1002028;// 破碎虚空活动已经结束
	e_error_code_map_cross_server_pk_not_begin			=1002029;//跨服职业竞技没开始
	e_error_code_map_cross_server_pk_session_error		=1002030;//不存在该玩家
	e_error_code_map_cross_server_pk_end				=1002031;//活动已结束
	e_error_code_map_cross_server_pk_not_start			=1002032;//跨服职业竞技没开放
	e_error_code_map_cross_server_world_boss_begin 		=1002033;//跨服世界boss活动没有开始
	e_error_code_map_cross_server_world_boss_end   		=1002034;//跨服世界boss活动已经结束
	e_error_code_map_cross_server_world_boss_not_start	=1002035;//跨服世界boss没有开放
	e_error_code_map_cross_city_war_not_begin			=1002036;//没到活动时间
	e_error_code_map_cross_city_war_map_error			=1002037;//地图有错
	e_error_code_map_cross_city_war_map_not_find		=1002038;//地图guid找不到
	e_error_code_map_cross_city_war_map_end				=1002039;//该城战地图已经结束
	e_error_code_map_cross_territory_war_not_begin		=1002040;//没到活动时间
	e_error_code_map_no_territory_war_qualification		=1002041;//没有资格参加
	e_error_code_map_pk_king_ready_end					=1002042;//Pk之王准备时间已结束
	e_error_code_map_pk_king_ready_not_join_time		=1002043;//Pk之王可进入时间已过
	e_error_code_map_attack_city_game_not_open			=1002044;//活动还没有开启
	e_error_code_map_attack_city_game_not_begin			=1002045;//活动还没有开始
	e_error_code_map_attack_city_map_not_join			=1002046;//地图创建中请稍后
	e_error_code_map_attack_city_legion_not_join		=1002047;//军团无法参与
	e_error_code_map_attack_city_player_max				=1002048;//地图玩家已满
	e_error_code_map_attack_city_game_end				=1002049;//活动已结束
	e_error_code_map_map_locked							=1002050;//地图前置条件
	e_error_code_map_lack_of_money						=1002051;//传送资金不足
	e_error_code_map_lack_of_times						=1002052;//进入次数不足
	e_error_code_map_player_level_not_enough			=1002053;//玩家等级不足
	e_error_code_map_player_vip_level_not_enough		=1002054;//玩家VIP等级不足
	e_error_code_map_cur_map_cant_ready					=1002055;//当前地图无法准备传送
	e_error_code_map_func_condition_lock				=1002056;//地图任务解锁
	e_error_code_map_item_num_not_enough				=1002057;//进入地图所需物品不足	
	
//物品操作
	e_error_code_item_can_not_use						= 1003001;	//不能使用
	e_error_code_item_no_item							= 1003002;	//没有该物品
	e_error_code_item_no_target							= 1003003;	//nTargetRoleID没有找到
	e_error_code_item_create_item						= 1003004;	//创建物品失败
	e_error_code_item_spelling							= 1003005;	//正在执行另一个动作
	e_error_code_item_cd								= 1003006;	//cd未好
	e_error_code_item_in_combat							= 1003007;	//战斗状态下无法使用
	e_error_code_item_quest								= 1003008;	//任务物品使用错误
	e_error_code_item_target							= 1003009;	//目标错误
	e_error_code_item_regin								= 1003010;	//没有在指定区域内使用
	e_error_code_item_level								= 1003011;	//未满足等级要求
	e_error_code_item_class								= 1003012;	//未满足职业要求
	e_error_code_item_camp								= 1003013;	//未满足阵营要求
	e_error_code_item_race								= 1003014;	//未满足种族要求
	e_error_code_item_gender							= 1003015;	//未满足性别要求
	e_error_code_item_spell_learn						= 1003016;	//不能学习该技能
	e_error_code_item_specialty_learn					= 1003017;	//不能学习该生活技能
	e_error_code_item_pet_spell_learn					= 1003018;	//指定兵魂不能学习该技能
	e_error_code_item_compse_learn						= 1003019;	//不能学习配方
	e_error_code_item_not_identified					= 1003020;	//物品需要鉴定后才能使用
	e_error_code_item_not_enough_item					= 1003021;	//所需合成物品缺少
	e_error_code_item_target_too_far					= 1003022;	//目标太远
	e_error_code_item_cannot_open_gift_bag				= 1003023;	//背包满无法打开礼品包
	e_error_code_item_cannot_use_qust_point_bag			= 1003024;	//任务点数达到上限无法增加任务点
	e_error_code_item_cannot_use_prestige_bag			= 1003025;	//势力声望达到最大值无法增加
	e_error_code_item_cannot_use_presting_bag			= 1003026;	//无法完成物品合成操作，背包空间不足
	e_error_code_item_no_catch_pet_skill				= 1003027;	//还没有学习吸魂技能不能使用兵魂栏位扩充道具
	e_error_code_item_all_pet_slot_opened				= 1003028;	//所有的兵魂栏位已被全部打开
	e_error_code_item_error_metemp_sychosis_times		= 1003029;	//错误的转生次数
	e_error_code_item_spell_learned						= 1003030;	//已经学会了
	e_error_code_item_success_hc						= 1003031;	//使用道具合成
	e_error_code_item_pk_cannot_use_item1				= 1003032;	//此物品不需使用
	e_error_code_item_item_is_using						= 1003033;	//物品正在使用中，操作失败
	e_error_code_item_invalid							= 1003034;	//原堆物品不合法
	e_error_code_item_new_position						= 1003035;	//新位置错误
	e_error_code_item_bag_capacity						= 1003036;	//背包容量变化非法
	e_error_code_item_never_can_be_discard				= 1003037;	//物品不能销毁
	e_error_code_item_ca_not_enough						= 1003038;	//战力值不足
	e_error_code_item_noneed_item						= 1003039;	//使用失败，缺少必要的物品
	e_error_code_item_script_trigger_error				= 1003040;	//脚本函数返回错误
	e_error_code_item_peer_level						= 1003041;	//贵族等级不足
	e_error_code_item_vip_level							= 1003042;	//vip等级不足
	e_error_code_item_yuanbao							= 1003043;	//玩家元宝不足
	e_error_code_item_yuanbao_bind						= 1003044;	//玩家绑定元宝不足
	e_error_code_item_inherit							= 1003045;	//传承失败
	e_error_code_item_advance							= 1003046;	//进阶失败
	e_error_code_item_upgrade							= 1003047;	//强化失败不降级
	e_error_code_item_upgrade_lower1					= 1003048;	//强化失败降1级
	e_error_code_item_upgrade_lower2					= 1003049;	//强化失败降2级
	e_error_code_item_upgrade_lower3					= 1003050;	//强化失败降3级
	e_error_code_item_upgrade_lower4					= 1003051;	//强化失败降4级
	e_error_code_item_upgrade_lower5					= 1003052;	//强化失败降5级
	e_error_code_item_item_use_in_cd            		= 1003053;	//道具CD中，无法使用
	e_error_code_item_money								= 1003054;	//金币不足
	e_error_code_item_jewel								= 1003055;	//钻石不足
	e_error_code_item_full_level						= 1003056;	//等级已满
	e_error_code_item_matirial_not_enough				= 1003057;	//素材不足
	e_error_code_item_godassembly						= 1003058;	//神装再造失败
	e_error_code_item_bag_full                 			= 1003059;	//背包已满
	e_error_code_item_composit							= 1003060;	//合成失败
	e_error_code_item_add_star_critical					= 1003061;	//升星暴击
	e_error_code_item_shape_wing_cant_up				= 1003062;	//外形翅膀不能升级
	e_error_code_item_chant_show_unactivate_wing		= 1003063;	//不能显示未激活的翅膀
	e_error_code_item_had_this_shape_wing				= 1003064;	//已拥有此外形翅膀
	e_error_code_item_mount_class_not_reach				= 1003065;	//坐骑阶数不足
	e_error_code_item_pound								= 1003066;	//元素粉末不足
	e_error_code_item_equip_same_type					= 1003067;	//元素之心装备相同类型
	e_error_code_item_equip_full						= 1003068;	//装备位置已满
	e_error_code_item_element_heart_group_too_high		= 1003069;	//元素之心抽取组过高
	e_error_code_item_element_one_refine_no_time		= 1003070;	//元素之心提炼次数不足，1次
	e_error_code_item_element_ten_refine_no_time		= 1003071;	//元素之心提炼次数不足，10次
	e_error_code_item_godassembled						= 1003072;	//神装合成失败
	e_error_code_item_spirit_promote_max_level			= 1003073;	//精灵升格达到上限
	e_error_code_item_spirit_promote_not_enough			= 1003074;	//精灵升格材料不足
	e_error_code_item_break_will_active					= 1003075;	//心魔意志已经激活过了
	e_error_code_item_break_will_no_level				= 1003076;	//心魔意志激活等级不足
	e_error_code_item_awaken_fetter_no_level			= 1003077;	//觉醒羁绊需要等级不足
	e_error_code_item_invalid_player_state				= 1003078;	//当前玩家状态不能进行使用物品的操作
	e_error_code_item_invalid_item_template				= 1003079;	//物品模板数据无效
	e_error_code_item_invalid_prop_template				= 1003080;	//道具模板数据无效
	e_error_code_item_invalid_use_num					= 1003081;	//使用数量非法(为负数或比物品的当前数量更多)
	e_error_code_item_class_type_limit					= 1003082;	//种族不符合物品使用要求
	e_error_code_item_level_limit						= 1003083;	//等级不符合物品使用要求
	e_error_code_item_in_cd								= 1003084;	//物品还在使用CD中
	e_error_code_item_fruit_upper_limit					= 1003086;	//已达到果实食用上限
	e_error_code_item_readd_title						= 1003087;	//重复激活了某个(永久的)称号
	e_error_code_item_element_bag_full					= 1003088;	//符文背包已满
	e_error_code_item_cant_unlock_mount_illusion		= 1003089;	//未达到坐骑解锁条件
	e_error_code_item_cant_unlock_wing_illusion			= 1003090;	//未达到坐骑解锁条件
	e_error_code_item_has_unlocked						= 1003091;	//不能重复解锁
	e_error_code_item_over_time							= 1003092;	//物品已经超过使用时间

}