syntax = "proto3";

/////////////////////////////////////////
// Eye To Daemon Protocol
/////////////////////////////////////////
message E2D_OPEN_FILE {
	int32 nFlag 						= 1;
	bool  bFullPath 				= 2;
	string strFileName 		= 3;
}

message E2D_READ_FILE {
	int32 nDataLen 				= 1;
}

message E2D_WRITE_FILE {
	int32 nDataLen 				= 1;
	bytes content 					= 2;
}

message E2D_SEEK_FILE {
	bool  bKeep 						= 1;
	int32 nOffset 					= 2;
}

message E2D_GET_PORT_INFO {
	int32 port 						= 1;
	int32 pid 							= 2;
	int32 serverid					= 3;
}

message SERVER_ID_MAP {
	int32  nType						= 1;
	int32  nServerID   		= 2;
}

message E2D_SYNC_SERVERID {
	repeated SERVER_ID_MAP  serverids				=1;
}

message E2D_SERVER_PID{
	
}

message E2D_EXE_SYSCMD{
	bool		bNeedOutput					= 1;
	bool 	bNeedCN							= 2;
	string strCommand					= 3;
	string strInputBuffer			= 4;
	string strMD5							= 5;					
}

message E2D_EXE_SYSCMD_LARGE{
	uint32	unNeedOutput				=1;
	uint32 unNeedCN						=2;
	bytes 	strCommand					=3;
	string strInputBuffer			=4;
	string strMD5							=5;					
}

message E2D_UPDATE_SERVER{
	string strPack							= 1;
	string strMD5							= 2;
	int32 nCheck								= 3;
}

message E2D_FILE{
	uint32  unFileLen					= 1;
	string strPath							= 2;
	string strData							= 3;
}

message E2D_FTP_DOWNLOAD{
	string strFtpHost						= 1;
	string strFtpUser						= 2;
	string strFtpPass						= 3;
	string strFtpPath						= 4;
}

/////////////////////////////////////////
// Eye To Server Protocol
/////////////////////////////////////////
message E2S_GM_CMD {
	string gmCode							= 1;
	string data								= 2;
}

message E2S_MAIL_ATTACHMENT {
	int32 itemType		= 1;
	int32 itemId			= 2;
	int32 itemNum 		= 3;
}

message E2S_MAIL_FILTER {
	repeated  uint32  conditon = 1; 
}

message E2S_SEND_MAIL{
	string strTitle									= 1;
	string strSender									= 2;
	string strContent								= 3;
	repeated string strPlayerGUID							= 4;
	repeated E2S_MAIL_ATTACHMENT attachment		= 5;
	repeated E2S_MAIL_FILTER		filter				= 6;
	
}

/////////////////////////////////////////
// Daemon To Eye Protocol
/////////////////////////////////////////
message D2E_GET_SERVERID{
	int32 nPId 								= 1;
	int32 nGameServerId 				= 2;
}

message D2E_FILE_OPERATION {
	int32 nFileLen 			= 1;
	int32 nRetCode 			= 2;
	bytes content 				= 3;
}

message D2E_GET_CPUBASEINFO{
	string strCPUVendor			= 1;
	string strCPUBrand				= 2;
}

message D2E_GET_CPULOAD{
	repeated int32 nCoreLoad					= 1;
	int32 nTotalLoad        	= 2;
}

message D2E_GET_GAME_PROCINFO{
	string strCpuRate					= 1;
	string strVSZ       				= 2;
	string strRSS       				= 3;
}

message D2E_GET_MEMINFO{
	int32 nTotalMem					= 1;
	int32  nFreeMem					= 2;
}

message PROC_INFO{
	string  strProcName 				= 1;
	uint32  unPID 							= 2;
	uint32  unMemUse 					= 3;
	uint32  unVMSize 					= 4;
	uint32  unCPUTime 					= 5;
	uint32  unThreadCount 			= 6;
}	

message D2E_GET_PROCINFO{
	uint32  unProcCount					=1;
	repeated PROC_INFO ProcInfos					=2;
}

message D2E_GAME_PROCINFO{
	bool  	 isAlive 						= 1;
	uint32  unMemUse 					= 2;
	uint32  unVMSize 					= 3;
	uint32  unCPULoad 					= 4;
}

message DISK_BASEINFO{
	string strDiskDesc					=1;
	int32  nTotalSize					=2;
	int32  nFreeSize					=3;
}

message D2E_GET_DISKINFO{
	uint32	 unDiskCount					=1;
	repeated DISK_BASEINFO	DiskInfos				=2;
}
message NET_CARDINFO{
	string strCardDesc					=1;
	string strIP						=2;
	string strMask						=3;
	string strMac						=4;
}
message D2E_GET_NETINFO{
	uint32 nCardCount						=1;
	string strSystemName					=2;
	string strHostName						=3;
	repeated NET_CARDINFO CardInfos					=4;
}

message NET_CARDLOAD{
	uint32 unTXSize					=1;
	uint32 unRXSize					=2;
	uint32 unTXRate					=3;
	uint32 unRXRate					=4;
}

message D2E_GET_CARDLOAD{
	uint32 unCardCount					=1;
	repeated NET_CARDLOAD CardLoads				=2;
}

message D2E_GET_GUARDDIR{
	string strGuardDir					=1;
}

message D2E_EXE_SYSCMD{
	int32 nReturnCode					=1;
	bytes strOutputBuff				=2;
}

message D2E_GET_PORT_INFO{
	uint32	port						= 1;
	uint32 count						= 2;
}

message D2E_UPDATE_SERVER{
	int32 nCurrentStep					= 1;
	int32 nStepCount					= 2;
	int32 nResult					    = 3;
	string strMessage					= 4;  
}

message D2E_FTP_DOWNLOAD{
	int32 nProgress						= 1;
	int32 nRessult							= 2;
	string strMessage					= 3;
}

////////////////////////////////////////
// Server To Daemon Protocol
/////////////////////////////////////////
message S2D_GET_SERVER_INFO{
	int32 nServerType  				= 1;
	int32 nPid  								= 2;
	int32 nGameServerId  			= 3;
}


message eye_proto
{
	message s2d_tick_server_connect
	{
		int32 server_id					= 1;
		int32 server_type					= 2;
	}

	message s2d_send_server_info_to_daemon
	{
		int32 server_id  					= 1;
		int32 server_type  				= 2;
		int32 process_id  					= 3;
		string param_string  				= 4;
	}
	
	message d2s_close_process
	{
		int32 server_id					= 1;
		int32 server_type					= 2;
	}
	
	message d2s_gm_order
	{
		int32 listen_port					= 1;
		int64 handle_index					= 2;
		int32 server_id					= 3;
		string gm_string					= 4;
	}
	
	message s2d_gm_order_end
	{
		int32 listen_port					= 1;
		int64 handle_index					= 2;
		int32 server_id					= 3;
		int32 result_code					= 4;
		string result_msg					= 5;
	}
	
	message s2d_send_string_to_eye
	{
		int32 server_id  					= 1;
		int32 server_type  				= 2;
		string param_string  				= 3;
	}
	
}









