syntax = "proto3";
package faith;

message login_proto
{	
	//此消息会在服务器(FEP)初始化或者更新客户端连接的加密信息时，发送到客户端
	//客户端收到后必须立刻初始化或更新相关信息，然后通过[RDE加密]方法收发数据
	message rde_encryption
	{
		bool			is_gm						= 1;
	}

	// Client 加密数据包后，通过此消息发送给服务器
	message encryped_data
	{
		uint32				index						= 1;	
		uint32				data_len					= 2;	
		string				data						= 3;					// 长度限制为e_max_len
	}

	// 服务器加密数据包后，通过此消息发送给客户端
	message encryped_data_end
	{
		uint32				index						= 1;	
		string				data						= 2;					// 长度限制为e_max_len
	}
	
	message get_server_list
	{
		string			account						= 1;
	}
	message server_list_info
	{
		uint32				server_id					= 1;
		uint32				server_name					= 2;
		string				ip_addr						= 3;
		uint32				port						= 4;
		uint32				server_state				= 5;
		uint32				recommend_state				= 6;
		uint32				begin_time					= 7;	
		
	}
	message get_server_list_end
	{
		repeated	server_list_info			server_list		= 1;
	}
	message role_list_info
	{
		uint32				server_id					= 1;
		uint32				template_id					= 2;
		uint32				exp_level					= 3;
		string				role_name					= 4;
	
	}
	message get_role_list_end
	{
		repeated 	role_list_info			role_list			= 1;
	}
	
	message login_reconnect
	{
		string			account						= 1;
		int32			cur_map_id					= 2;
		int32			cur_map_line_id				= 3;
	}
	message login_reconnect_end
	{
		int32			reconnect_res				= 1;
	}
	
	message login
	{
		string			client_account				= 1;
		string			logic_account				= 2;
		string			password					= 3;
		int32			login_type					= 4;
		string			client_version				= 5;
		uint32			buildTimes					= 6;
		uint32			switch_cluster				= 7;
		uint32			server_id					= 8;
		string			captcha_str					= 9;
		string			ip							= 10;
		string			device_type					= 11;
		string			custom_info					= 12;
		sdk_login_data	sdk_data					= 13;	
	}
	
	message sdk_login_data
	{
		bytes			data						= 1; 
		uint32			data_size					= 2; 
		string			channel_id					= 3;
		string			app_key						= 4;
		string			app_secret					= 5;
		string			device_id					= 6;
		string			opcode						= 7;
		string			model						= 8;
		string			idfa						= 9;
		string			imei						= 10;
		string			android_id					= 11;
		string			mac							= 12;
		string			sn							= 13;
		string			os							= 14;
		string			os_version					= 15;
		string			sdk_version					= 16;
		string			lang						= 17;
		string			recharge_type				= 18;
	}
	
	message login_end
	{
		uint32			result						= 1;
		string			account						= 2;
		string			server_msg					= 4;

		uint32			login_type					= 5;
		uint32			login_type_plus				= 6;
		uint32			queue_pos					= 7;
		uint32			left_time_in_sec			= 8;
		int32			radio_host					= 9;
		bool			is_create_account			= 10;
		int32			online_duration				= 11;
		int32			online_time					= 12;
		int32			age							= 13;
		int32			month_recharge_num			= 14;
		int32			month_recharge_time			= 15;
	}

	message login_queue_status
	{
		uint32			left_time_in_sec			= 1;
		uint32			position					= 2;
	}

	message kickout_account_end
	{
		string			account						= 1;
		string			desc						= 2;
		int32			reason						= 3;				
	}

	message logout
	{
		uint32			type						= 1;
	}

	message logout_end
	{
		uint32			result						= 1;
	}
}


