syntax = "proto3";
package faith;

message mission_proto
{
	message mission_id
	{
		int32 mission_id					= 1;
	}
	
	message mission_info
	{
		repeated int32 mission_info					= 1;
	}
	
	message mission_all
	{
		repeated int32	role_guid					= 1;
		repeated mission_info mission_array			= 2;
		int32 daily_mission_done_num		= 3;
		int32 against_mission_done_num		= 4;
		bool	is_finish					= 5;
	}
	
	message mission_operate
	{
		int32 mission_id					= 1;
		int32 mission_slot					= 2;
		int32 operation_type				= 3;
		int32 operate_npc_id				= 4;
	}
	
	message mission_operate_end
	{
		int32 mission_id					= 1;
		int32 operation_type				= 2;
		int32 operation_end_state			= 3;
		int32 mission_slot					= 4;
		
		repeated mission_info mission_array			= 5;
		int32 daily_mission_done_num		= 6;
		int32 against_mission_done_num		= 7;
	}
		
	message mission_alien_kill_npc
	{
		int32 npc_id						= 1;
		int32 npc_num						= 2;
	}
	
	message mission_finish
	{
		int32 mission_id					= 1;
	}
	
	message reset_mission_test
	{
	
	}
	
	message mission_create_npc_info
	{
		int32 mission_type					= 1;
		int32 npc_count					= 2;
		repeated int64 npc_guid						= 3;
	}
	
	message get_monster_item
	{
		int32 monster_item_name_id			= 1;
	}
	
	message show_chapter_over
	{
		int32 chapter_template_id			= 1;
	}
	
	message use_power_up
	{
		int32 power_up_type				= 1;
	}
}

