syntax = "proto3";
package faith;

message skytreasure_proto
{
	message skytreasure_info_one
	{
		int32 skytreasure_layer_num                   = 1;
		int32 skytreasure_pos	                       = 2;
		int32 skytreasure_pos_in_array	               = 3;
	}
	message skytreasure_all
	{
		repeated skytreasure_info_one  skytreasure_list        = 1;
	}
	message skytreasure_operate
	{
		int32 operation_type	              = 1;
		int32 operation_param1               = 2;
		int32 operation_param2               = 3;
	}
	message skytreasure_operate_end
	{
		int32 operation_type                   = 1;
		int32 operation_result	                = 2;
	}
}

