syntax = "proto3";
package faith;

message st_proto
{
    
	message st_login_fixed_data
	{
		string 		param1				= 1;
		string 		param2 				= 2;	
		string 		param3 				= 3;	
		string 		param4 				= 4;	
		string 		param5 				= 5;	
		string 		param6 				= 6;	
		string 		param7 				= 7;	
		string 		param8 				= 8;	
		string 		param9 				= 9;	
		string 		param10				= 10;	
		string 		param11 			= 11;
		string			param12 			= 12;	
		string 		param13 			= 13;	
		string 		param14 			= 14;
		string			param15				= 15;
	}
	
	message st_player_team_info
	{
	   	int64	team_guid = 1;
		int64	captain_guid = 2;
		int32	member_num = 3;
		int32	team_map_id = 4;
		int32	team_type = 5;
		int32	team_sub_type_id = 6;
		int32	team_one_stop_flags = 7;
		repeated  int64	team_mems_guid = 8;
	}
	
	message st_player_legion_info
	{
		int64		legion_guid = 1;
	 	string		legion_name = 2;
		int32		legion_level = 3;
		int32		legion_role_num = 4;
		int32	    job_title = 5;
		repeated int32		occupied_territorys = 6;
		repeated int32		legion_construction_level = 7;
		int64      legion_power = 8;
	}
	
	message st_game_info
	{
	   int32  server_id = 1;
	   string out_ip = 2;
	   int32  out_port = 3;
	   string server_name = 4;
	   int32  cross_id = 5;
	};
	
	message st_legion_member_info
	{
	  int64  role_guid = 1;
	  string role_name = 2;
	  int64  gs_value = 3;
	  repeated int64  data_ary = 4;
	}
	
	message st_legion_boss_award_get_log
	{
	  int64  role_guid = 1;
	  int32  get_logs_num = 2;
	  repeated  int32  get_logs = 3;
	};
	
	message st_city_war_legion_score
	{
	  int64	legion_guid = 1;
	  string	legion_name = 2;
	  int32	score = 3;
	  int32	bid_price = 4;
	}
	
	message st_player_arena_rank
	{
	  int32	rank_pos = 1;
	  int64	role_guid = 2;
	  string	role_name = 3;
	  int64	gs_value = 4;
	  int32	role_template_id = 5;
	  int64	challenge_end_time = 6;
	  int32	robot_template_id = 7;
	  int32	military_level = 8;
	  int32	vip_level = 9;
	  string	game_channel = 10;
	}
	
	message st_unit_info
	{
	   int64  role_guid = 1;
	   string account = 2;
	   string role_name = 3;
	   string role_appearance = 4;
	   string role_first_kill_ary = 5;
	   int64  map_guid = 6;
	   repeated int64  data_i64_ary = 7;
	   repeated int32  data_ary = 8;
	 
	}
	
	message st_base_att_info
	{
	   repeated int64 data_ary = 1;
	}
	
	message st_skill_info
	{
	   repeated int32 data_ary = 1;
	}
	
	message st_item_info
	{
	   int64  item_guid = 1;
	   repeated int32  data_ary = 2;
	   string param_str = 3;
	}
	
	message st_buff_info
	{
	    int64	buff_guid = 1;
		int64	sender_guid = 2;
		repeated    int32	data_ary = 3;
	}
	message st_arena_char_fight_att
	{
	  	int64	role_guid = 1;
		repeated    double	att_value = 2;
	}
	
	message st_spirit_info
	{
	   int64	spirit_guid = 1;								// guid		
	   repeated	    int32	data_ary = 2;
	}
	message st_belief_info
	{
	   repeated	   int32	data_ary = 1;		
	}
	message st_fake_player_info
	{
	
		int32			data_block_mask = 1;
		int64			guid = 2;
		st_unit_info	role_info = 3;
		st_base_att_info	att_info = 4;
		int32				skill_num = 5;
		repeated  st_skill_info		skill_data = 6;
		int32				item_num = 7;
		repeated  st_item_info		item_data = 8;
		int32				buff_num = 9;
		repeated  st_buff_info		buff_data = 10;
		st_arena_char_fight_att   m_fight_att = 11;
		st_spirit_info			   spirit_data = 12;
		repeated  st_belief_info			   belief_data = 13;
		int32					   belief_num = 14;
	};
	
	message st_auction_info
	{
	   int64  seller_guid = 1;
	   string seller_name = 2;
	   int64  buyer_guid = 3;
	   string buyer_name = 4;
	   int32  trade_type = 5;
	   int32  seller_vip_level = 6;
	   int32  auction_type = 7;
	   int32  auction_sub_type = 8;
	   int32  item_color = 9;
	   int32  quality_level = 10;
	   int32  class_limit = 11;
	   string item_name = 12;
	   int64  sell_time = 13;
	   int64  deal_time = 14;
	   int32  sell_money_type = 15;
       int64  sell_total_money = 16;
	   int64  sell_single_money =17;
	   int64  cur_bid_money = 18;
	   int32  is_show = 19;
	   int32  add_time = 20;
	   int32  is_sky_order = 21;
	   int64  show_guid = 22;
	   st_item_info item_info = 23;
	}
	
	
	message st_server_harry_msg
	{
	  int32		server_id = 1;
      int32		server_money = 2;
	  int32		special_money = 3;
	  int64		first_player_guid = 4;
	  int64		second_player_guid = 5;
	  int64		third_player_guid = 6;
	  string		first_player_name = 7;
	}
	
	message st_time_limit_activity_temp_db
	{
	   int32		ActGuid = 1;
	   int32		AttributeId = 2;
	   int32		ActivityType = 3;
	   int32		CycleParamType = 4;
	   string		CycleParamNum = 5;
	   string		CycleFirstId = 6;
	   int32		OpenType = 7;
	   int32		OpenServerDate = 8;
	   string		OpenSpencificDate = 9;
	   int32		FirstOpenDayOfWeek = 10;
	   int32		DurationDays = 11;
	   int32		CycleDays = 12;
	   int32		ShowType = 13;
	   string		TextImage = 14;
	   string		ParamArr1 = 15;
	   string		ParamArr2 = 16;
	   string		ParamArr3 = 17;
       string		ParamArr4 = 18;
	   string		ParamArr5 = 19;
	   int32		IsEndAct = 20;
	   string		OriginalCycleFirstId = 21;
	   string		OldCycleFirstId = 22;
	   int32		CreateTime = 23;
	   int32		EndTime = 24;
	   int32		TemplateFromType = 25;
	   int32		RefreshTime = 26;
	}
	
	message st_time_limit_activity_branch_temp_db
	{
	  int32		ActGuid = 1;
	  int32		AttributeId = 2;
	  int32		ActivityType = 3;
	  int32		CycleIndex = 4;
	  string		Condition = 5;
	  string		Reward = 6;
	  string		TextImage = 7;
	  string	    ParamArr1 = 8;
	  string		ParamArr2 = 9;
	  string		ParamArr3 = 10;
	  string		ParamArr4 = 11;
	  string		ParamArr5 = 12;
	}
	
	message st_assist_fight_info 
	{
	  int32	    assist_fight_type = 1;
	  int64		asssit_fight_guid = 2;
	  string		role_name = 3;
	  int32		role_lv = 4;
	  int32       role_professional = 5;
	  int32       role_head_icon = 6;
	  int32		boss_id = 7;
	  int64       boss_guid = 8;
	  int32		map_id = 9;
	  int64		map_guid = 10;
	  repeated  float       unit_location = 11;
	  repeated  float       unit_rotation = 12;
	  repeated	int64       assist_guid_list = 13;
	  int32       assist_fight_tag = 14;
	  int64       legion_guid = 15;
	  int32       start_assist_time = 16;
	}
	
	message st_element_war_match_role_info
	{
	  int64		role_guid = 1;
	  string		role_name = 2;
	  string		server_name = 3;
	  int32		server_id = 4;
	  int32		template_id = 5;
	  int32		role_level = 6;
	  int32		score_num = 7;
	  int32		total_join_num = 8;
	  int32		total_win_num = 9;
	  int32		last_win_num = 10;
	  int32		vip_level = 11;
      string		role_server_out_ip = 12;
	  int32		role_server_out_port = 13;
	  bool		is_robor = 14;
	  int32		robor_template_id = 15;
	 }
	
	message st_element_war_match_info
	{
	  repeated	st_element_war_match_role_info first_role_info = 1;
	  repeated	st_element_war_match_role_info second_role_info = 2;
	  int32	map_level = 3;

	};
	
	
	message st_ranking_player_info
	{
	  int64	role_guid = 1;
	  string	role_name = 2;
	  int64	ranking_type = 3;
	  int64	ranking_value = 4;
	  int64	save_time = 5;
	  int64	supporting_guid = 6;						
	  string	supporting_name = 7;
	  int32	vip_level  = 8;
	  int32	Peak = 9;
	  int32	server_id = 10;
	  string	game_channel = 11;
	  int64	standby_parameter = 12;						
	}
	
	message st_auction_share_info
	{
		int64	item_guid = 1;
		int64	role_guid = 2;
		float	share_rate = 3;
		string	share_mail_title = 4;
		string	share_mail_content = 5;
	};
	
	message st_gain_treasure_record_player_info_db
	{
		string		role_name = 1;
		string		gain_item_template_id = 2;
		int64      role_guid = 3;
	
	};
	
	message st_gain_treasure_record_info_one_db
	{
		int32	boss_spawn_point_template_id = 1;
		int32	killed_stamp = 2;
		repeated st_gain_treasure_record_player_info_db	player_info_arr = 3;	
	};
	
	message st_gain_treasure_record_player_info
	{
		string	 role_name = 1;
	    repeated int32	 gain_item_template_id = 2;
		int64	 role_guid = 3;
	
	};
	
	message st_gain_treasure_record_info_one
	{
		int32	 boss_spawn_point_template_id = 1;
		int32	 killed_stamp = 2;
		repeated st_gain_treasure_record_player_info	player_info_arr = 3;
	};
	
	message st_gain_treasure_player_info
	{
		int64					player_guid = 1;
		string					player_name = 2;
	
	};
	
	
	
	message st_gain_treasure_boss_info
	{
		int32			boss_spawn_point_template_id = 1;
		int64			boss_guid = 2;							//boss死亡时guid为0
		int32			next_refresh_stamp = 3;
		repeated st_gain_treasure_player_info			player_info = 4;
		
	};
	
	
	message st_single_map_record
	{
		int64	role_guid = 1;
		string	role_name = 2;
		int32	value = 3;
	};
	
	message st_db_best_record
	{
		int32	map_template_id = 1;
		int64  role_guid = 2;
		string	role_name = 3;
		int32	value = 4;

	};
	
	message st_big_player_db
	{
		int32 player_type = 1;
		int64 role_guid  = 2;
	};
	
	
	
	
	
	
	
}

