delete from low_game_schema_1.`auction`where low_game_schema_1.`auction`.`item_guid`in(SELECT`item_guid`FROM low_game_schema.`auction`);
delete from low_game_schema_1.`auction_bid_record`where low_game_schema_1.`auction_bid_record`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`auction_bid_record`);
delete from low_game_schema_1.`auction_record`where low_game_schema_1.`auction_record`.`record_guid`in(SELECT`record_guid`FROM low_game_schema.`auction_record`);
delete from low_game_schema_1.`auction_share_list`where low_game_schema_1.`auction_share_list`.`item_guid`in(SELECT`item_guid`FROM low_game_schema.`auction_share_list`);
delete from low_game_schema_1.`best_record_info`where low_game_schema_1.`best_record_info`.`map_template_id`in(SELECT`map_template_id`FROM low_game_schema.`best_record_info`);
delete from low_game_schema_1.`big_player`where low_game_schema_1.`big_player`.`big_player_type`in(SELECT`big_player_type`FROM low_game_schema.`big_player`);
delete from low_game_schema_1.`cloud_shop_role_record`where low_game_schema_1.`cloud_shop_role_record`.`player_uid`in(SELECT`player_uid`FROM low_game_schema.`cloud_shop_role_record`);
delete from low_game_schema_1.`cloud_shop_server_info`where low_game_schema_1.`cloud_shop_server_info`.`activity_date`in(SELECT`activity_date`FROM low_game_schema.`cloud_shop_server_info`);
delete from low_game_schema_1.`cross_world_boss`where low_game_schema_1.`cross_world_boss`.`boss_template_id`in(SELECT`boss_template_id`FROM low_game_schema.`cross_world_boss`);
delete from low_game_schema_1.`cross_ladder_ranking`where low_game_schema_1.`cross_ladder_ranking`.`ranking_id`in(SELECT`ranking_id`FROM low_game_schema.`cross_ladder_ranking`);
delete from low_game_schema_1.`cross_ladder_role_info`where low_game_schema_1.`cross_ladder_role_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`cross_ladder_role_info`);
delete from low_game_schema_1.`cross_role_info`where low_game_schema_1.`cross_role_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`cross_role_info`);
delete from low_game_schema_1.`cross_role_war`where low_game_schema_1.`cross_role_war`.`id`in(SELECT`id`FROM low_game_schema.`cross_role_war`);
delete from low_game_schema_1.`cross_server_harry_info`where low_game_schema_1.`cross_server_harry_info`.`server_id`in(SELECT`server_id`FROM low_game_schema.`cross_server_harry_info`);
delete from low_game_schema_1.`cross_server_overload_city_info`where low_game_schema_1.`cross_server_overload_city_info`.`legion_rank`in(SELECT`legion_rank`FROM low_game_schema.`cross_server_overload_city_info`);
delete from low_game_schema_1.`cross_server_pk_info`where low_game_schema_1.`cross_server_pk_info`.`war_idex`in(SELECT`war_idex`FROM low_game_schema.`cross_server_pk_info`);
delete from low_game_schema_1.`cross_world_boss`where low_game_schema_1.`cross_world_boss`.`boss_template_id`in(SELECT`boss_template_id`FROM low_game_schema.`cross_world_boss`);
delete from low_game_schema_1.`gain_treasure_record`where low_game_schema_1.`gain_treasure_record`.`boss_spawn_point_template_id`in(SELECT`boss_spawn_point_template_id`FROM low_game_schema.`gain_treasure_record`);
delete from low_game_schema_1.`gm_role_lock`where low_game_schema_1.`gm_role_lock`.`role_mark`in(SELECT`role_mark`FROM low_game_schema.`gm_role_lock`);
delete from low_game_schema_1.`legion_applicant`where low_game_schema_1.`legion_applicant`.`legion_guid`in(SELECT`legion_guid`FROM low_game_schema.`legion_applicant`);
delete from low_game_schema_1.`legion_bonus_info`where low_game_schema_1.`legion_bonus_info`.`legion_guid`in(SELECT`legion_guid`FROM low_game_schema.`legion_bonus_info`);
delete from low_game_schema_1.`legion_boss_record`where low_game_schema_1.`legion_boss_record`.`legion_guid`in(SELECT`legion_guid`FROM low_game_schema.`legion_boss_record`);
delete from low_game_schema_1.`legion_city_bid_info`where low_game_schema_1.`legion_city_bid_info`.`territory_id`in(SELECT`territory_id`FROM low_game_schema.`legion_city_bid_info`);
delete from low_game_schema_1.`legion_city_info`where low_game_schema_1.`legion_city_info`.`occupation_legion_guid`in(SELECT`occupation_legion_guid`FROM low_game_schema.`legion_city_info`);
delete from low_game_schema_1.`legion_event`where low_game_schema_1.`legion_event`.`legion_guid`in(SELECT`legion_guid`FROM low_game_schema.`legion_event`);
delete from low_game_schema_1.`legion_get_boss_award_log`where low_game_schema_1.`legion_get_boss_award_log`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`legion_get_boss_award_log`);
delete from low_game_schema_1.`legion_info`where low_game_schema_1.`legion_info`.`legion_guid`in(SELECT`legion_guid`FROM low_game_schema.`legion_info`);
delete from low_game_schema_1.`legion_member_info`where low_game_schema_1.`legion_member_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`legion_member_info`);
delete from low_game_schema_1.`legion_warehouse_log`where low_game_schema_1.`legion_warehouse_log`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`legion_warehouse_log`);
delete from low_game_schema_1.`mail_globel_mail`where low_game_schema_1.`mail_globel_mail`.`mail_guid`in(SELECT`mail_guid`FROM low_game_schema.`mail_globel_mail`);
delete from low_game_schema_1.`mail_globel_mail_item`where low_game_schema_1.`mail_globel_mail_item`.`item_guid`in(SELECT`item_guid`FROM low_game_schema.`mail_globel_mail_item`);
delete from low_game_schema_1. `oracle_trial_player_info`where low_game_schema_1. `oracle_trial_player_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `oracle_trial_player_info`);
delete from low_game_schema_1. `other_server_mail_record`where low_game_schema_1. `other_server_mail_record`.`source_server_id`in(SELECT`source_server_id`FROM low_game_schema. `other_server_mail_record`);
delete from low_game_schema_1. `ranking_arena`where low_game_schema_1. `ranking_arena`.`position`in(SELECT`position`FROM low_game_schema. `ranking_arena`);
delete from low_game_schema_1. `ranking_arena_challenge_log`where low_game_schema_1. `ranking_arena_challenge_log`.`log_id`in(SELECT`log_id`FROM low_game_schema. `ranking_arena_challenge_log`);
delete from low_game_schema_1. `ranking_role_worship`where low_game_schema_1. `ranking_role_worship`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `ranking_role_worship`);
delete from low_game_schema_1. `recharge_record`where low_game_schema_1. `recharge_record`.`order_id`in(SELECT`order_id`FROM low_game_schema. `recharge_record`);
delete from low_game_schema_1. `red_package_info`where low_game_schema_1. `red_package_info`.`red_package_guid`in(SELECT`red_package_guid`FROM low_game_schema. `red_package_info`);
delete from low_game_schema_1. `red_package_receiver_info`where low_game_schema_1. `red_package_receiver_info`.`red_package_guid`in(SELECT`red_package_guid`FROM low_game_schema. `red_package_receiver_info`);
delete from low_game_schema_1. `role_achievement`where low_game_schema_1. `role_achievement`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_achievement`);
delete from low_game_schema_1. `role_active_degree`where low_game_schema_1. `role_active_degree`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_active_degree`);
delete from low_game_schema_1. `role_att`where low_game_schema_1. `role_att`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_att`);
delete from low_game_schema_1. `role_belief`where low_game_schema_1. `role_belief`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_belief`);
delete from low_game_schema_1. `role_boss_island`where low_game_schema_1. `role_boss_island`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_boss_island`);
delete from low_game_schema_1. `role_buff`where low_game_schema_1. `role_buff`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_buff`);
delete from low_game_schema_1. `role_chat_record`where low_game_schema_1. `role_chat_record`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_chat_record`);
delete from low_game_schema_1. `role_convert`where low_game_schema_1. `role_convert`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_convert`);
delete from low_game_schema_1. `role_daily_must_do_count`where low_game_schema_1. `role_daily_must_do_count`.`role_guid`in(SELECT`role_guid`FROM low_game_schema. `role_daily_must_do_count`);
delete from low_game_schema_1.`role_demons_tower`where low_game_schema_1.`role_demons_tower`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_demons_tower`);
delete from low_game_schema_1.`role_element_heart`where low_game_schema_1.`role_element_heart`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_element_heart`);
delete from low_game_schema_1.`role_event`where low_game_schema_1.`role_event`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_event`);
delete from low_game_schema_1.`role_fight_att`where low_game_schema_1.`role_fight_att`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_fight_att`);
delete from low_game_schema_1.`role_first_time_do`where low_game_schema_1.`role_first_time_do`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_first_time_do`);
delete from low_game_schema_1.`role_gain_treasure`where low_game_schema_1.`role_gain_treasure`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_gain_treasure`);
delete from low_game_schema_1.`role_goods`where low_game_schema_1.`role_goods`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_goods`);
delete from low_game_schema_1.`role_guide_record`where low_game_schema_1.`role_guide_record`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_guide_record`);
delete from low_game_schema_1.`role_harry_record`where low_game_schema_1.`role_harry_record`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_harry_record`);
delete from low_game_schema_1.`role_history_highest_record`where low_game_schema_1.`role_history_highest_record`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_history_highest_record`);
delete from low_game_schema_1.`role_info`where low_game_schema_1.`role_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_info`);
delete from low_game_schema_1.`role_item`where low_game_schema_1.`role_item`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_item`);
delete from low_game_schema_1.`role_logic`where low_game_schema_1.`role_logic`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_logic`);
delete from low_game_schema_1.`role_mail`where low_game_schema_1.`role_mail`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_mail`);
delete from low_game_schema_1.`role_mail_by_id`where low_game_schema_1.`role_mail_by_id`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_mail_by_id`);
delete from low_game_schema_1.`role_mail_item`where low_game_schema_1.`role_mail_item`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_mail_item`);
delete from low_game_schema_1.`role_map_record`where low_game_schema_1.`role_map_record`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_map_record`);
delete from low_game_schema_1.`role_marry`where low_game_schema_1.`role_marry`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_marry`);
delete from low_game_schema_1.`role_mission`where low_game_schema_1.`role_mission`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_mission`);
delete from low_game_schema_1.`role_money`where low_game_schema_1.`role_money`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_money`);
delete from low_game_schema_1.`role_offline_chat`where low_game_schema_1.`role_offline_chat`.`chat_guid`in(SELECT`chat_guid`FROM low_game_schema.`role_offline_chat`);
delete from low_game_schema_1.`role_passive_skill`where low_game_schema_1.`role_passive_skill`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_passive_skill`);
delete from low_game_schema_1.`role_person_information`where low_game_schema_1.`role_person_information`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_person_information`);
delete from low_game_schema_1.`role_phantom`where low_game_schema_1.`role_phantom`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_phantom`);
delete from low_game_schema_1.`role_pokedex`where low_game_schema_1.`role_pokedex`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_pokedex`);
delete from low_game_schema_1.`role_ranking`where low_game_schema_1.`role_ranking`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_ranking`);
delete from low_game_schema_1.`role_relation`where low_game_schema_1.`role_relation`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_relation`);
delete from low_game_schema_1.`role_service_goal`where low_game_schema_1.`role_service_goal`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_service_goal`);
delete from low_game_schema_1.`role_service_rank`where low_game_schema_1.`role_service_rank`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_service_rank`);
delete from low_game_schema_1.`role_service_rank_reward_state`where low_game_schema_1.`role_service_rank_reward_state`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_service_rank_reward_state`);
delete from low_game_schema_1.`role_seven_day_goal`where low_game_schema_1.`role_seven_day_goal`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_seven_day_goal`);
delete from low_game_schema_1.`role_show_info`where low_game_schema_1.`role_show_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_show_info`);
delete from low_game_schema_1.`role_skill`where low_game_schema_1.`role_skill`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_skill`);
delete from low_game_schema_1.`role_special_name`where low_game_schema_1.`role_special_name`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_special_name`);
delete from low_game_schema_1.`role_spirit`where low_game_schema_1.`role_spirit`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_spirit`);
delete from low_game_schema_1.`role_talent`where low_game_schema_1.`role_talent`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_talent`);
delete from low_game_schema_1.`role_time`where low_game_schema_1.`role_time`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_time`);
delete from low_game_schema_1.`role_time_limit_activity`where low_game_schema_1.`role_time_limit_activity`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_time_limit_activity`);
delete from low_game_schema_1.`role_tinder`where low_game_schema_1.`role_tinder`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_tinder`);
delete from low_game_schema_1.`role_title`where low_game_schema_1.`role_title`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_title`);
delete from low_game_schema_1.`role_treasure`where low_game_schema_1.`role_treasure`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_treasure`);
delete from low_game_schema_1.`role_welfare`where low_game_schema_1.`role_welfare`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_welfare`);
delete from low_game_schema_1.`role_welfare_random_get`where low_game_schema_1.`role_welfare_random_get`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_welfare_random_get`);
delete from low_game_schema_1.`role_worship_target`where low_game_schema_1.`role_worship_target`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_worship_target`);
delete from low_game_schema_1.`role_ws_info`where low_game_schema_1.`role_ws_info`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_ws_info`);
delete from low_game_schema_1.`role_yesterday_must_do_remain`where low_game_schema_1.`role_yesterday_must_do_remain`.`role_guid`in(SELECT`role_guid`FROM low_game_schema.`role_yesterday_must_do_remain`);
delete from low_game_schema_1.`server_info`where low_game_schema_1.`server_info`.`big_group_id`in(SELECT`big_group_id`FROM low_game_schema.`server_info`);
delete from low_game_schema_1.`server_refresh`where low_game_schema_1.`server_refresh`.`time_type`in(SELECT`time_type`FROM low_game_schema.`server_refresh`);
delete from low_game_schema_1.`time_limit_activity_ws_info`where low_game_schema_1.`time_limit_activity_ws_info`.`act_type`in(SELECT`act_type`FROM low_game_schema.`time_limit_activity_ws_info`);
delete from low_game_schema_1.`time_limit_branch_template`where low_game_schema_1.`time_limit_branch_template`.`act_guid`in(SELECT`act_guid`FROM low_game_schema.`time_limit_branch_template`);
delete from low_game_schema_1.`time_limit_template`where low_game_schema_1.`time_limit_template`.`act_guid`in(SELECT`act_guid`FROM low_game_schema.`time_limit_template`);
delete from low_game_schema_1.`transfer_channel`where low_game_schema_1.`transfer_channel`.`obj_type`in(SELECT`obj_type`FROM low_game_schema.`transfer_channel`);
delete from low_game_schema_1.`world_boss`where low_game_schema_1.`world_boss`.`npc_respawn_point_template_id`in(SELECT`npc_respawn_point_template_id`FROM low_game_schema.`world_boss`);
delete from low_game_schema_1.`ws_lucky_draw_record`where low_game_schema_1.`ws_lucky_draw_record`.`info_guid`in(SELECT`info_guid`FROM low_game_schema.`ws_lucky_draw_record`);