#include "BuffDataTemplate_S.h"

namespace faith
{
    void BuffDataTemplateSize()
    {
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("Type");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("Series");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("Race");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("Level");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("BeginActions");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("EndActions");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("EffectActions");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("CycActions");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("EventCondition");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("EventActions");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("DuringTime");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("JumpTime");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("BuffPercent");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("CanCannel");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("ExistWhenDeath");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("DelByResetSkill");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("TimeEndKeep");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("MaxPileDepth");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("SameLevelCover");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("DiffLevelCover ");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("SameLevelSameSenderWrap ");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("SameLevelDifSenderWrap");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("SameLevelTimeCumulative");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("DiffevelTimeCumulative");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("SaveType");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("Sync");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("OtherPlayerCanSee");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("IsShowInExhibition");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("ResourceID	");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("DisplayPriority");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("InvalidMapTypeArray");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("ValidMapTypeArray");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("IsShowAbNormalBuff");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("MapEndClear");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("InvalidBoss");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("NotInvalidFakerPlayer");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("IsFashionBuff");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("MountStatusHidden");
        template_size::get_instance().template_size_map[e_BuffDataTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_BuffDataTemplate].push_back("NeedRefresh");
    }
}
