#include "DailyActivitiesTemplate_S.h"

namespace hld
{
    void DailyActivitiesTemplateSize()
    {
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ActivityTyp");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("TargetValue");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("AddValue");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("VIPAddNum");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("TagType");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("SubTabArray");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ActivityOrder");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ShowFlagArray");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("DesStringTemplateId");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("OpenTimeDescription");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ExpTitleIcon");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ExpTitleIconNum");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("MustDoRewardClass");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("PeopleTitleIcon");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("RewardClassArray");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<float>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("DynamicMoneyShow");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("StaticMoneyShow");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ItemShow");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("WidgetJumpArray");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("IsCanFindBack");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("EffectLevelRange");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<float>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("DynamicFindBackInfo");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("StaticFindBackInfo");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("SiliverBackCost");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("DiamondBackCost");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("ItemFindBackArray");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("MapTemplateId");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("FuncUnlockName");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("SubscribeRewardId");
        template_size::get_instance().template_size_map[e_DailyActivitiesTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_DailyActivitiesTemplate].push_back("InMapList");
    }
}
