#include "GuideTriggerTemplate_S.h"

namespace hld
{
    void GuideTriggerTemplateSize()
    {
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("TriggerGuideID");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedLevel");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedMission");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("MustNeedMission");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedFuncUnlock");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NewFuncUnlockFuncId");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("LandWelfareId");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("IsHitFirstGuide");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedItem");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedItemType");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedMoney");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("RoleState");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("OpenWidget");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("FirstTimeDo");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedGodHoodGrade");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedTinderOrder");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedShowWidgetName");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedFlyMaxHedit");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("DeadCanGuide");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedMapID");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NeedMapState");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("NewGudieNeedRePlay");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("EndGuideNeedOpenMp");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("OpenGuideNoOpenMp");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("TriggerInPublicMap");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("ResetSkillType");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("KeepWidget");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("is_accord");
        template_size::get_instance().template_size_map[e_GuideTriggerTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_GuideTriggerTemplate].push_back("LoginCheckGuideMission");
    }
}
