#include "NpcSpawnPointTemplate_S.h"

namespace faith
{
    void NpcSpawnPointTemplateSize()
    {
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("MapId");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("TemplateId");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("NpcType");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("PosX");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("PosY");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("PosZ");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("TpPosX");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("TpPosY");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("TpPosZ");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("EnvironmentType");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("NextPosX");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("NextPosY");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("NextPosZ");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("Roll");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("Pitch");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("Yaw");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("RespawnType");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("RespawnTime");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("RespawnPeriod");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("RespawnByDayArray");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("IsCreateByMapCreate");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("Area");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("SpawnRate");
        template_size::get_instance().template_size_map[e_NpcSpawnPointTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_NpcSpawnPointTemplate].push_back("NextSpawnNpcId");
    }
}
