#include "PlayerUpgradeTemplate_S.h"

namespace faith
{
    void PlayerUpgradeTemplateSize()
    {
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("ClassType");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("Level");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("NextLevelExp");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("MoveSpeedForce");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("MaxBagCount");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("EnergyBackValue");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("EnergyBackTime");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("EnergyMax");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("RandomItem");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("SpecialRandomItem");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("RandomTreasure");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("vector<float>");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("AttPermanent");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("SkillCount");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("PassiveSkillCount");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("SpriteCount");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("vector<float>");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("AttArray");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("BaseExp");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("BaseCoin");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("DailyMissionLibrary");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("AgainstMissionLibrary");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("TargetGsValue");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("TalentNum");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("AddPoints");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("MeditationExpAddition");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("MeditationStandardGs");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("vector<float>");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("PureHurtAttArray");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("MarryMissionLibrary");
        template_size::get_instance().template_size_map[e_PlayerUpgradeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PlayerUpgradeTemplate].push_back("ReplyEnergy");
    }
}
