#include "PropBasicAttributeTemplate_S.h"

namespace hld
{
    void PropBasicAttributeTemplateSize()
    {
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("UseType");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("MoneyChange");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("ItemGet");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<float>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("RoleAttributeChange");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("UseCD");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("WidgetJumpArray");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("SpawnNpcId");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("TitleGet");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("BagSendInType");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("FriendlinessAdd");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("OtherRecvItemID");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("LevelUp");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("FuncLevelLimit");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("UpgradeProtectInfoArray");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("ReducePkValue");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("GetRechargeNum");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("logic_id");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("NeedRedTip");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("EffectiveTime");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("ExperienceVipLevel");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("AddMapCount");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("ExpNum");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("ChooseItem");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("MeditationMedicineTime");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("OnlyUseInSelfServer");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("AddHeartValue");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("SummonNpcID");
        template_size::get_instance().template_size_map[e_PropBasicAttributeTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_PropBasicAttributeTemplate].push_back("AddMapTimeArr");
    }
}
