#include "ServiceRankTemplate_S.h"

namespace hld
{
    void ServiceRankTemplateSize()
    {
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("Type");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("RankingType");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("RankingSubType");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("EndTime");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetRewardEndTime");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("MinValue");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("RankNum");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("RankImgArray");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ItemRewardOne");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ItemRewardTwo");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ItemRewardThree");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ItemRewardFour");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ItemRewardFive");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ShowTextStrArr");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayWidgetJumpArray1");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayUnlockIdArray1");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayWidgetJumpArray2");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayUnlockIdArray2");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayWidgetJumpArray3");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayUnlockIdArray3");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayWidgetJumpArray4");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("GetWayUnlockIdArray4");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("RankingShowImg");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("ModelTemplateIdArray");
        template_size::get_instance().template_size_map[e_ServiceRankTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_ServiceRankTemplate].push_back("RankIndexAndValueText");
    }
}
