#include "SkillResTemplate_S.h"

namespace hld
{
    void SkillResTemplateSize()
    {
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("template_base");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("AttributeId");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("IconInfo");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("HurtSoundType");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("HurtSound");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("FlyEffNomal");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("FlyEffIce");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("FlyEffFire");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("FlyEffLight");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("FlyEffDark");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("vector<int32>");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("HurtEff");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("NoOpenStrId");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SpellSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("CastSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("ChannelSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("AttackSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("HurtSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("MotionBlendSpaceId");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("OtherSpellSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("OtherCastSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("OtherChannelSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("OtherAttackSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("string");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("OtherHurtSections");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillName");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillTemplate");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillDiscribe");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillSmallDiscribe");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillUnlockDescribe");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillRecommendDescribe");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillUnlockConditionDescribe");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("LightStrength");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("LightR");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("LightG");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("LightB");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("LightA");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("ExploreAtCapsule");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillVedio");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("int32");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("CacheNpcId");
        template_size::get_instance().template_size_map[e_SkillResTemplate].push_back("float");
        template_size::get_instance().template_key_map[e_SkillResTemplate].push_back("SkillVedioLen");
    }
}
